### ISSUE TITLE
Weird `.` app in `updater` script's output

### ISSUE THREAD

**Issue by cycool29** [Botspot/pi-apps#1004]
When I run the `updater` script, it shows the weird `.` app, both cli and gui.

GUI:

![image](https://user-images.githubusercontent.com/88134003/135795835-da114837-289b-4053-86b2-b275ec0e9b7a.png)

CLI:

![image](https://user-images.githubusercontent.com/88134003/135796310-d3df05b7-4427-4628-8f94-d542436d00ba.png)

**Comment by Botspot** [comment]
`pi-apps/manage check-all` returns a period (`.`) character if no apps were updatable. This was necessary due to how its output was parsed. Originally, `check-all`'s output was all standard output (including the logging stuff), and the updatable apps were on the last line of output, each one separated by the `|` character. (if memory serves)
The period allowed the `updater` script to properly detect the last line of the output. If the last line _was_ a period, `updater` would clear the variable.
But that was in early Pi-Apps days. For most of Pi-Apps history, `check-all` outputted debug stuff to stderr, while each updatable app newline-separated and outputted to stdout. But I never bothered to remove the period character as it wasn't causing any trouble. Well it now is, so I've just removed the period-workaround in commit https://github.com/Botspot/pi-apps/commit/be523e3debae0f149b50eb9c8a60ebe427ce0e9f.

Why was this not caught when I was rewriting the updater? Because in all my tests I had multiple updatable apps, not ever zero. (The "updatable" apps weren't outdated, they were future improvements to apps that had not been declared "stable" yet)
