### ISSUE TITLE
WPS Office

### ISSUE THREAD

**Issue by fabianmendes** [Botspot/pi-apps#105]
May you please make available this great app, thanks!
Here is the ".deb" file that should work, but I can't install it. It should be easy, but I don't know anything about it. **https://wdl1.cache.wps.cn/wps/download/ep/Linux2019/9615/wps-office_11.1.0.9615_arm64.deb** (info extracted from https://archived.forum.manjaro.org/t/guide-install-wps-office-aarch64-in-manjaro-arm-via-aur/155332 for credits)

It says that needs libc6, but all we already have it (updated), so it's impossible to installing it because you can't install that libc6 due to already having an updated version that the WPS Office deb file doesn't recognize!

**Comment by Botspot** [comment]
What does WPS Office do?

**Comment by fabianmendes** [comment]
It is the most vale alternative to Microsoft Office, actually quite better than Open office OR Libreoffice, and open-source with features that no-other office package there alike have

**Comment by Botspot** [comment]
Oh, looks like it's not open source... So there's no compiling it. Interesting.

**Comment by Botspot** [comment]
Do you know if there's a 32bit arm release?

**Comment by fabianmendes** [comment]
No I dont know, o Just know the T that's for arm64 arch but it doesnt compile on raspberry pi (armhf)

**Comment by Botspot** [comment]
Interesting - I found a later arm64 version. https://wdl1.cache.wps.cn/wps/download/ep/Linux2019/9719/wps-office_11.1.0.9719_arm64.deb

**Comment by fabianmendes** [comment]
> Interesting - I found a later arm64 version. https://wdl1.cache.wps.cn/wps/download/ep/Linux2019/9719/wps-office_11.1.0.9719_arm64.deb

Oh, does it work??  :O

**Comment by Botspot** [comment]
> > Interesting - I found a later arm64 version. https://wdl1.cache.wps.cn/wps/download/ep/Linux2019/9719/wps-office_11.1.0.9719_arm64.deb
> 
> Oh, does it work?? :O

I haven't tested it yet.

**Comment by Botspot** [comment]
I GOT IT WORKING!!!
![2020-11-28-150205_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/100526013-cd077d00-318a-11eb-9df3-4258d13f17df.png)

**Comment by fabianmendes** [comment]
niice I'll do the same let me see

**Comment by Botspot** [comment]
I'll make an app about it soon.

**Comment by fabianmendes** [comment]
> I'll make an app for it soon.

Thaaaanks, haha because I've tried that version you've just shared to me here and I still couldn't install it!

![2020-11-28-202755_800x480_scrot](https://user-images.githubusercontent.com/31230743/100528924-7749c980-31b8-11eb-8691-26b9d28c6dfd.png)

**Comment by Botspot** [comment]
@fabianmendes Your OS has to be 64-bit for it to work.

**Comment by fabianmendes** [comment]
I think it does, if not, what can I do? (Also, I know it is 64-bit because I've installed many apps that say it is. But I'm not totally sure)

**Comment by Botspot** [comment]
> I think it does, if not, what can I do? (Also, I know it is 64-bit because I've installed many apps that say it is. But I'm not totally sure)
> 
> Did you see on the screenshot that it's still saying that thing of "libc6"?

In that case I'm not sure. It works for me.

Here, try the Pi-Apps beta version:  
[WPS Office.zip](https://github.com/Botspot/pi-apps/files/5611441/WPS.Office.zip)

**Comment by Botspot** [comment]
Okay I've now added WPS Office to Pi-Apps as of commit 004f9ca533eb6897b8b2098c8b91f3bdb987186a.

**Comment by fabianmendes** [comment]
Hi, excuse me @Botspot, I can't see this app on the pi-apps list, I want to try to install it again but there's not listed to do it :$

**Comment by Itai-Nelken** [comment]
> Hi, excuse me @Botspot, I can't see this app on the pi-apps list, I want to try to install it again but there's not listed to do it :$

@fabianmendes it's only 64bit, you can't use it on 32bit systems/OS's.

**Comment by fabianmendes** [comment]
Oh all right, so. If I want to turn MY RPi OS into 64-bits. I must to
reflash it, right?

**Comment by Itai-Nelken** [comment]
> Oh all right, so. If I want to turn MY RPi OS into 64-bits. I must to reflash it, right?
> […](#)

@fabianmendes you can try to use the `switch kernel 32/64bit` option in commander pi, than install it (be sure to backup first). otherwise, you have to flash a 64bit OS like Ubuntu 20.10 ( https://ubuntu.com/download/raspberry-pi ), 64bit beta RPiOS ( https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2020-05-28/2020-05-27-raspios-buster-arm64.zip ), Ubuntu MATE ( https://ubuntu-mate.org/download/arm64/ ).

**Comment by Botspot** [comment]
Switching to the 64bit kernel won't work.

You need 64bit RPiOS to run WPS Office.

**Comment by fabianmendes** [comment]
All right, thaanks!

On Dec 28, 2020 2:08 PM, "Botspot" <notifications@github.com> wrote:

Switching to the 64bit kernel won't work.

You need 64bit RPiOS to run WPS Office.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Botspot/pi-apps/issues/105#issuecomment-751812604>, or
unsubscribe

**Comment by stguen1** [comment]
Hi everyone, I've been trying to install WPS Office for a couple of weeks now on my Raspberry PI 4 with no success. The application does not appear in the PI-apps menu although it's in the PI-apps folder. I've tried to install it directly from the folder but the installation aborted due to a missing component/application ?? Admittedly, I'm relatively new to Linux! Hoping someone can help me find what I'm doing wrong. Thanks in advance.

**Comment by Itai-Nelken** [comment]
> Hi everyone, I've been trying to install WPS Office for a couple of weeks now on my Raspberry PI 4 with no success. The application does not appear in the PI-apps menu although it's in the PI-apps folder. I've tried to install it directly from the folder but the installation aborted due to a missing component/application ?? Admittedly, I'm relatively new to Linux! Hoping someone can help me find what I'm doing wrong. Thanks in advance.

@stguen1 it doesn't appear for you because you probably are on a 32bit system and WPS Office only works on 64bit systems.

**Comment by stguen1** [comment]
Well that would explain why I could'nt install it! Thank you for your prompt response.

________________________________
De : Itai Nelken ***@***.***>
Envoyé : 20 mars 2021 13:40
À : Botspot/pi-apps ***@***.***>
Cc : stguen1 ***@***.***>; Mention ***@***.***>
Objet : Re: [Botspot/pi-apps] WPS Office (#105)


Hi everyone, I've been trying to install WPS Office for a couple of weeks now on my Raspberry PI 4 with no success. The application does not appear in the PI-apps menu although it's in the PI-apps folder. I've tried to install it directly from the folder but the installation aborted due to a missing component/application ?? Admittedly, I'm relatively new to Linux! Hoping someone can help me find what I'm doing wrong. Thanks in advance.

@stguen1<https://github.com/stguen1> it doesn't appear for you because you probably are on a 32bit system and WPS Office only works on 64bit systems.
