### ISSUE TITLE
Wolfram engine/script

### ISSUE THREAD

**Issue by TheTorbenator** [Botspot/pi-apps#1098]
[Mathematica.zip](https://github.com/Botspot/pi-apps/files/7444858/Mathematica.zip)

**Comment by Botspot** [comment]
According to the [app eligibility rubric](https://github.com/Botspot/pi-apps/issues/185), this app is not allowed because it's already available on APT.

HOWEVER, I won't close the issue for two reasons:
- Pi-Apps will soon roll out large-scale support for APT-packages. The code is already in place, but I'm waiting until we sort out some reliability stuff before dropping a bunch of updates.
- As I understand it, Mathematica is not available in conventional ARM repositories. So if this app was changed to download the deb from elsewhere, it could allow this app to work on Ubuntu and Kali, for example.

**Comment by theofficialgman** [comment]
fyi, bospot, the license agreement specifically states that only :
```
Subject to the terms of this Agreement and Your acceptance thereof, WRI grants You a non-exclusive license to use the Product solely for personal or educational purposes on a Model A or Model B Raspberry Pi computer. You are also authorized to:

maintain one archival copy of the Software on storage media; and
author and distribute Computable Document Format™ (CDF) files consistent with any associated licensing terms.
```

just make sure that whatever you do, you DONT host the mathmatica deb yourself, as that is not allowed.

you could probably link directly to the raspberry pi repo (the deb file itself) and wget from that though and install that way on non rasbian/raspberry pios distros

**Comment by theofficialgman** [comment]
https://wolfr.am/wolfram-engine-raspi-install
fyi, wolfram alpha has an installation script on their own website here ^
it downloads the deb directly from `https://files.wolframcdn.com/raspbian`
and btw, there is only an armhf deb

**Comment by Botspot** [comment]
> `https://files.wolframcdn.com/raspbian`

404.

**Comment by theofficialgman** [comment]
yes you can't directly open that url
download the script and view the full thing there

**Comment by theofficialgman** [comment]
also just to note, wolfram engine and script are NOT the same thing as mathmatica (even if mathmatica is built on them)

**Comment by theofficialgman** [comment]
closing as stale
