### ISSUE TITLE
installing Zoom - Failed to run cmake!

### ISSUE THREAD

**Issue by olaxe** [Botspot/pi-apps#113]
Hello,

I just discovered the nice project and I am impressed by the list of apps proposed especially Zoom or Visual Studio Code.
When I launched the install of Zoom. I had this message:
/home/olaxe/pi-apps/apps/Zoom/install-32: ligne 84: cmake : commande introuvable Failed to run cmake!

After investigations, it seems when the install-32 launched the pkg-install, it has been launched in dry-run as it didn't installed packages. Confirmed in the pkg-install at the line 115 with --dry-run
So I installed them manually:
sudo apt install cmake cmake-data libasound2-plugins libjsoncpp1 libpulsedsp librhash0 libuv1 libxcb-xtest0 pulseaudio pulseaudio-utils

and it works like a charm.

Another message during the install:
/home/olaxe/pi-apps/manage: ligne 47 : [: == : opérateur unaire attendu

**Comment by fabianmendes** [comment]
Does it need pulseaudio?? I've installed it but I cant open it because I
dont have installed pulseaudio

**Comment by Botspot** [comment]
I think this is an issue with your non-english locale.

`pkg-install` has to detect which packages apt installs, and the way it does that is by doing this:

- First run apt-get as a [dry-run](https://github.com/Botspot/pi-apps/blob/master/pkg-install#L75). `pkg-install` parses apt's output, and determines which packages apt wants to install. And it [writes](https://github.com/Botspot/pi-apps/blob/master/pkg-install#L91) this list to a file.
- Next, if the package list [is not empty](https://github.com/Botspot/pi-apps/blob/master/pkg-install#L88), `pkg-install` actually [installs](https://github.com/Botspot/pi-apps/blob/master/pkg-install#L96) the packages.

Now, if you're using a non-english locale, `pkg-install` may fail to parse `apt`'s output correctly.

I'm not sure what to do about it unfortunately.

**Comment by Botspot** [comment]
@olaxe Let's try something on your install with your locale.

First, let's uninstall the packages you installed:
```
sudo apt purge cmake cmake-data libasound2-plugins libjsoncpp1 libpulsedsp librhash0 libuv1 libxcb-xtest0 pulseaudio pulseaudio-utils
```
Now, I want you to post the output from this below command:
```
sudo LANG=C LC_ALL=C apt install -y cmake cmake-data libasound2-plugins libjsoncpp1 libpulsedsp librhash0 libuv1 libxcb-xtest0 pulseaudio pulseaudio-utils
```

**Comment by olaxe** [comment]
It works, it's in English:
sudo LANG=C LC_ALL=C apt install -y cmake cmake-data libasound2-plugins libjsoncpp1 libpulsedsp librhash0 libuv1 libxcb-xtest0 pulseaudio pulseaudio-utils
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  rtkit
Suggested packages:
  cmake-doc ninja-build pavumeter pavucontrol paman paprefs
The following NEW packages will be installed:
  cmake cmake-data libasound2-plugins libjsoncpp1 libpulsedsp librhash0 libuv1 libxcb-xtest0 pulseaudio pulseaudio-utils rtkit
0 upgraded, 11 newly installed, 0 to remove and 0 not upgraded.
Need to get 5682 kB of archives.
After this operation, 28.5 MB of additional disk space will be used.
Get:1 http://ftp.igh.cnrs.fr/pub/os/linux/raspbian/raspbian buster/main armhf cmake-data all 3.13.4-1 [1476 kB]
Get:2 http://ftp.igh.cnrs.fr/pub/os/linux/raspbian/raspbian buster/main armhf libjsoncpp1 armhf 1.7.4-3 [66.2 kB]
Get:3 http://ftp.igh.cnrs.fr/pub/os/linux/raspbian/raspbian buster/main armhf librhash0 armhf 1.3.8-1 [132 kB]
Get:4 http://ftp.igh.cnrs.fr/pub/os/linux/raspbian/raspbian buster/main armhf libuv1 armhf 1.24.1-1 [96.7 kB]
Get:5 http://ftp.igh.cnrs.fr/pub/os/linux/raspbian/raspbian buster/main armhf cmake armhf 3.13.4-1 [2559 kB]
Get:6 http://ftp.igh.cnrs.fr/pub/os/linux/raspbian/raspbian buster/main armhf libasound2-plugins armhf 1.1.8-1 [64.2 kB]
Get:7 http://ftp.igh.cnrs.fr/pub/os/linux/raspbian/raspbian buster/main armhf libpulsedsp armhf 12.2-4+deb10u1 [45.0 kB]
Get:8 http://ftp.igh.cnrs.fr/pub/os/linux/raspbian/raspbian buster/main armhf libxcb-xtest0 armhf 1.13.1-2 [98.4 kB]
Get:9 http://ftp.igh.cnrs.fr/pub/os/linux/raspbian/raspbian buster/main armhf pulseaudio-utils armhf 12.2-4+deb10u1 [75.4 kB]
Get:10 http://ftp.igh.cnrs.fr/pub/os/linux/raspbian/raspbian buster/main armhf pulseaudio armhf 12.2-4+deb10u1 [1036 kB]
Get:11 http://ftp.igh.cnrs.fr/pub/os/linux/raspbian/raspbian buster/main armhf rtkit armhf 0.11-6 [32.6 kB]
Fetched 5682 kB in 3s (1935 kB/s) 
Selecting previously unselected package cmake-data.
(Reading database ... 127010 files and directories currently installed.)
Preparing to unpack .../00-cmake-data_3.13.4-1_all.deb ...
Unpacking cmake-data (3.13.4-1) ...
Selecting previously unselected package libjsoncpp1:armhf.
Preparing to unpack .../01-libjsoncpp1_1.7.4-3_armhf.deb ...
Unpacking libjsoncpp1:armhf (1.7.4-3) ...
Selecting previously unselected package librhash0:armhf.
Preparing to unpack .../02-librhash0_1.3.8-1_armhf.deb ...
Unpacking librhash0:armhf (1.3.8-1) ...
Selecting previously unselected package libuv1:armhf.
Preparing to unpack .../03-libuv1_1.24.1-1_armhf.deb ...
Unpacking libuv1:armhf (1.24.1-1) ...
Selecting previously unselected package cmake.
Preparing to unpack .../04-cmake_3.13.4-1_armhf.deb ...
Unpacking cmake (3.13.4-1) ...
Selecting previously unselected package libasound2-plugins:armhf.
Preparing to unpack .../05-libasound2-plugins_1.1.8-1_armhf.deb ...
Unpacking libasound2-plugins:armhf (1.1.8-1) ...
Selecting previously unselected package libpulsedsp:armhf.
Preparing to unpack .../06-libpulsedsp_12.2-4+deb10u1_armhf.deb ...
Unpacking libpulsedsp:armhf (12.2-4+deb10u1) ...
Selecting previously unselected package libxcb-xtest0:armhf.
Preparing to unpack .../07-libxcb-xtest0_1.13.1-2_armhf.deb ...
Unpacking libxcb-xtest0:armhf (1.13.1-2) ...
Selecting previously unselected package pulseaudio-utils.
Preparing to unpack .../08-pulseaudio-utils_12.2-4+deb10u1_armhf.deb ...
Unpacking pulseaudio-utils (12.2-4+deb10u1) ...
Selecting previously unselected package pulseaudio.
Preparing to unpack .../09-pulseaudio_12.2-4+deb10u1_armhf.deb ...
Unpacking pulseaudio (12.2-4+deb10u1) ...
Selecting previously unselected package rtkit.
Preparing to unpack .../10-rtkit_0.11-6_armhf.deb ...
Unpacking rtkit (0.11-6) ...
Setting up rtkit (0.11-6) ...
Setting up libasound2-plugins:armhf (1.1.8-1) ...
Setting up libpulsedsp:armhf (12.2-4+deb10u1) ...
Setting up libuv1:armhf (1.24.1-1) ...
Setting up pulseaudio-utils (12.2-4+deb10u1) ...
Setting up libxcb-xtest0:armhf (1.13.1-2) ...
Setting up librhash0:armhf (1.3.8-1) ...
Setting up cmake-data (3.13.4-1) ...
Setting up libjsoncpp1:armhf (1.7.4-3) ...
Setting up pulseaudio (12.2-4+deb10u1) ...
Adding user pulse to group audio
Setting up cmake (3.13.4-1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for dbus (1.12.20-0+deb10u1) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...

**Comment by fabianmendes** [comment]
Excuse me do you know the code that pulseaudio find my Bluetooth headphoned
device?

On Nov 30, 2020 2:21 AM, "Axel" <notifications@github.com> wrote:

It works, it's in English:
sudo LANG=C LC_ALL=C apt install -y cmake cmake-data libasound2-plugins
libjsoncpp1 libpulsedsp librhash0 libuv1 libxcb-xtest0 pulseaudio
pulseaudio-utils
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
rtkit
Suggested packages:
cmake-doc ninja-build pavumeter pavucontrol paman paprefs
The following NEW packages will be installed:
cmake cmake-data libasound2-plugins libjsoncpp1 libpulsedsp librhash0
libuv1 libxcb-xtest0 pulseaudio pulseaudio-utils rtkit
0 upgraded, 11 newly installed, 0 to remove and 0 not upgraded.
Need to get 5682 kB of archives.
After this operation, 28.5 MB of additional disk space will be used.
Get:1 http://ftp.igh.cnrs.fr/pub/os/linux/raspbian/raspbian buster/main
armhf cmake-data all 3.13.4-1 [1476 kB]
Get:2 http://ftp.igh.cnrs.fr/pub/os/linux/raspbian/raspbian buster/main
armhf libjsoncpp1 armhf 1.7.4-3 [66.2 kB]
Get:3 http://ftp.igh.cnrs.fr/pub/os/linux/raspbian/raspbian buster/main
armhf librhash0 armhf 1.3.8-1 [132 kB]
Get:4 http://ftp.igh.cnrs.fr/pub/os/linux/raspbian/raspbian buster/main
armhf libuv1 armhf 1.24.1-1 [96.7 kB]
Get:5 http://ftp.igh.cnrs.fr/pub/os/linux/raspbian/raspbian buster/main
armhf cmake armhf 3.13.4-1 [2559 kB]
Get:6 http://ftp.igh.cnrs.fr/pub/os/linux/raspbian/raspbian buster/main
armhf libasound2-plugins armhf 1.1.8-1 [64.2 kB]
Get:7 http://ftp.igh.cnrs.fr/pub/os/linux/raspbian/raspbian buster/main
armhf libpulsedsp armhf 12.2-4+deb10u1 [45.0 kB]
Get:8 http://ftp.igh.cnrs.fr/pub/os/linux/raspbian/raspbian buster/main
armhf libxcb-xtest0 armhf 1.13.1-2 [98.4 kB]
Get:9 http://ftp.igh.cnrs.fr/pub/os/linux/raspbian/raspbian buster/main
armhf pulseaudio-utils armhf 12.2-4+deb10u1 [75.4 kB]
Get:10 http://ftp.igh.cnrs.fr/pub/os/linux/raspbian/raspbian buster/main
armhf pulseaudio armhf 12.2-4+deb10u1 [1036 kB]
Get:11 http://ftp.igh.cnrs.fr/pub/os/linux/raspbian/raspbian buster/main
armhf rtkit armhf 0.11-6 [32.6 kB]
Fetched 5682 kB in 3s (1935 kB/s)
Selecting previously unselected package cmake-data.
(Reading database ... 127010 files and directories currently installed.)
Preparing to unpack .../00-cmake-data_3.13.4-1_all.deb ...
Unpacking cmake-data (3.13.4-1) ...
Selecting previously unselected package libjsoncpp1:armhf.
Preparing to unpack .../01-libjsoncpp1_1.7.4-3_armhf.deb ...
Unpacking libjsoncpp1:armhf (1.7.4-3) ...
Selecting previously unselected package librhash0:armhf.
Preparing to unpack .../02-librhash0_1.3.8-1_armhf.deb ...
Unpacking librhash0:armhf (1.3.8-1) ...
Selecting previously unselected package libuv1:armhf.
Preparing to unpack .../03-libuv1_1.24.1-1_armhf.deb ...
Unpacking libuv1:armhf (1.24.1-1) ...
Selecting previously unselected package cmake.
Preparing to unpack .../04-cmake_3.13.4-1_armhf.deb ...
Unpacking cmake (3.13.4-1) ...
Selecting previously unselected package libasound2-plugins:armhf.
Preparing to unpack .../05-libasound2-plugins_1.1.8-1_armhf.deb ...
Unpacking libasound2-plugins:armhf (1.1.8-1) ...
Selecting previously unselected package libpulsedsp:armhf.
Preparing to unpack .../06-libpulsedsp_12.2-4+deb10u1_armhf.deb ...
Unpacking libpulsedsp:armhf (12.2-4+deb10u1) ...
Selecting previously unselected package libxcb-xtest0:armhf.
Preparing to unpack .../07-libxcb-xtest0_1.13.1-2_armhf.deb ...
Unpacking libxcb-xtest0:armhf (1.13.1-2) ...
Selecting previously unselected package pulseaudio-utils.
Preparing to unpack .../08-pulseaudio-utils_12.2-4+deb10u1_armhf.deb ...
Unpacking pulseaudio-utils (12.2-4+deb10u1) ...
Selecting previously unselected package pulseaudio.
Preparing to unpack .../09-pulseaudio_12.2-4+deb10u1_armhf.deb ...
Unpacking pulseaudio (12.2-4+deb10u1) ...
Selecting previously unselected package rtkit.
Preparing to unpack .../10-rtkit_0.11-6_armhf.deb ...
Unpacking rtkit (0.11-6) ...
Setting up rtkit (0.11-6) ...
Setting up libasound2-plugins:armhf (1.1.8-1) ...
Setting up libpulsedsp:armhf (12.2-4+deb10u1) ...
Setting up libuv1:armhf (1.24.1-1) ...
Setting up pulseaudio-utils (12.2-4+deb10u1) ...
Setting up libxcb-xtest0:armhf (1.13.1-2) ...
Setting up librhash0:armhf (1.3.8-1) ...
Setting up cmake-data (3.13.4-1) ...
Setting up libjsoncpp1:armhf (1.7.4-3) ...
Setting up pulseaudio (12.2-4+deb10u1) ...
Adding user pulse to group audio
Setting up cmake (3.13.4-1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for dbus (1.12.20-0+deb10u1) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Botspot/pi-apps/issues/113#issuecomment-735575758>, or
unsubscribe

**Comment by Botspot** [comment]
Perfect. I've updated `pkg-install` and now it too should work.

I will now close this issue. However, @olaxe, if you continue having problems like this, let me know in a new issue!
