### ISSUE TITLE
Tetris CLI

### ISSUE THREAD

**Issue by ryanfortner** [Botspot/pi-apps#1131]
<img src=https://github.com/k-vernooy/tetris/raw/master/docs/out.gif width=500px>

Can this app run on RPi? If so, please provide a link to a tutorial if applicable.

https://github.com/ryanfortner/pi-bashscripts-files/blob/main/Tetris_CLI.md

Is this app something many GUI users would find useful?

Yes, maybe we could have a desktop entry that launches the program in a terminal window.

Is this app installable with `sudo apt install`?

No

If you've created a zip file for this app, upload it here.

Not near my Pi right now, I will make scripts as soon as I can.

**Comment by Itai-Nelken** [comment]
Just a note: I think the terminal window has to have a specific size for this to work.

**Comment by craigevil** [comment]
sudo apt install tint

Description: Tetris clone for text based terminal

**Comment by cycool29** [comment]
@ryanfortner Should we make a deb for this? It should be simple since it only contains a binary file.

**Comment by ryanfortner** [comment]
> @ryanfortner Should we make a deb for this? It should be simple since it only contains a binary file.

Yeah that might be a good idea. I wrote [a deb creator script](https://github.com/ryanfortner/deb-builder) a few hours ago, maybe I can use that.

**Comment by cycool29** [comment]
I made a initial deb for armhf: https://transfer.sh/3zNr6l/tetris_2.0_armhf.deb. I used tint icon, as Tetris don't have one.

**Comment by ryanfortner** [comment]
> I made a initial deb for armhf: https://transfer.sh/3zNr6l/tetris_2.0_armhf.deb. I used tint icon, as Tetris don't have one.

I tested it, works well.

**Comment by leha-code** [comment]
There's already a better tetris for command line and it comes as an apt package: tint. Was in all os sea apt repos I ever had

**Comment by ryanfortner** [comment]
@cycool29 your deb's desktop entry had the wrong path for the binary. Here's the new deb link: https://transfer.sh/dq7m7p/tetris-cli_2.0-1_armhf.deb

**Comment by cycool29** [comment]
> There's already a better tetris for command line and it comes as an apt package: tint. Was in all os sea apt repos I ever had

That doesn't matter, remember pi-apps is an app store - users can choose whether they want `tint` or `tetris`, we just provide them the way to install.
That's why we have many same purpose apps in pi-apps, like Remarkable and Stackedit, Zoom and Zoom PWA, etc. :)



> @cycool29 your deb's desktop entry had the wrong path for the binary. Here's the new deb link: https://transfer.sh/dq7m7p/tetris-cli_2.0-1_armhf.deb

Thanks, I removed the unneeded `.git` and `.gitignore`, and here are the final debs:

armhf: https://transfer.sh/YDqUMW/tetris-cli_2.0_armhf.deb
arm64: https://transfer.sh/xBXxnS/tetris-cli_2.0_arm64.deb

@ryanfortner I think you can add these debs to your raspbian-addons repo instead of https://github.com/Pi-Apps-Coders/files since it can be installed without pi-apps.

**Comment by ryanfortner** [comment]
the debs in my repository are in this folder: https://apt.raspbian-addons.org/debian/pool/main/t/tetris-cli/
