### ISSUE TITLE
SavUTube

### ISSUE THREAD

**Issue by Botspot** [Botspot/pi-apps#116]
https://github.com/BC2A/SavUTube

**Comment by Itai-Nelken** [comment]
@Botspot I created the scripts:
[SavUTube.zip](https://github.com/Botspot/pi-apps/files/5681308/SavUTube.zip)

**Comment by Botspot** [comment]
> I created the scripts:
> [SavUTube.zip](https://github.com/Botspot/pi-apps/files/5681308/SavUTube.zip)

Oh, sorry, I should have updated this issue with the concerns I've had about SavUTube.

Mainly, I don't see the point. Who would use it? AFAIK, SavUTube **does not help you find videos**, but only allows you to paste in a youtube url to download.

So, for most people, they'd have to locate an interesting YT video from Chromium, copy the URL, and then paste it into SavUTube.

There's three problems with that:

- First, why not watch the video straight in the browser?
- Second, if you already have the URL, why not use a terminal to download it using pure `youtube-dl`?
- Third, TBOPlayer already does this, and more: It includes a functional youtube search engine. You can then select a video from the search results and add it to the video list. TBOPlayer then downloads the videos with `youtube-dl`, and plays them with `omxplayer`.

So, IMO, TBOPlayer does a far better job than SavUTube does, and for that reason I'm not sure SavUTube would be beneficial for most users.

**Comment by Itai-Nelken** [comment]
I know TBOPlayer does all of this, but personally I use it (SavUTube) when I want to watch videos in full HD fullscreen because youtube 1080p streaming in chromium still is pretty bad when in fullscreen (and it's worse in any other browser). 
also in my opinion while TBOPlayer is great, I don't like the way the video and the controls are in 2 separate windows, you can always use VLC, but than you have to find the video in a browser, so it's the same thing as SavUTube (and most people that will use a video downloader like SavUTube would rather paste a url in a nice text box than find how to convert the video with vlc). 
using `youtube-dl` is pretty easy, but I have had ~80% success with it compared to ~99% with SavUTube (I know it uses `youtube-dl`, but I think it uses some different command or something, because it downloads videos that failed to download when using `youtube-dl`).
I think that most people that will use SavUTube are people that prefer not to use the terminal more than when absolutely necessary or just want a GUI. 

>I'm not sure SavUTube would be beneficial for most users.

I think you are right, but in my opinion someone that is a complete starter to linux and the pi, would like to have a GUI video downloader in pi-apps (I know how frustrating it can be when you are looking for a GUI app to do something and all you find is a terminal app, because I felt like that when I was looking for a video downloader a year ago and I still didn't use the terminal for more than updating).

**Comment by Botspot** [comment]
You're right:

- TBOPlayer is not perfect. (as the interface is wonky)
- VLC is not perfect. (as it doesn't save the video to file AFAIK, and is slightly buggy)
- youtube-dl is not perfect (as it's terminal-based)

So for my own personal needs, I'm not satisfied with any of the options.

Perhaps if SavUTube had a YT search feature. That would be awesome.

**Comment by Itai-Nelken** [comment]
>Perhaps if SavUTube had a YT search feature. That would be awesome.

yes it would be great.

**Comment by Itai-Nelken** [comment]
>VLC is not perfect. (as it doesn't save the video to file AFAIK, and is slightly buggy)

it can save to a file, but it's a bit compilcated, and doesn't always work.

>Perhaps if SavUTube had a YT search feature. That would be awesome.

that would be great.

**Comment by Botspot** [comment]
> > Perhaps if SavUTube had a YT search feature. That would be awesome.
> 
> that would be great.

I'll see what I can do. ;)

**Comment by Itai-Nelken** [comment]
that would be great! I would do it if i had enough time to learn how.

**Comment by Botspot** [comment]
Okay I've made significant progress from some Google searches.  
This will parse the output from `youtube-dl` and return back a bunch of info about each video.
```
youtube-dl -s --print-json "ytsearch1:hacksmith" | tr ',]}{[' '\n' | grep -E '"url":|height|upload_date|webpage_url|fulltitle'
```

**Comment by Itai-Nelken** [comment]
great!
https://discord.com/channels/770629697909424159/780995853023313981/787397984831799347
don't forget to add a download feature thats easily accessible.

**Comment by Botspot** [comment]
Closing this issue, as I plan to add YouTubuddy to Pi-Apps instead of SavUTube.
