### ISSUE TITLE
マイクラ

### ISSUE THREAD

**Issue by tokuidaiki** [Botspot/pi-apps#1304]
### What is the name of the app?

PiApps

### About the app

マイクラを入れたい

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
@tokuidaiki please use english next time
using a translator is looks like you are requesting minecraft (in japanese)?

multiple versions of minecraft are already available in pi-apps:
bedrock: https://github.com/Botspot/pi-apps/wiki/Apps-List#-minecraft-bedrock
lunar client java edition: https://github.com/Botspot/pi-apps/wiki/Apps-List#-minecraft-java
MultiMC5 java edition: https://github.com/Botspot/pi-apps/wiki/Apps-List#-minecraft-java-multimc5
Minecraft Pi Modded: https://github.com/Botspot/pi-apps/wiki/Apps-List#-minecraft-pi-modded

is there something else you wanted? otherwise this can be closed as this confirmation is false

>  I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
