### ISSUE TITLE
OBS Studio does not run

### ISSUE THREAD

**Issue by amarmashruwala** [Botspot/pi-apps#1318]
Hi Team,

I have installed OBS studio on a Pi 4 4GB RAM but when i run it nothing happens. the program does not run.

Is there anything else i need to do. 

thanks 

here is the rror i get when trying to run from CLI

pi@raspberrypi:~ $ obs
/usr/bin/obs-exec: error while loading shared libraries: libxcb-util.so.0: cannot open shared object file: No such file or directory

**Comment by amarmashruwala** [comment]
here is the rror i get when trying to run from CLI

pi@raspberrypi:~ $ obs
/usr/bin/obs-exec: error while loading shared libraries: libxcb-util.so.0: cannot open shared object file: No such file or directory

**Comment by theofficialgman** [comment]
I've seen this reported in the pi-apps discord as well
libxcb seems to have had a major enough version change to warrant a binary file name change from `libxcb-util.so.0` on buster to `libxcb-util.so.1` on bullseye

the pi-apps installer will need updating and there will probably need to be debs made specifically on buster and specifically on bullseye

**Comment by epicmario7133** [comment]
same problem here

**Comment by epicmario7133** [comment]
Still not working after update, this happens when you try to register:
Full error:
warning: Stream output type 'rtmp_output' failed to start!
QObject::connect: No such signal QLineEdit::editingFinished(const QString &)
QObject::connect: (sender name: 'customServer')
QObject::connect: (receiver name: 'OBSBasicSettings')
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/
Attempted path: /usr/share/obs/obs-studio/themes/
error: Encoder ID 'obs_x264' not found
info: Settings changed (outputs)

**Comment by byronbonkers** [comment]
It still doesn't work

**Comment by derryktutt** [comment]
@cycool29 still does not work
