### ISSUE TITLE
Minecraft Java App Suggestions

### ISSUE THREAD

**Issue by zachdwilliams** [Botspot/pi-apps#140]
Hey, if you don’t mind I would suggest some small changes to the Minecraft Java App:

- Change the icon to the one on the Minecraft Launcher (attached and you can resize it if needed)
- Rename the app to “Minecraft Launcher”
- Update the game to the latest version and snapshot (or does it automatically do that when Mojang releases a new update?)

That’s about it, but I have one question. Does playing on diverse versions of Minecraft take up space? I mean, does it take up space downloading a certain version/snapshot of Minecraft?

![BE3B6041-60C0-41FB-AA31-91D4B90EC662](https://user-images.githubusercontent.com/60779039/102589314-253cf980-410f-11eb-98e9-531a3eb4df57.png)

**Comment by mobilegmYT** [comment]
"Change the icon to the one on the Minecraft Launcher (attached and you can resize it if needed)"
Well, not everyone is the same, but the current logo does look way cooler and prettier than the normal one.

Rename the app to “Minecraft Launcher”
It's named Minecraft Java right now to separate it from the other edition of Bedrock. Changing it to Minecraft Bedrock could cause confusion with the bedrock version.

Update the game to the latest version and snapshot (or does it automatically do that when Mojang releases a new update?)
When you launch the game, it'll auto download the latest version of Minecraft. If you want a snapshot version, just hit the edit profile button and enable Snapshot versions.

That’s about it, but I have one question. Does playing on diverse versions of Minecraft take up space? I mean, does it take up space downloading a certain version/snapshot of Minecraft?
All Minecraft versions take up space(about 100-300mb), but a newer version will take up more space because of more features.

**Comment by zachdwilliams** [comment]
Ok

**Comment by Botspot** [comment]
Should this "issue" be closed?

**Comment by zachdwilliams** [comment]
Sure
