### ISSUE TITLE
Removal from trash bin

### ISSUE THREAD

**Issue by rbcoder117** [Botspot/pi-apps#1403]
### Cool ideas?

You should make it so that it permanently deletes a app from the trash so it doesn't still take up a lot of space.

**Comment by Rak1ta** [comment]
The argument against this is that if something doesn't work for me with the upgrade, I can restore the old setup script. You can always empty the basket yourself.

**Comment by Botspot** [comment]
> ### Cool ideas?
> You should make it so that it permanently deletes a app from the trash so it doesn't still take up a lot of space.

For future readers: Pi-Apps does move old app-folders to the Trash folder during an update. This design prevents accidental data loss in situations where someone modified the app's installation script before the update. By moving the app-folder to the trash, you have a chance to recover it. But if old app-folders were deleted, there would be no way to get it back.

For example, I have made a few changes to the Wine app which I'm holding back for the time being. Because Wine's installation script doesn't match the online one, Pi-Apps will ask me to update Wine. If I click yes, my improved scripts will be removed. Fortunately, I can recover them easily as they are in the trash. But if Pi-Apps used `rm`? My changes would be gone forever.

I know this compromise is useless for most people, as they don't modify scripts that often. But I don't think it's a big deal because each app-folder is only a couple kilobytes. (basically nothing)
If someone is bothered enough by it, they can open a PR to address the compromise more elegantly. (maybe with a setting or something)

**Comment by rbcoder117** [comment]
ok
