### ISSUE TITLE
Pi-Apps logo is displayed incorrectly

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#1441]
While there was a need to reinstall Raspbian, I noticed a flaw. The logo in the terminal is displayed correctly in Debian 11, but distorted in Debian 10 Buster (see screenshot):
![Безымянный](https://user-images.githubusercontent.com/88277343/151163505-3d902cbe-5a8f-41dd-95c8-5efd4d0adbc4.png)

Until I noticed how it should look and did not pay attention to it.

**Comment by Itai-Nelken** [comment]
Probably a locale/language problem.
@Botspot setting `LC_ALL` to C in generate_logo() might help?

**Comment by cycool29** [comment]
That is because you didn't install `Color Emoji font`.

@Botspot Maybe we can make it as a dependency of pi-apps?

**Comment by Botspot** [comment]
This looks like a Unicode/missing font problem.

We have four options:

1. Do nothing
1. Downgrade to a logo that only uses common ASCII characters, even though it would not look very good
1. Force-install a font package in a new `runonce` entry
2. Somehow detect which fonts are installed and fallback to the old logo if necessary.

I think option 3 has the least number of disadvantages. Can someone on a Buster system try installing one `fonts-*` apt package at a time to which ones, if any, will work?
Each test should go like this: Close all terminals, then launch a terminal. Closing them all is necessary; otherwise it will use the existing terminal's session and won't refresh fonts. (I learned this the hard way) Now that you have one fresh terminal opened, run `~/pi-apps/api generate_logo`. Rinse and repeat.

**Comment by Rak1ta** [comment]
`try installing one fonts-* apt package`  - i
![Безымянный](https://user-images.githubusercontent.com/88277343/151429393-7a30aa1b-4887-4d48-bc4d-95b6b45d6a2b.png)
 correctly understood that in turn it is from this large list until the logo changes?

**Comment by Rak1ta** [comment]
@Botspot 
`try installing one fonts-* apt package`  - i correctly understood that in turn it is from this large list until the logo changes? 
![Безымянный](https://user-images.githubusercontent.com/88277343/151429496-bb8ea03d-c899-408d-9118-e02a670382d3.png)

**Comment by Botspot** [comment]
> @Botspot `try installing one fonts-* apt package` - i correctly understood that in turn it is from this large list until the logo changes?

Yes, but I think you will accomplish it faster by using the terminal.
This command will print a list of the `fonts-` packages available for your system, that are **not** currently installed.
`apt search fonts --names-only | grep -v installed | grep '^fonts-' | awk -F/ '{print $1}'`

Now, compare that output with a list of all fonts I have currently installed on my Bullseye system.
```
fonts-cantarell
fonts-crosextra-caladea
fonts-crosextra-carlito
fonts-dejavu-core
fonts-dejavu-extra
fonts-dejavu
fonts-droid-fallback
fonts-fantasque-sans
fonts-freefont-ttf
fonts-liberation2
fonts-liberation
fonts-linuxlibertine
fonts-noto-core
fonts-noto-extra
fonts-noto-mono
fonts-noto-ui-core
fonts-opensymbol
fonts-piboto
fonts-powerline
fonts-quicksand
fonts-sil-gentium-basic
fonts-sil-gentium
fonts-urw-base35
fonts-wine
```
There ought to be a few fonts that are installed on my system, but are not installed on yours. And hopefully one of them contains the characters we need.
You can install a package with: `sudo apt install -y fonts-piboto`

**Comment by Rak1ta** [comment]
@Botspot from your list installed everything that was missing. Further all possible fonts. Nothing has changed. Maybe I didn't do it right.

**Comment by Botspot** [comment]
> @Botspot from your list installed everything that was missing. Further all possible fonts. Nothing has changed. Maybe I didn't do it right.

All possible fonts?! Surely, one of them would have the necessary characters. Try rebooting. And, this shouldn't matter, but what terminal are you using? The default `lxterminal`?

**Comment by Rak1ta** [comment]
@Botspot lxterminal - yes. Put Bullseye - deleted everything, the picture is there. Does it depend on the font?
![Безымянный](https://user-images.githubusercontent.com/88277343/151502604-864e8db0-f296-498d-8a0b-bd133a4805e2.png)

**Comment by Botspot** [comment]
OK I'm going to try to solve this with vdesktop and a buster image I still had lying around.

**Comment by Botspot** [comment]
It appears that the symbols that aren't displaying correctly are from the list of [Symbols for Legacy Computing](https://en.wikipedia.org/wiki/Symbols_for_Legacy_Computing).

**Comment by Botspot** [comment]
To add onto my previous statement, it appears that these characters have been added back to Unicode rather recently! (Unicode 13.0)
So that would make sense, where an older distro's font-files don't have those characters because Buster was released two years ago.

To see if I was right, I copied everything from my Bullseye system's `usr/share/fonts` to the Buster VM. After restarting lxterminal, the Pi-Apps logo looked like this:
![2022-01-28-113502_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/151594707-dc1949a4-1b99-4b8e-b2e0-b8074a0c7e02.png)
Better, but it looks so... wrong. 🤣 

As it appears that changes were made to Bullseye more than just the fonts, I think I will tweak the logo to get rid of all diagonal, triangular characters, and use it as a fallback if the debian version is less than 11.

**Comment by Botspot** [comment]
This issue should now be solved.
On systems that are older than Bullseye, the logo will look like this:
![2022-01-28-141449_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/151615254-d71a244e-7ed6-4111-a473-7f16165b8e4b.png)
