### ISSUE TITLE
Old School RuneScape (RuneLite)

### ISSUE THREAD

**Issue by DatBoiG265** [Botspot/pi-apps#1519]
### What is the name of the app?

RuneScape

### (Optional) Where is the app hosted?

https://github.com/DatBoiG265/RuneScape-on-Linux

### About the app

A Script that installs Old School RuneScape on your raspberry pi

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by DatBoiG265** [comment]
@Botspot i have fully tested this install and uninstall script i have made and posted it on my github repositories list
I would love if you put my app on to pi-apps

i tested Old School RuneScape on my RaspberryPi4 model b(4gb)

**Comment by Botspot** [comment]
That name sounds familiar... We used to have a couple of app-requests for Old School RuneScape open, but each was closed due to inactivity or user-error.

Assuming this game abides by [the rules](https://github.com/Botspot/pi-apps/issues/185), then it ought to be fine to add.
@DatBoiG265, I took a brief look at your repository, and your scripts have a couple of issues. First, you don't make any provisions to install Java. Also, Your scripts make reference to `/home/pi`, which causes problems for anyone using anything other than `/home/pi`. (You should replace `/home/pi` with the `$HOME` variable.)

Also, Pi-Apps has a built-in App Creation wizard. You should check it out. ;)

**Comment by theofficialgman** [comment]
@DatBoiG265 this will be closed as well soon due to inactivity (unless another user wants to pickup on the scripts)
