### ISSUE TITLE
Steam install fails if Steamlink is installed

### ISSUE THREAD

**Issue by rrolo1** [Botspot/pi-apps#152]
Raspberry PI OS 32-bit, up to date

Steam install fails with ( forgive the Portuguese ) :

> A descompactar steam-launcher (1:1.0.0.67) ...

> dpkg: erro ao processar o arquivo /home/pi/steam.deb (--install):
 > a tentar sobre-escrever '/lib/udev/rules.d/60-steam-input.rules', que também está no pacote steamlink 1.0.7 

aka, from what I understand,  the install script is trying to overwrite a file that was installed by steamlink without proper admin rights ( and before you ask why I want steamlink and steam in the same install, Steam in small mode doesn't allow to use remote play ). Given that this didn't happened in the previous versions of Pi-Apps, I assume there was a change in the script since last update ( given that the update uninstalled Steam to reinstall it, I assume that is the case )

**Comment by Botspot** [comment]
Here's Google's translation:
```
Unzipping steam-launcher (1: 1.0.0.67) ...
dpkg: error processing /home/pi/steam.deb (--install):
trying to overwrite '/lib/udev/rules.d/60-steam-input.rules', which is also in the steamlink 1.0.7 package
```
I am not sure what to recommend. If you feel like taking a risk, you can try deleting the file in question wi9th this command:
```
sudo rm /lib/udev/rules.d/60-steam-input.rules
```
After that runs, you can try installing Steam via Pi-Apps again.

> Given that this didn't happened in the previous versions of Pi-Apps, I assume there was a change in the script since last update ( given that the update uninstalled Steam to reinstall it, I assume that is the case

That's probably due to fixing a couple of other problems in the script. Originally it [forcibly extracted](https://github.com/Botspot/pi-apps/blob/7c54fb875dacf9bc720db120e2584305bd420b9b/apps/Steam/install-32#L22) `steam.deb`'s files directly to `/`. This proved to [corrupt SD cards](https://github.com/Botspot/pi-apps/issues/128) for no apparent reason, even though that exact command was recommended [on the Tom's Hardware](https://www.tomshardware.com/how-to/raspberry-pi-install-steam) tutorial.
So now, `steam.deb` is [installed properly](https://github.com/Botspot/pi-apps/blob/6996ed87616895da42e5ca9fe62d96cb6000c66a/apps/Steam/install-32#L25) by using an APT package manager.

**Comment by rrolo1** [comment]
Ok , this is weird ...

I was going to do the sudo rm command just for the hecks sake ( it is not that I can't fix it if it breaks ) but decided to do a ls to the folder in question , just to see the permissions on the file and such ... and '/lib/udev/rules.d/60-steam-input.rules' does not exist . So, I'm quite lost on how can I have a error overwriting a file that does not exist ... Will do some more digging.

P.S In fact there is a file in my install with that name but on ./home/pi/.local/share/SteamLink/.old/udev/rules.d/60-steam-input.rules. Not sure of how this affects anything ...

**Comment by Botspot** [comment]
What would you recommend I do?

If using `--force-overwrite` works, which it probably will, I am tempted to add it. On the other hand, it could overwrite something you'd want.

If you were in my position, would you correct an edge-case like this?

**Comment by rrolo1** [comment]
TBH I would consider it a edge case if I were you, especially if in the future people find a way of getting remote play working via the box86 Steam install ( that would negate the need of using Steamlink ). At best, I would just leave a note in case someone in the future ends up with the same issue somewhere. I would definitely not encourage using such a blunt tool as force-overwrite in an automated script ... so much can go wrong.

Anyway, I just purged Steamlink and reinstalled both Steam and Steamlink. Seems to be working.

**Comment by Botspot** [comment]
Okay thank you for your input. Good to know you've gotten it working.
