### ISSUE TITLE
(APP REQUEST) Thunder

### ISSUE THREAD

**Issue by hadcl4** [Botspot/pi-apps#1614]
### What is the name of the app?

Thunder

### (Optional) Where is the app hosted?

https://github.com/hadcl4/Thunder

### About the app

Thunder is a gaming service designed specifically for devices such as the Raspberry Pi. Easily play games from Steam, GOG, Itch, and other storefronts as well as retro games using emulators, all in one easy to use GUI. To launch run "thunder-cli --gui" in a terminal or select the icon from the app menu.

Here are some of Thunder's features:
- A game launcher
- An easy-to-use game installer (with a growing collection of games)
- A collection of setup scripts
- Several emulators pre-installed
- Easy-to-use installers for Steam, Box86, Box64, and Mednafen.
- A web browser
- And more... (Really!)

### Upload file or Add PR Link

[Thunder.zip](https://github.com/Botspot/pi-apps/files/8310200/Thunder.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by hadcl4** [comment]
Anyone?

**Comment by ryanfortner** [comment]
I don't think you need to run chmod with sudo in your install script, but other than that it looks good to me!

**Comment by hadcl4** [comment]
Okay, here's a new zip with only using sudo when it's needed:
[Thunder.zip](https://github.com/Botspot/pi-apps/files/8312050/Thunder.zip)

**Comment by jonahXD** [comment]
looks good 
@Botspot  add it pls :))

**Comment by theofficialgman** [comment]
@hadcl4 neat idea, but this can't be included without major changes at Thunder.
for one, your setup script at that repo is extremely messy and your indentation is all over the place to say the least....

thunder does not "clean uninstall" or install, this is a requirement for pi-apps inclusion
see here:

https://github.com/hadcl4/Thunder/blob/e923e8d31b48ab9b356f7f40fc971cd833274773/setup#L324-L341
stuff like this is not allowed.

your prebuild binaries from your emulators folder will also not work on many systems so this is another thing against Thunder inclusion.
Pi-Apps already includes a structure for adding apps, consider adding proper install/uninstall scripts for these emulators to pi-apps itself. I personally didn't see much value in adding a bunch of standalone emulators to pi-apps because there is already a good and popular project for that, https://retropie.org.uk/docs/

**Comment by hadcl4** [comment]
The pi-apps install script doesn't run setup though. All apps have dependencies, so I don't see what's wrong here with setup.

Thunder <b>isn't</b> the same thing as Retropie at all. Retropie targets Raspberry Pi almost exclusively, Thunder targets all ARM Linux devices.

Maybe I could make the Pi-Apps install script install Steam, Box86, and Box64 from Pi-Apps?

**Comment by hadcl4** [comment]
I just tried cleaning up setup a bit:
https://github.com/hadcl4/Thunder/commit/df1e9a395feb38c8018f9cb223304c0b56899522

**Comment by theofficialgman** [comment]
> The pi-apps install script doesn't run setup though. All apps have dependencies, so I don't see what's wrong here with setup. The Pi-Apps install script doesn't use setup at all.

right, but the `setup` script is still cloned and present when using this zip, its likely users will run it and the uninstall script here will not undo any of that

> Thunder isn't the same thing as Retropie at all. Retropie targets Raspberry Pi almost exclusively, Thunder targets all ARM Linux devices.

pi-apps is a raspberry pi exclusive target. retropie however is not, its has x86_64, armv6, armv7l, and armv8 targets which work on nearly any linux system. this includes the pi's of course but is not limited to them. there are special optimized targets for tinker pi, odroids, raspberry pis, nvidia jetsons/tegras but it can run on generic targets for all systems

**Comment by hadcl4** [comment]
> > The pi-apps install script doesn't run setup though. All apps have dependencies, so I don't see what's wrong here with setup. The Pi-Apps install script doesn't use setup at all.
> 
> right, but the `setup` script is still cloned and present when using this zip, its likely users will run it and the uninstall script here will not undo any of that
> 
> > Thunder isn't the same thing as Retropie at all. Retropie targets Raspberry Pi almost exclusively, Thunder targets all ARM Linux devices.
> 
> pi-apps is a raspberry pi exclusive target. retropie however is not, its has x86_64, armv6, armv7l, and armv8 targets which work on nearly any linux system. this includes the pi's of course but is not limited to them. there are special optimized targets for tinker pi, odroids, raspberry pis, nvidia jetsons/tegras but it can run on generic targets for all systems

I can add to the pi-apps install script to remove setup.

Even though pi-apps may target Raspberry Pi exclusively, it works fine on my RockPi 4B+ as well. I was just trying to say how Thunder and Retropie are different.

**Comment by hadcl4** [comment]
Would it work if I add to setup a warning to not run it if you installed Thunder through Pi-Apps?

**Comment by hadcl4** [comment]
Also I can build the emulators inside a RPiOS Buster VM to ensure they work on RPiOS.

**Comment by Botspot** [comment]
> Would it work if I add to setup a warning to not run it if you installed Thunder through Pi-Apps?

It would be better to detect the existence of another terminal theme, and then exit with an error.

**Comment by hadcl4** [comment]
> > Would it work if I add to setup a warning to not run it if you installed Thunder through Pi-Apps?
> 
> It would be better to detect the existence of another terminal theme, and then exit with an error.

How do terminal themes have to do with if it's running through Pi-Apps?

**Comment by theofficialgman** [comment]
> Would it work if I add to setup a warning to not run it if you installed Thunder through Pi-Apps?

I just see this as an very convoluted way to install these emulators. they should either be installed standalone with their own apps under pi-apps, or come from a large repository like retroarch, kodi (using retroarch), or retropie

**Comment by theofficialgman** [comment]
> > Would it work if I add to setup a warning to not run it if you installed Thunder through Pi-Apps?
> 
> It would be better to detect the existence of another terminal theme, and then exit with an error.

wrong github issue botspot, you are referring to this https://github.com/Botspot/pi-apps/pull/1617

**Comment by theofficialgman** [comment]
> The only thing is I want Thunder to work on any distro, so that's why emulators are compiled during setup.
> 
> I occasionally update emulator builds included, look through the CHANGELOG, there are some emulator updates in there.
> 
> And I spend a lot of time bugfixing!

I appreciate the effort you have done for your project, but it looks to be to be more of a liability to pi-apps than an addition.

2. there no guarantee that the binaries work on the supported pi-apps systems. for example, binaries for armhf should not be run on arm64 except under very specific installs through a chroot. binary installation need to be versioned, any updates to a binary should correspond to an update in the pi-apps repo so users get the update notification.
2. there is no way for pi-apps developers to fix any issues with your binaries or update them since they lie outside of our control.
3. if your setup script was used (which it isn't), it really doesn't make any sense to have all the buildscripts combined into one how you have it for maintenance and maintainability purposes.
4. there are already other better formatted projects out there that accomplish the same goals (often better like the emulationstation GUI, retroarch's multiple GUIs, attract mode, etc) and have significantly more developers behind them (retropie over 160+ contributors, and libretro has thousands of contributors), that just can't compare to one person.
4. your setup script doesn't handle installing all the dependencies for nearly anything you include there (a lot is missing) and it has no error checking

**Comment by hadcl4** [comment]
I give up on trying to get this on Pi-Apps, I'll just try some other app store...

Thunder works fine to me, so I don't get what's wrong with it.
