### ISSUE TITLE
Google play store

### ISSUE THREAD

**Issue by rbcoder117** [Botspot/pi-apps#1697]
### What is the name of the app?

Google play store

### About the app

Install apps from play store google all work because of arm chromebooks.
Is apk allowed if so this can run!

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.
- If apk can run

**Comment by theofficialgman** [comment]
apk files are the file format used on Android.
these can NOT run natively on Debian Linux systems or any GNU/Linux systems.

ARM chromebooks have an android app compatibility layer. I am not familiar with exactly which technique they are using on ChromeOS but someone more familiar with the chromiumOS can speak up on that.

Regardless, this is not a simple thing to implement, there are many methods of getting android apps running on linux, but most of them do not work on the pi or do not work for many apps.

Closing due to technological limitations

**Comment by rbcoder117** [comment]
:(

**Comment by theofficialgman** [comment]
if it were easy, it would have been done already. see other issues which request some of the android emulators like:
https://github.com/Botspot/pi-apps/issues/1710

**Comment by rbcoder117** [comment]
Ok
