### ISSUE TITLE
Network IP on wlan0 when you use Conky

### ISSUE THREAD

**Issue by tfavreau** [Botspot/pi-apps#170]
Greetings,

When you install the Conky app it seems that it is looking for an IP from eth0 and will not post the IP if you are connected via wireless.

**Comment by Botspot** [comment]
You are correct. I am not sure how to fix this.

Conky's config reads data values from either `eth0` or `wlan0`. I don't know of a way to make it  automatically choose.

**Comment by tfavreau** [comment]
I uninstalled the app, then reinstalled it from here, and it seems to work. I do not know the difference between the two other than it seems to work. https://www.novaspirit.com/2017/02/23/desktop-widget-raspberry-pi-using-conky/

**Comment by Botspot** [comment]
Yes, Novaspirit's version used `wlan0`. I changed it to `eth0`.

Bottom line: Some people use Wifi, while others use Ethernet. Unless Conky could automatically switch between the two interfaces, I don't see of a way to satisfy everybody.

**Comment by tfavreau** [comment]
I read this, does it help? There are two pages to the answer. https://www.linuxquestions.org/questions/debian-26/conky-and-wlan0-eth0-if-statement-894834/

**Comment by Botspot** [comment]
> I read this, does it help? There are two pages to the answer. https://www.linuxquestions.org/questions/debian-26/conky-and-wlan0-eth0-if-statement-894834/

That thread appears to discuss how to make conky display which interface is up.  
But we want to display statistics about one interface or the other. And I'm not sure how to do that,

**Comment by Botspot** [comment]
@tfavreau, I've figured out a slightly "hacky" workaround. But it should work for almost everybody.

Basically, when you install Conky, it will detect your current network interface. Whatever the interface is, the script replaces "`eth0`" with that interface.

Here's a zip for this experimental new version: [Conky.zip](https://github.com/Botspot/pi-apps/files/5749188/Conky.zip)  
To add this new version of the script to your Pi-Apps install, first delete the `/home/pi/pi-apps/apps/Conky` folder, then extract the zip to `/home/pi/pi-apps/apps`.
If `/home/pi/pi-apps/apps/Conky/install` exists, you extracted the zip correctly.

After you've extracted the zip, try installing the conky app from Pi-Apps. If all goes well, Conky will automatically display `wlan0` usage, instead of `eth0` usage.

**Comment by Botspot** [comment]
I've pushed those proposed changes to the repository.
