### ISSUE TITLE
appreciation

### ISSUE THREAD

**Issue by bap1968** [Botspot/pi-apps#1706]
### Cool ideas?

i cant express how much pi-apps have helped
i will make a donation asap ,its tuff when im trying to learn all these different apps and they just keep coming Idk how else i can help but if there is a way
i would be glade to ,,,,, thanks

**Comment by Botspot** [comment]
Thank you for expressing your gratitude. Most people don't.
We are just part-time volunteers who maintain Pi-Apps because we believe in its mission: to improve the Raspberry Pi desktop experience.

We don't need your money. If you want to help out but don't have programming knowledge, then tell your friends how Pi-Apps helped you. Maybe write about it on the Internet.

If you encounter any issues then please let us know (with a new issue, of course), and other than that, have a great day!

**Comment by bap1968** [comment]
You got it I'll tell everyone and try and do a tutorial on how easy it is
to install the apps maybe you can point me in the right direction to start
coding

**Comment by Botspot** [comment]
> maybe you can point me in the right direction to start coding

It's easy: keep an attitude that's willing to learn, and don't be afraid to try things. If you do this every day you'll be a master at the terminal in no time. In two years, I went from knowing nothing about computers and linux, to regularly writing bash scripts.
If this type of work interests you, go to YouTube and learn the basics of using a Linux terminal.
