### ISSUE TITLE
apt reinstall for local package not available

### ISSUE THREAD

**Issue by Peter-Donald** [Botspot/pi-apps#1712]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

apps not uninstalling or reinstalling 

### Description

what should i do?

### What is your operating system?

Raspberry pi 4

### (Optional) Error log? Terminal output? Debug messages?

```bash
🭊▅▅▅▅🬿
 🭈▂▂█▂▂▂▂█▂▂🬽
 ▌  ▗▖▗▖▗▖  ▐   █▀▀🭍 ▄
 ▌  ▗▖▗▖▗▖  ▐   █▄▄🭞 ▄ ▄▄ 🭂▀▀█ █▀▀🭍 █▀▀🭍 🭂🬰🬰🬰
 ▌  ▗▖▗▖▗▖  ▐   █    █    🭓▄▄█ █▄▄🭞 █▄▄🭞 ▄▄▄🭞
 🭓🬭🬭🬰🬰🬰🬰🬰🬰🬭🬭🭞                  █    █

Uninstalling LineRider...

Allowing packages required by the LineRider app to be uninstalled
These packages were: apt-transport-https, dirmngr, ffmpeg, gnupg, mono-devel, unzip, zip
Purging the pi-apps-10000b9e package...
E: The package stuntrally needs to be reinstalled, but I can't find an archive for it.
Apt finished.
Failed to uninstall the packages!
APT reported these errors:
E: The package stuntrally needs to be reinstalled, but I can't find an archive for it.
E: The package stuntrally needs to be reinstalled, but I can't find an archive for it.

Failed to uninstall LineRider!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu
```

**Comment by Crilum** [comment]
This isn't a problem with LineRider, It's a problem with Stunt Rally.
Does Stunt Rally still work? It looks like you need to reinstall it.

@ryanfortner It looks like Stunt Rally is installed from your repo, maybe you could look at this as well?

**Comment by theofficialgman** [comment]
there isn't a lot ryanfortner can do on his end. stuntrally (if installed through pi-apps) is directly download and installed via the deb. if apt for some reason need to reinstall it, which is says it needs to, it will not be available, since its placed in a temporary repo only used by pi-apps and cleared after install.

what is likely happening here is purging one of the dependencies for linerider, `apt-transport-https, dirmngr, ffmpeg, gnupg, mono-devel, unzip, zip` is triggering a reconfigure of one of the dependencies of stuntrally `libboost-wave-dev,libboost-system-dev,libboost-filesystem-dev,libboost-thread-dev,libogre-1.9-dev,libmygui-dev,libsdl2-dev,libogg-dev,libvorbis-dev,libenet-dev,libopenal-dev,libopenal-dev,libbullet-dev,libbullet-extras-dev`. after that reconfigure happens, the studtrally deb itself is told to reinstall which it can not do, since it is only downloaded and placed temporarily in the pi-apps local apt repo.

this is another case where the `less_apt` function is likely hiding usefull debug information which could be used to see which exact dependency is triggering the reinstall

**Comment by theofficialgman** [comment]
if I had to take a guess, my guess would be removing `ffmpeg` (dependency of linerider) is triggering a reinstall of `libsdl2-dev` (or one of its own dependencies like libsdl2-0.0) which then triggers a reinstall of stuntrally. I can't reproduce or prove this but I believe this is what is happening
