### ISSUE TITLE
Remove or reword TwisterOS support in README

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/pi-apps#1734]
### Cool ideas?

since twisterOS has now be dropped and without updates for over a year, I think we should remove it from the readme.
if a good replacement or supplement is made in the future, that can be added in its place but I don't think we should be recommending or advertising TwisterOS anymore

**Comment by Itai-Nelken** [comment]
It isn't abandoned. The main developer said about a week ago that they are working on a new version based on bullseye.

**Comment by theofficialgman** [comment]
did they? I thought the main dev said they are working on a different project that will not be twister and that twister is (and has been) dead

**Comment by ryanfortner** [comment]
To clear things up: monka and salva, part of the original pi labs team, left the twisterOS project to start their own. 

Twister is still being developed, but there is only one guy managing it now (grayduck), who has said that there is a bullseye release coming soon, however the new rpios release comes with complications and causes things to break. That's why it's been so long since any updates have been provided.

**Comment by Botspot** [comment]
Gman does have a point that the currently available version of TwisterOS is outdated and based on Buster. Some time in the future, there may be a new release of Twister based on Bullseye 64-bit, but this would be a completely new underlying system. Grayduck will probably be forced to differentiate to avoid confusion, likely calling the new one "Twister 2" or something like that.

Currently, with Pi-Apps still supporting Debian Buster, I think no action should be taken. But when Pi-Apps drops support for Buster, we should also take Twister off the list, assuming nothing changes before then.
