### ISSUE TITLE
Opera GX...

### ISSUE THREAD

**Issue by virat2010** [Botspot/pi-apps#1757]
### Cool ideas?

Opera GX?
Impossible to me! Can't wait to see if it's possible

**Comment by Botspot** [comment]
To get this working, you will need to overcome two hurdles:

1. Opera GX appears to only be available for Windows. Unless you want to run Windows on a Pi (not recommended for web browsing), you will have to use Wine to make it work. Which will be slow.
2. Opera GX does not appear to have any ARM releases which will work on Raspberry Pi. To make it work, you would have to emulate an x86 CPU processor. This will also harm performance.

Best case scenario: the browser will be extremely slow due to the two compatibility layers (wine and box86)
Most likely scenario: It won't work at all due to bugs and limitations in Wine and box86.

Stick with native ARM Linux applications for now. They are much faster on a Pi than anything else. For maximum browsing speed, try some of the high-performance browsers already available in Pi-Apps.
