### ISSUE TITLE
Nixos

### ISSUE THREAD

**Issue by rbcoder117** [Botspot/pi-apps#1764]
### What is the name of the app?

Nixpkgs

### (Optional) Where is the app hosted?

https://github.com/NixOS/nixpkgs

### About the app

I lets you install apps from a repo with many apps

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
I'm going to have to close this because this is WAY past pi-apps to support....
having another package manager from an unrelated project meant for use on nixOS that doesn't even support arm64 fully (and has no support for armv7l).

if users want to attempt this on their own, that is their own choice, it is way out of pi-apps control to support this

**Comment by rbcoder117** [comment]
Oh ok
