### ISSUE TITLE
Super Mario 64 PC Port

### ISSUE THREAD

**Issue by faizu396** [Botspot/pi-apps#1776]
I made an app :)
[Super Mario 64 PC Port.zip](https://github.com/Botspot/pi-apps/files/8637159/Super.Mario.64.PC.Port.zip)

**Comment by theofficialgman** [comment]
please use the correct app submission template next time: https://github.com/Botspot/pi-apps/issues/new/choose

I also have a script for setting up the SM64 PC port which uses bash/yad only (no python like yours).
I have not added it because of the nature of the port requiring a rom... which defeats the purpose I think a bit of being an app on pi-apps and might encourage piracy

https://github.com/cobalt2727/L4T-Megascript/blob/master/scripts/games_and_emulators/SM64.sh

**Comment by faizu396** [comment]
fixed the uninstall and install scripts
[Super Mario 64 PC Port.zip](https://github.com/Botspot/pi-apps/files/8643700/Super.Mario.64.PC.Port.zip)

**Comment by faizu396** [comment]
This was my first application and it was made pretty sloppily, so I get why it can't be added. I should probably learn a better way to create this port before uploading it.
