### ISSUE TITLE
YAD 12.0 (GitHub) updates

### ISSUE THREAD

**Issue by Crilum** [Botspot/pi-apps#1826]
### Cool ideas?

We could make Pi-Apps use a newer version of YAD, with newer featues.. It will definitely have bugs though...

YAD 12.0 (the GitHub version, the last SourceForge version was in 2017) now has switches, so Pi-Apps Settings can use switches for items like:
- `Shuffle App List`
- `Show Edit Button`
- `Enable analytics`

Of course we'd have to use a pre-built (or compile on install) binary, since the apt repos don't have this version.

Also, why the Icon change for Settings? I liked the old one better...

Some screenshots of the new version:
It has a app selection dialog, so that would remove the need for the `Preferred text Editor` setting:
![image](https://user-images.githubusercontent.com/91354257/168658250-c6ae4eb8-7c26-4253-9ef3-ce02a8d591bb.png)

Pi-Apps:

It doesn't have a x dimension scrollbar, which is good.

![image](https://user-images.githubusercontent.com/91354257/168658485-67400f45-6ed4-46a8-ac1a-aae2c7b4983d.png)

Pi-Apps Settings:

(it looks pretty much the same)

![image](https://user-images.githubusercontent.com/91354257/168658602-89db01f8-e208-47aa-b75b-41f32ef9d426.png)

App info box:

(I didn't compile it with some extensions, (html, and syntax highlighting), so it might look different with those enabled)

![image](https://user-images.githubusercontent.com/91354257/168658757-06974f4f-51b5-401c-97de-22a54a3783d1.png)

Search:

![image](https://user-images.githubusercontent.com/91354257/168659167-2eb73cd1-a7c0-4013-beaf-75340d66c9d1.png)

Multi-Install:

![image](https://user-images.githubusercontent.com/91354257/168659322-ae33138e-08b4-4b96-b69d-98ac6986814b.png)

**Comment by Crilum** [comment]
I think the app selection dialog is new as well as the ability to add switches (12.0 was released 13 days ago, and the [changelog says it adds switches](https://github.com/v1cont/yad/blob/04167716187efd7e63bb78e4a3f878c673ea99c6/NEWS#L7)).

**Comment by Botspot** [comment]
> The applist is centered in the newer versions, that's different

It's not centered, it's a gap of unusable space on the left. I'm not convinced that's a good thing.

> and the app info window doesn't open on the side of the applist.

That would appear to be a regression, not a feature.
I tried compiling YAD a few months back, and at the time it was unusable because button-icons are now forcibly resized to be squares. At the time, our Install and Uninstall icons were long rectangular PNGs to accommodate text beside them. With the Pi-Apps new gui update, that's no longer the case, but we'll still have to go through our pi-apps icons and make sure that everything is square to avoid stretching.

...OR we could leave yad as-is, not worrying about compatibility or compilation issues.
About app switches, they really aren't that groundbreaking. I could change the Combo-box to a checkbox if you want.

**Comment by Crilum** [comment]
>...OR we could leave yad as-is, not worrying about compatibility or compilation issues.
About app switches, they really aren't that groundbreaking. I could change the Combo-box to a checkbox if you want.

I think this is a good idea, I mostly thought the new version would have lots of new features, but it doesn't, really. I'll close this.
About the checkbox, I think that would be better than the dropdowns we have now.
