### ISSUE TITLE
Only show the progress monitor if there's more than one app queued

### ISSUE THREAD

**Issue by Crilum** [Botspot/pi-apps#1843]
### Cool ideas?

It seems unnecessary to have the Progress Monitor open if there's only one app to be installed/uninstalled. I think it would make more sense to open the Monitor when another app gets added to the queue.

Also, this:
``` 
queue is 'install;BalenaEtcher'
Received 'install;BalenaEtcher'
Action is install, app is BalenaEtcher
```
feels kind of debuggy (that's probably not a word, but whatever...), maybe we could add a setting for more/less debug output?

**Comment by Botspot** [comment]
During development of the `manage daemon` mode that is responsible for displaying what you call the "progress monitor", I reconsidered its preferred behavior multiple times. Should the queue-viewer (what I call it) only appear when there are multiple items in the queue? From a logical standpoint, yes.
But on the other hand, I realized that this was a fairly useful way to show overall progress of what was being done. Due to `manage daemon` not knowing how many apps the user will install in one session, the terminal's titlebar is set to a pathetically nondescriptive name: "Terminal Output".

Some apps, like Wine or Minecraft, take a long time to install with a lot of output. Without the terminal title or queue-viewer, it's possible that a distracted user could *forget* what they even chose to install! After thinking about it that way, I chose to make the queue-viewer visible even if only one app is managed during the session.

**Comment by Botspot** [comment]
> ```
> queue is 'install;BalenaEtcher'
> Received 'install;BalenaEtcher'
> Action is install, app is BalenaEtcher
> ```
> 
> feels kind of debuggy (that's probably not a word, but whatever...), maybe we could add a setting for more/less debug output?

I do plan to remove that debug output eventually, once many users confirm this new gui is 100% stable. [Right now it's not.](https://github.com/Botspot/pi-apps/issues/1842)
