### ISSUE TITLE
KTorrent

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#1892]
### What is the name of the app?

KTorrent

### About the app

_This package contains KTorrent, a BitTorrent peer-to-peer network client, that is based on the KDE platform. 
Obviously, KTorrent supports such basic features as downloading, uploading and seeding files on the BitTorrent network. 
Some features are available as plugins hence you should make sure you have the ones you need enabled._

https://apps.kde.org/ktorrent/
This is package-app.
[KTorrent.zip](https://github.com/Botspot/pi-apps/files/8789702/KTorrent.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Crilum** [comment]
English link: https://apps.kde.org/ktorrent/

**Comment by theofficialgman** [comment]
technically this falls under the package app rules since pi-apps does not have any install32/64 torrent clients/servers

https://github.com/Botspot/pi-apps/issues/185#issue-776095524

but since botspot already included 2 other torrent clients, might as well add another I guess... my only concern is this is a KDE app, and it comes with dependencies on a LOT of kde packages.. which compared to other torrent clients, does kinda add some unnecessary stuff.

**Comment by theofficialgman** [comment]
maybe consider qbittorrent (also an apt pacakge) as an alternative

**Comment by Crilum** [comment]
> but since botspot already included 2 other torrent clients, might as well add another I guess... 

Well, if we already have 2 torrent clients, I don't think we need more..
