### ISSUE TITLE
betaflight-configurator

### ISSUE THREAD

**Issue by ss8688** [Botspot/pi-apps#1913]
### What is the name of the app?

betaflight-configurator

### (Optional) Where is the app hosted?

https://github.com/betaflight/betaflight-configurator

### About the app

Betaflight Configurator is a crossplatform configuration tool for the Betaflight flight control system.

It runs as an application under different operating systems and allows you to configure the Betaflight software running on any supported Betaflight target.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
I personally feel like betaflight is TOO niche for pi-apps. for one, the configurator doesn't have armhf/arm64 release binaries, meaning a pi-apps developer would have to build (or buildscript) and maintain a piece of software we can't even use or test. Users would also need to already own a drone/quadcopter/helicopter that is compatible with this software before this is even useful.

see https://github.com/Botspot/pi-apps/issues/185

**Comment by Botspot** [comment]
Well we already have Mission Planner, which is in a similar category to this tool. I added it because there were many people on the Internet who expressed interest in getting it working on Raspberry Pi.

> meaning a pi-apps developer would have to build (or buildscript) and maintain a piece of software we can't even use or test.

Mission Planner launched, and that was enough for me. I didn't feel the need to test it with hardware.

Betaflight Configurator might also be highly sought after on Raspberry Pi, but I'm not sure. This is no guarantee that we will add this, but @ss8688, how many people do you think would actually use this tool on their Raspberry Pi if it was easy to install?
