### ISSUE TITLE
Something wrong with Tor browser on Kali linux...

### ISSUE THREAD

**Issue by yazishkhan** [Botspot/pi-apps#1963]
i am install kali linux on raspberry pi 4 to survive dark web but the tor browser is not support so that's why I install pi apps to install tor but their pi apps is also not supporting

**Comment by Itai-Nelken** [comment]
Tor browser is supported on both arm64 and arm32 on pi-apps. so I assume you got an error when installing it.
could you send the FULL terminal output when trying to install it?

**Comment by theofficialgman** [comment]
@yazishkhan for future bug reports, please use the appropriate new issue template, this helps with labeling and walking the user through by telling them what information we need to help you https://github.com/Botspot/pi-apps/issues/new/choose

incase you have not noticed, I have add the "needs more info" tag since we can not assist you in any way until you send more information.
