### ISSUE TITLE
Hakkly: A "hack" client for MCPI

### ISSUE THREAD

**Issue by 89paradox** [Botspot/pi-apps#2015]
### What is the name of the app?

Hakkly

### (Optional) Where is the app hosted?

https://github.com/89paradox/hakkly

### **A simple "hack" client for Minecraft Pi using it's Python API.**

You can easily use it using the command prompt
`sudo hakkly <hack #>`

"Hacks":
1- Fly
2- Rock Drop (Press BACKSPACE to drop)
3 - Spam Chat

(it needs sudo because it uses the keyboard module)

### Upload file or Add PR Link

[hakkly-piapps.zip](https://github.com/Botspot/pi-apps/files/9012249/hakkly-piapps.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [x] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
This seems like a small add-on for the existing Minecraft Pi (modded) game.

Here are our options:
1. Bundle hakkly with `Minecraft Pi (Modded)`.
2. Distribute it separately as an add-on app.
3. Duplicate `Minecraft Pi (Modded)` and under a new app name, include hakkly.
4. During installation, have `Minecraft Pi (Modded)` ask if you want hakky installed too.

Each of these options has problems:
1. Bundling would annoy some users and would force an "update" for all users, most of which will not care, or be aware, of this feature at all.
2. Distributing it separately would confuse things. Some people may try to use this with Minecraft Java or Bedrock Edition, even if the description clearly says otherwise.
3. Duplicating `Minecraft Pi (Modded)` would introduce extra complications and increase clutter. We already have too many Minecraft options! 😀
4. Asking permission to include hakkly during `Minecraft Pi (Modded)` installation would look like adware, and it would force an "update" for all users, most of which will not care.

At the end of the day, it is probably best to install this separately. If a lot of people seem to like your hakkly tool, we may make a note of it in the description of the `Minecraft Pi (Modded)` app.
