### ISSUE TITLE
Pi-Encryption

### ISSUE THREAD

**Issue by MemeManMemes** [Botspot/pi-apps#2025]
### What is the name of the app?

PI-Encryption

### (Optional) Where is the app hosted?

My file is hosted via a github link

### About the app

I wrote this app in C# to be a very powerful encrypting service with a unique hashing sequence that no programmer has ever though to make. 

### Upload file or Add PR Link

https://github.com/MemeManMemes/PI-Encryption
![icon-24](https://user-images.githubusercontent.com/97808663/177214880-23a713e0-c75c-4353-90fd-7c97c027c3c6.png) <- Icon (24)
![icon-64](https://user-images.githubusercontent.com/97808663/177214886-4a63dfbf-d1f0-4d51-b018-1a648871590e.png) <- Icon (64)
[PI-Encryption (1).zip](https://github.com/Botspot/pi-apps/files/9042289/PI-Encryption.1.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Sussy-OS** [comment]
Thanks for editing the title. This app seems like an app that I would use everyday. I am going to test right now, to see if works on my pi.

**Comment by Sussy-OS** [comment]
Your install needs some work. Adding/fixing some stuff right now.

**Comment by MemeManMemes** [comment]
Yeah I know.  I'm kinda bad with bash

**Comment by Sussy-OS** [comment]
I have fixed a few things, please update the PI-Encryption.zip file:
[PI-Encryption.zip](https://github.com/Botspot/pi-apps/files/9042135/PI-Encryption.zip)

**Comment by Sussy-OS** [comment]
Please edit app folder to this:
[PI-Encryption.zip](https://github.com/Botspot/pi-apps/files/9042148/PI-Encryption.zip)

**Comment by Sussy-OS** [comment]
I have fixed a few bugs, and added menu button.

**Comment by MemeManMemes** [comment]
wait how?  What "menu"

**Comment by Sussy-OS** [comment]
> wait how? What "menu"

The Pi menu button

**Comment by Botspot** [comment]
@MemeManMemes reached out to me on Discord and turned over the alleged source code for this program. While I have no way to prove that the source code matches the compiled program, it is possible the cause of the virus detection could be due to abnormal usage of SHA256 and SHA512 all throughout the program.

I did not fully understand how the encryption works, but it did not seem nearly as cryptographically sound as GPG or other leading encryption algorithms. Combine this with the explicit request of @MemeManMemes to not share the source code, for "just another layer of protection", this app is not a good fit for Pi-Apps.

But I no longer believe it's a virus.
