### ISSUE TITLE
Unable to Run on Termux

### ISSUE THREAD

**Issue by aman-boop** [Botspot/pi-apps#2035]
I use debian on termux and i installed pi-apps on it.
I was got stuck at preloding app list forever, but it installed.
Then i tried to install apps, but nothing work.
I tried to install other apps, but same thing happens with them.
It opens terminal output, but it nothing comes on it.
Please fix this.

**Comment by theofficialgman** [comment]
I don't think the issue is termux itself, but how users use termux and setup their users.

most people I have seen do everything in termux as ROOT or don't setup a user account properly. this leaves them unable to write to the /tmp folder, unable to write to /dev/null /dev/stdout /dev/stderr and other issue
