### ISSUE TITLE
Normal Suggestions

### ISSUE THREAD

**Issue by virat2010** [Botspot/pi-apps#2109]
### Cool ideas?

Got multiple ideas. I got few suggestions: I use the atom editor a lot along with vs code. You guys got the vs code part. Thanks for keeping this project running, It's amazing! Free Download Manager is a timesaver but I find a hard one to implement. Thanks again for this project and I would love to see these apps implemented. Hats off to you guys.

**Comment by theofficialgman** [comment]
github killed off the atom code editor already. all projects based directly on it will be archived December 15, 2022 so this will never come to pi-apps.

Free Download Manager (the current version with linux support) is now proprietary software, no longer open source. So that will also realistically never come to pi-apps without official builds from the developer.

I will suggest that you use  Xtreme Download Manager from pi-apps https://github.com/Botspot/pi-apps/wiki/Apps-List#-xtreme-download-manager . The developer has been hard at work with a full rewrite in C#, when that is done, it will be updated in pi-apps
