### ISSUE TITLE
Request for resources on learning bash

### ISSUE THREAD

**Issue by CoderLogy** [Botspot/pi-apps#2113]
Hey how to learn this level of bash like botspot where u can make gui with bash and more. pls tell

**Comment by Botspot** [comment]
Practice, persistence, and a willingness to find solutions. I believe the only reason I learned bash was because I had no other choice.
For years my only computer has been an Pi, and whenever it acted up or had an error, I had to research the error and find the commands to fix it. Over time, I began to make a list of common commands and began to understand how Linux and the shell worked.
Later I found out that it is possible to place multiple commands in a text file and *run* them as a script. Vdesktop was my first program.

After I became dissatisfied with Vdesktop, I wanted to make a graphical version. After searching for a while, (more google searches), I saw somebody mention **zenity** - a simple dialog program that can be used in shell scripts. Though I found Zenity to be too simple for my needs, along the way I discovered YAD - a far more customizable dialog program similar to Zenity.

And that's about it! What I am leaving out is all of the late nights when I continued trying to solve a particular problem, each time pulling through with a bit more knowledge gained. Fast forward a few years... and that's about it.

None of this would have happened had I gone the easy route, gotten a windows computer, and wasted my time on YouTube.

I am reminded of Alexander the Great, when he landed an army to conquer Persia. To remove any chance for retreat, he ordered all possible return vessels to be **burned**. He told his men, "We will either return home in Persian ships or we will die here."

So with that I say, **force yourself** to only use a Raspberry Pi. And [whenever you mess something up](https://forums.raspberrypi.com/viewtopic.php?t=275994) with your install, don't reflash the SD card, try to fix what you did. In a few years, you may be in a similar place

**Comment by CoderLogy** [comment]
Thnks @Botspot , is there any good resource to learn it faster.

**Comment by CoderLogy** [comment]
Thnks @Botspot , is there any good resource to learn it faster.

**Comment by Botspot** [comment]
Maybe there is, but this is just how I did it.

Other Pi-Apps devs are welcome to comment below how they got into bash.

**Comment by Itai-Nelken** [comment]
After you understand the basics, find something that interests you and try to create it. It is hard at first, but once you finish, you will have learnt more and be more comfortable with the syntax. Eventually, with enough patience you will succeed.
