### ISSUE TITLE
Raspbian lite support

### ISSUE THREAD

**Issue by symbios24** [Botspot/pi-apps#2119]
### Cool ideas?

Hello there,are PiApps working under Raspian lite enviroment? (No desktop)

If they are not,is it possible to add support for lite OS with a simple gui/menu that you can select what to install etc??

Thank you

**Comment by Botspot** [comment]
Pi-Apps is able to be used from the terminal. You can do things like `~/pi-apps/manage install Arduino` to install the Arduino app from the terminal.

However, some apps will try to show you dialog windows during installation. "Better Chromium" is a good example. It will try to display a configuration dialog during installation, so that you can enable the features you want. Without a running desktop, apps like these will fail to install.

But this all avoids the bigger question: What is the point of using Pi-Apps on a system that does not have a desktop environment? Very, very few apps on Pi-Apps can be used without a desktop environment anyway. Additionally, we usually avoid terminal-only apps to begin with.
Pi-Apps is a place to find desktop apps. If you want a CLI (command-line interface) tool to install CLI applications, then it might be better to find an alternate tool.

**Comment by symbios24** [comment]
There is a point in that most of the apps run with xorg/x11 manager fine from lite os, thats due to no highest desktop recourses they perform better,what i ask is that you can add lite os support also,i use apt but it will be better to have them all in a simple menu to select and install you can add a warning that will say some will not work or work correct from cli environment 

Thanks anyway

**Comment by Itai-Nelken** [comment]
If I understand correctly you are asking if pi-apps will work on pi os lite with a desktop installed? If that is the question the answer is yes, pi-apps will work.
If there is no desktop however, you can try manually installing apps with the manage script, though most of them won't work as Botspot said.

**Comment by symbios24** [comment]
No im asking that you add raspbian lite os support withourmt desktop with h a simple menu like this one in the photo under for exampe

![αρχείο λήψης](https://user-images.githubusercontent.com/10866601/187087601-f93cc002-08d7-4f04-a1a9-572a45d8ff54.png)

**Comment by Botspot** [comment]
> No im asking that you add raspbian lite os support without desktop at all, with a simple menu like this one in the photo under for exampe

And again, I am telling you that such a menu like that would be almost pointless, because 99% of the apps you install would not run without a desktop.

Why make a full Pi-Apps client that runs in the console, when everything you can _install_ from Pi-Apps cannot run without a desktop environment to begin with?

**Comment by symbios24** [comment]
They can run if xinit is used most of them at least i tested a lot out of desktop environment they run successful for example with xinit chromium
Descent,audacity,librecad,libreoffice etc.

Thanks for your time

**Comment by Itai-Nelken** [comment]
If you can run gui apps, why not use the yad gui?
