### ISSUE TITLE
Ability to rollback to a previous version.

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#2148]
### Cool ideas?

In pi-apps, many applications are available on third-party sites and the programs themselves are available on many OS, which means that they are not guaranteed to work on the Pi. If the user has installed the program and it doesn't work, he should be able to install the previous one.
My suggestion. In case of an installation error or incorrect operation of the program, or if pi-apps sees the program as installed, add a reinstall button. Then you can choose the reason for the reinstallation.
Two options: rollback to the previous version - pi-apps returns the old installation script and installs the program, then you can install it as an update; re-installation.

As an example: 'Minecraft Pi (Modded)' updated from 2.4.3 to 2.4.5 and started with an error. The solution is to install the old version.

![Безымянный](https://user-images.githubusercontent.com/88277343/194772333-f8b6cd5c-fef7-462a-b766-b8bf8e842354.png)

**Comment by theofficialgman** [comment]
> As an example: 'Minecraft Pi (Modded)' updated from 2.4.3 to 2.4.5 and started with an error. The solution is to install the old version.

we became aware of this as soon as the developer was. the solution was not to downgrade but to update to 2.4.6 which was released the next day.

> Two options: rollback to the previous version - pi-apps returns the old installation script and installs the program, then you can install it as an update; re-installation.

not viable, users should only be installing the version that pi-apps provides. if the version is pi-apps is broken, it should be reported and a maintainer can roll it back or patch it or do whatever is necessary so that it functions for all users.
