### ISSUE TITLE
Make PiGro auto-update

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#2211]
### Cool ideas?

For all the time that I had PiGro installed, it has [never been updated](https://github.com/Botspot/pi-apps/blob/master/apps/PiGro/install) (that is, which version I installed a long time ago, this remained), and there is no update mechanism in pi-apps.
Can you add [update](https://github.com/actionschnitzel/PiGro-Aid-/releases) functionality to pi-apps similar to DDNet?

**Comment by theofficialgman** [comment]
DDNet has shown that allowing build from source apps to auto-update is somewhat problematic. When dependencies are added without our knowledge, it can happen that a maintainer updates the app unaware of these changes and users cannot build.

I wanted to add a buildbot as a github actions to test all pi-apps updates before updating so that this would not be a problem but I am blocked by an issue at arm-action-runnner for multiple months now
https://github.com/Botspot/pi-apps/commit/c4f8d6475aa5beabb098d9ba2c815f852254b8d6
https://github.com/pguyot/arm-runner-action/issues/60

**Comment by Rak1ta** [comment]
@theofficialgman it seems that the creator of PiGro independently [monitors](https://github.com/Botspot/pi-apps/commits/master/apps/PiGro/install) the relevance of the data.

**Comment by theofficialgman** [comment]
what is the relavence of the monitors link you sent? that is the commit history for PiGro at pi-apps.

I don't care what the creators do, that does not matter, they do not actually try to build and install on a pi following our buildscript. the github actions that I made runs a raspbian buster image and attempts to install all packages that have been updated into it. if any of of them fails, it won't let pi-apps auto updater include that and will throw a warning.

but like I said, I can't add it because everything is running as root user in arm-runner-action

**Comment by theofficialgman** [comment]
this can be added now
I have created my own fork of arm-actions-updater with the features necessary https://github.com/theofficialgman/arm-runner-action and finalized and enabled the update verification system in pi-apps

currently all updated apps are tested for installation and uninstallation on buster armhf and bullseye arm64. if any one of these fails then the changes are reverted for that app and an error is written in the PR comment message.
