### ISSUE TITLE
minecraft.deb

### ISSUE THREAD

**Issue by Rocket2101** [Botspot/pi-apps#2227]
### What is the name of the app?

minecraft

### (Optional) Where is the app hosted?

https://launcher.mojang.com/download/Minecraft.deb

### About the app

minecraft game

### Upload file or Add PR Link

[Minecraft.zip](https://github.com/Botspot/pi-apps/files/10352881/Minecraft.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
Pi-Apps already has **seven** apps related to Minecraft. We have Minecraft Bedrock, Minecraft Pi, multiple launchers of Java Minecraft, and even a Minecraft server.
You don't even need a Pi to check if Pi-Apps already has Minecraft, because all apps are listed [here](https://github.com/Botspot/pi-apps/wiki/Apps-List).

@Rocket2101, you are not the first person to suggest we add an app that is already there. Is there a reason for it? Did you try to find out if minecraft is on pi-apps, or did you assume we did not have it yet?
Is there anything on the website that we could have done to help you realize that minecraft is already on Pi-Apps?
