### ISSUE TITLE
Chromium Widevine App probably doesn't work anymore

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/pi-apps#2272]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Google revoked older widevine versions

### Description

<https://bitmovin.com/google-deprecating-widevine-drm-cdm/>
this app downloads an older widevine version hidden in the pi-apps repo history. the version (as obtained by doing a strings and search of the binary) is `4.10.1679.0`

to my knowledge ALL widevine versions released prior to Dec 2022 have been revoked (at least on desktop platforms). so only the current version works
```
4.10.2557.0
```

### What are your system specs (run the following command in your terminal)?

```bash
N/A
```

**Comment by theofficialgman** [comment]
@Botspot thoughts? Even if this does still work, is there any reason for this application to exist when winevine support is present by default?

**Comment by Botspot** [comment]
It used to be necessary for sites requiring a ChromeOS user agent. Since late last year however, rpi-chromium-mods has changed chromium's user-agent to mimic that of chromeOS, so the only historical benefit in my mind for keeping Chromium Widevine was in case one of us Pi-Apps devs added 64-bit support before PiOS did.

I've been a bit out of touch with Pi news lately, but as [libwidevinecdm0 now works](https://forums.raspberrypi.com/viewtopic.php?p=2122835&hilit=widevine+64#p2083892) out of the box on PiOS 64-bit, I no longer see any reason to keep Chromium Widevine in Pi-Apps.

I will remove it in a few minutes.
