### ISSUE TITLE
PyCharm not allowing addition packages

### ISSUE THREAD

**Issue by dtsig** [Botspot/pi-apps#2273]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

PyCharm not allowing new packages

### Description

Start the program
Menu item View>Tools Windows>Add Packages
The Packages panel opens and says "Nothing to show"
There is no 'link' to Add packages. 
This is the way it works on a PC

I don't know what else to say .. it is just that simple to duplicate

### What are your system specs (run the following command in your terminal)?

```bash
dsig@raspberrypi:~ $ ~/pi-apps/api get_device_info
OS: Raspbian GNU/Linux 11 (bullseye)
OS architecture: 32-bit
Last updated Pi-Apps on: 03/01/2023
Latest Pi-Apps version: 03/01/2023
Kernel: armv7l 5.15.84-v7l+
Device model: Raspberry Pi 4 Model B Rev 1.4 
Cpu name: Cortex-A72
Ram size: 7.89 GB
Raspberry Pi OS image version: 2022-09-22
Language: en_US.UTF-8
dsig@raspberrypi:~ $
```

**Comment by theofficialgman** [comment]
jcef (java chromium electron framework) is not available in binary form for armv7l. thus this window errors an cannot load
`Caused by: java.lang.IllegalStateException: JCEF is not supported in this env or failed to initialize`

pycharm is deprecated on all 32bit platforms and is held back to 2021.1 for arm32 in pi-apps as it is the last fully working version on 32bit.

you will need to use a 64bit (aarch64) OS with GLIBC 2.29+ (piOS bullseye 64bit is a good start) in order to use the latest version of pycharm which does have aarch64 full support including in jcef. GLIBC 2.26+ will eventually only be required once jetbrains upgrades to CEF 111 https://youtrack.jetbrains.com/issue/JBR-5308/Update-CEF-to-version-110

**Comment by dtsig** [comment]
Thank you for the quick, though saddening, response

DSig

**Comment by theofficialgman** [comment]
@dtsig it really isn't a bad thing. you (and most users) should be using piOS 64bit anyway.
32bit support is getting dropped by many projects and 32bit OSs can't take full advantage of your 8GB of ram anyway.

just install piOS 64bit and you will be glad you did so.

**Comment by dtsig** [comment]
will do .. thanks
