### ISSUE TITLE
GroupMe Nativefier app

### ISSUE THREAD

**Issue by Crilum** [Botspot/pi-apps#2282]
### What is the name of the app?

GroupMe

### (Optional) Where is the app hosted?

...
I guess [web.groupme.com](https://web.groupme.com) would be what goes here

### About the app

GroupMe is a online instant messaging service by Microsoft.

I just used Nativefier on the webapp URL, and it works perfectly.. This would need to be tested on a RPi obviously, but I think it would be a good addition to Pi-Apps.

### Upload file or Add PR Link

https://github.com/Crilum/stuff/blob/main/GroupMe-linux-armv7l.zip?raw=true
https://github.com/Crilum/stuff/blob/main/GroupMe-linux-arm64.zip?raw=true

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [ ] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
I don't really see a need for groupme (or whatsapp for that matter) to have nativefier based apps (as mentioned here before https://github.com/Botspot/pi-apps/issues/1791#issuecomment-1129106616 ). snapdrop makes sense because it allows for totally offline use with the nativefier webapp but this is not the case for online messaging services.

is there some feature that this adds to groupme that wouldn't be better served already by a browser tab with groupme open or a "Web Apps" (https://github.com/Botspot/pi-apps/blob/master/apps/Web%20Apps/description) based program (which uses the system chromium browser with potentially better performance, decoding, and DRM support than electron)?

**Comment by Botspot** [comment]
Not to mention the RAM penalty for running multiple separate Chromium instances

**Comment by Botspot** [comment]
However I will say that I am on the fence with the whole idea of wrapping up communication webapps inside Nativefier windows.
7000 users is 7000 people who decided they wanted Whatsapp to look and feel like a normal program.

And if you only need to quickly check whatsapp or groupme and chromium is not already open, it is probably faster to launch these dedicated "programs" instead of searching for their website counterparts after opening chromium.

**Comment by Crilum** [comment]
I personally like having software like this as it's own window, for example.. Discord. Sure you can run it it a browser... But the desktop app is just more convenient (and has a few other features, but that doesn't really apply to this).

I'd honestly take using more RAM over using GroupMe or Whatsapp in a browser. Same thing with [Telegram](https://web.telegram.org/k/).

I think that it could be added as a "Web Apps" app, but I do like nativefier apps soo....

I could go either way on this, so whatever you guys decide.. Scripts would be super easy to implement, if you decide this app would be a good fit for Pi-Apps.

**Comment by theofficialgman** [comment]
I personally don't see any benefit of a nativefier app over a web app, only negatives.
The negatives are:
- higher storage use (installing electron which is 100MB+ when chromium is already installed)
- worse rendering performance (uses generic electron builds without piOS/distro patches)
- no hardware accelerated video decoding/encoding (eg: video playback)
- additional ram used when running (compared to an additional chromium tab). we have 2GB pi users, this is simply a bad option for them.
- gets out of date and insecure fast (we have to keep it up to date otherwise user data is at risk running old chromium based versions)

I am going to ask again. Is there any benefit that nativefier brings to the table over a chromium webapp for GroupMe?

**Comment by Crilum** [comment]
Okay... I think you're right @theofficialgman. I just realized that idle, the GroupMe nativefier app uses 4% of my Desktop's CPU... And 300 MB of RAM... So it probably wouldn't perform too well on Raspberry Pi.

As much as I like the aesthetic of nativefier apps, a webapp might be a better idea for this one..

**Comment by theofficialgman** [comment]
nativefier is unmaintained and no longer used by any pi-apps applications. see https://github.com/Botspot/pi-apps/pull/2333#issuecomment-1874169234 for more info
