### ISSUE TITLE
Aseprite

### ISSUE THREAD

**Issue by cdkw2** [Botspot/pi-apps#2316]
### What is the name of the app?

aseprite

### (Optional) Where is the app hosted?

It is open source on GitHub here: https://github.com/aseprite/aseprite

### About the app

The latest response from the aseprite team on the raspberry pi version is present here and it is tagged low priority: https://github.com/aseprite/aseprite/issues/2835

**I know this issue is discussed before (that's why I didn't check that box up there but it was not letting me post this without checking it o please forgive me for that T_T) : https://github.com/Botspot/pi-apps/issues/1486**

But it talks about the mouse lag thing and it being a bit buggy overall, my long distant friend recently told me that he has compiled aseprite on and it works pretty good. Please revisit this app as it'sone om my dream apps to run on a raspberry pi as raspberry pi is my main PC.

Some important link's I think will help you: 

https://community.aseprite.org/t/raspberry-pi-version/7419/4
https://www.gudinna.com/projects/aseprite/skia/aseprite-m96/Skia-Linux-Release-ARM32.zip

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [ ] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by cdkw2** [comment]
I know this issue is discussed before (that's why I didn't check that box up there but it was not letting me post this without checking it o please forgive me for that T_T) : https://github.com/Botspot/pi-apps/issues/1486

**Comment by cdkw2** [comment]
I know this issue is discussed before (that's why I didn't check that box up there but it was not letting me post this without checking it o please forgive me for that T_T) : https://github.com/Botspot/pi-apps/issues/1486

Please reconsider this!!!

**Comment by theofficialgman** [comment]
please don't double post, thats why the checkbox is there that prevents such.
the previous issue has not been closed

**Comment by Botspot** [comment]
I think gman's response here is incomplete, so I will elaborate. @cdkw2, your opinion here matters and it is perfectly fine to try to update us on new details of a potential app. But in this case, it would have been better to voice support in the original issue instead of opening a new one. It would have been better to comment in https://github.com/Botspot/pi-apps/issues/1486 with new information, rather than opening a fresh, duplicate issue that splits the conversation and complicates our job.

We're not trying to silence your opinion. Does that make sense?

**Comment by theofficialgman** [comment]
yeah what botspot said is what I meant. I generally don't have the patience or time anymore to write out a paragraph response to every user like this anymore.

Sorry for being brief @cdkw2 

aseprite is just one of those things thats a big of a nightmare to build and creater scripting for due to using google gn (for the skia dependency). I already went through that torture once with musescore... maybe I'll be up for it again in a month or so with this 🙃

**Comment by cdkw2** [comment]
Sorry for complicating your jobs, I thought if I commented on the original post I would probably get unnoticed. So that's why I opened a new one. Sorry for being a nightmare to be dealt with. I will try to be a good community member in the future.

**Comment by Botspot** [comment]
> Sorry for being a nightmare to be dealt with. I will try to be a good community member in the future.

Don't be so hard on yourself! It is simply our policy to keep discussions in one github issue. You did not know that. No hard feelings at all, at least from me. :)
