### ISSUE TITLE
BunJS - Install Script

### ISSUE THREAD

**Issue by CommanderGL** [Botspot/pi-apps#2327]
### What is the name of the app?

Bun

### (Optional) Where is the app hosted?

Github + Website.

### About the app

Node.JS alternative with out of the box Typescript support. Bun is also 30x faster than Node.

### Upload file or Add PR Link

[BunJS.zip](https://github.com/Botspot/pi-apps/files/11484209/BunJS.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
Two things:
1. Bun appears to not have a release target for armv7l systems, meaning that it will fail to install on PiOS 32-bit. I found this out by inspecting the bunjs install script at https://bun.sh/install
    ```bash
   case $(uname -ms) in
   Darwin x86_64)
       target=darwin-x64
       ;;
   Darwin arm64)
       target=darwin-aarch64
       ;;
   Linux aarch64 | Linux arm64)
       target=linux-aarch64
       ;;
   Linux x86_64 | *)
       target=linux-x64
       ;;
   esac
   ```
   I've copied the relevant code for you to see. Notice how there is only Linux arm64, and not a 32-bit variant mentioned. This is easy to fix from your end. You can fix it by renaming the apps `install` script file to `install-64`, to let Pi-Apps know that this can only be installed on 64-bit systems.
2. This seems more like a developer utility which would be integrated in a project, not useful by itself for many average desktop users. We generally only add the most mainstream programming tools to Pi-Apps.

I would suggest looking through our apps which already install and use NodeJS internally. Take a look at our **Boxy SVG** app. If you can make Boxy SVG run faster by switching from Node.JS to BunJS, that would be extremely useful for the type of people who use Pi-Apps.

**Comment by CommanderGL** [comment]
Oh sorry didn't notice it didn't have 32-bit support but I'm wondering why NodeJS is in the tools section (That's the reason I put it there.)

**Comment by CommanderGL** [comment]
Update:
[BunJS.zip](https://github.com/Botspot/pi-apps/files/11523382/BunJS.zip)

**Comment by CommanderGL** [comment]
Oh and I wouldn't find a way to make BoxySVG run faster (It wasn't generating executable.)

**Comment by theofficialgman** [comment]
the uninstall failed with an error for all targets. refer to any of the logs here https://github.com/Botspot/pi-apps/actions/runs/5092441326

**Comment by theofficialgman** [comment]
I also don't like the install script. You should attempt to integrate it directly and remove the dangerous modifications to the deprecated .bashrc. a more proper location for addition of a folder to the path would be to create a `.sh` file in `/etc/profile.d/` for the system or modify the `~/.profile` and make so that it can be easily removed with a sed command.

what would be better would be to simply install bun to the default system binary folders (eg: `/usr/local/bin`). You should make it so the install script installs a specific version of bun that way pi-apps can check for bun updates on the github <https://github.com/oven-sh/bun/releases> and keep the users bun version up to date. bun is a single binary, so its a simple as dropping the binary from the zip (renaming it as `bun`) into the `/usr/local/bin` folder

**Comment by theofficialgman** [comment]
closing stale issues

**Comment by Botspot** [comment]
@CommanderGL reply back and respond to past concerns and we can re-open this for you.
