### ISSUE TITLE
Add Dolphin to Pi-Apps!

### ISSUE THREAD

**Issue by xPi400** [Botspot/pi-apps#2391]
### What is the name of the app?

Dolphin Emulator

### (Optional) Where is the app hosted?

dolphin-emu.org

### About the app

Dolphin Emulator can emulate Wii and GameCube games, and install Wii WADs to the virtual Wii NAND.
Note: Add the latest Beta or Development version, not the latest stable. The stable is from YEARS upon YEARS ago.
### Confirmations

- [x] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by xPi400** [comment]
There is already emulators (Wine, box86 and box64, QEMU) already on Pi-Apps. So why can't we another console emulator? We got PPSSPP as well as what I mentioned above, so why not?

**Comment by Rak1ta** [comment]
Dolphin is already in [pi-kiss](https://github.com/jmcerrejon/PiKISS/blob/master/scripts/emus/dolphin.sh) and even works (did not fully check it in games)

**Comment by xPi400** [comment]
> Dolphin is already in [pi-kiss](https://github.com/jmcerrejon/PiKISS/blob/master/scripts/emus/dolphin.sh) and even works (did not fully check it in games)

Last I installed Pi-kiss and checked it Dolphin wasn't in there. But that _WAS_ also last year...

**Comment by xPi400** [comment]
The version of Dolphin PiKISS installs is version 4.0, not even 5.0, the most recent (but 7 years ago) stable build, and not even the latest BETA, let alone what installing Dolphin on Linux usually does which is the latest development build

**Comment by Botspot** [comment]
We've actually had one other github issue requesting Dolphin Emulator before. https://github.com/Botspot/pi-apps/issues/595
That issue was closed because the installation method proposed there would not work.

This time around, it just comes down to someone sitting down and finding a way to install the latest version. Easy, right? Well maybe. I don't know, and at least right now I do not have the time to find out personally, though someone else is encouraged to.

**Comment by theofficialgman** [comment]
We build dolphin from source at the L4T-Megascript.
No released pi is capable of running wii or GameCube games at full speed or even near playable performance so I don't see any reason to add this. The CPU, ram, and GPU are too slow, slow, and slow.

**Comment by everypizza1** [comment]
> We build dolphin from source at the L4T-Megascript. No released pi is capable of running wii or GameCube games at full speed or even near playable performance so I don't see any reason to add this. The CPU, ram, and GPU are too slow, slow, and slow.

![Screenshot_20230717-082546](https://github.com/Botspot/pi-apps/assets/82726593/25c8d39c-e80d-4337-8ea2-804ff2801b3a)
The Pi seems to have better specs.

**Comment by theofficialgman** [comment]
Emulation of any system is expensive. You need a device of one or more magnitudes of power greater than your target system since you are emulating the hardware of that device using software. The pi simply has too slow ram to emulate the GPU shaders and handle the JIR recompiler, too slow CPU to execute the recompiled instructions, and a laughably terrible GPU.
