### ISSUE TITLE
Digital Clock Package app 

### ISSUE THREAD

**Issue by AIREEXZIP2** [Botspot/pi-apps#2405]
### What is the name of the app?

digital clock

### About the app

 A simple shell script that will show the current time on our screen.

How does it work?

To start, you would typically use the "date" command in Linux, which provides system date and time information. The "date" command allows you to specify a format for displaying the date and time.

The basic structure of the digital clock script involves an infinite loop. An infinite loop is a loop that runs indefinitely, repeatedly executing the same set of commands until explicitly terminated. In this case, it ensures that the digital clock keeps updating and displaying the current time continuously.

Steps_
1-Use the "date" command to get the current time in the desired format.
2- Create an infinite loop that continuously updates and displays the time.
3- Display the current time on the screen within the loop.
4- Add a delay to control the refresh rate of the clock (e.g., every second).
5- By executing this script, you'll have a digital clock that shows the current time and keeps updating in real-time until you stop the script manually.

### Upload file or Add PR Link

[digital clock.zip](https://github.com/Botspot/pi-apps/files/12208315/digital.clock.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
Hello @AIREEXZIP2! Thank you fro submitting this. Unfortunately there are a few problems with it.
First of all, we try to prioritize adding apps that a normal, everyday desktop user would find useful. To see the current time, an average user may look at a clock plugin in the panel, or maybe use a system monitor like conky to view the time.

This very simple shell script does not exactly fit with what we are trying to add to Pi-Apps. I suggest having a look at our [App Eligibility Rubric.](https://github.com/Botspot/pi-apps/issues/185)
Also check out our [very informative guide to adding an app to pi-apps.](https://pi-apps.io/wiki/development/Creating-an-app/), because I noticed a few simple issues in your scripts.

I do not think that any amount of changes to the script would persuade us to add this app to the official list of apps on pi-apps, so I am closing this issue now. You can still feel free to reply back here and ask about anything else.
