### ISSUE TITLE
Include moonlight

### ISSUE THREAD

**Issue by ianalexis** [Botspot/pi-apps#2418]
### What is the name of the app?

Moonlight

### (Optional) Where is the app hosted?

https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Raspberry-Pi-4
https://github.com/moonlight-stream/moonlight-qt/releases

### About the app

TL;DR:
Moonlight is an remote controller for windows and linux, low latency, high quality that can be used with Sunshine in the pc.
Everything is FOSS.
-------
[Moonlight PC](https://moonlight-stream.org/) is an open source PC client for NVIDIA GameStream, as used by the NVIDIA Shield.
This implementation is to use the Raspberry as a Shield.
Moonlight can be used with [Sunshine](https://github.com/LizardByte/Sunshine), a self-hosted game stream host for Moonlight. Offering low latency, cloud gaming server capabilities with support for AMD, Intel, and Nvidia GPUs for hardware encoding.

-----
Has been named a time ago in this comment from @theofficialgman and @Rak1ta https://github.com/Botspot/pi-apps/issues/2198#issuecomment-1355396425

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
due to the complications and multiple possible configurations for installing moonlight depending on the OS, video backend (mesa vs legacy), hardware (pi, tegra, other arm hardware), and display servers (X11/wayland) all requiring different setups I don't think this is viable for inclusion in pi-apps.

Maybe in the distant future if we only support PiOS bookworm and newer on wayland only clients with only pi4 and newer and moonlight-qt for raspberry pis is updated to support this we can think about adding it.

As of now none of that is not the case so this just isn't feasible.  It is a great application when you have it setup, we just can't include it for the above reasons.
