### ISSUE TITLE
EDIT ME Include the app name and if it is a Package app or an Install based App

### ISSUE THREAD

**Issue by kidmakesreal** [Botspot/pi-apps#2433]
### What is the name of the app?

Minecraft Pi Server

### About the app

this is a one click installer for a minecraft pi edition server

### Upload file or Add PR Link

[minecraft_server.zip](https://github.com/Botspot/pi-apps/files/12434549/minecraft_server.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
Cool. @NoozAbooz would you like to take a look at this one?

**Comment by NoozAbooz** [comment]
> Cool. @NoozAbooz would you like to take a look at this one?

It's been quite awhile since I've looked here... I think gman is better suited than me to look at these. Just looking at the script however, it doesn't look like it conforms to Pi-Apps app standards.

@kidmakesreal I would suggest using the Pi-Apps app creator tool to remake the app (https://pi-apps.io/wiki/development/Creating-an-app/) and install the appimage in a way similiar to https://github.com/Botspot/pi-apps/blob/master/apps/Minecraft%20Pi%20(Modded)/install

Also adding @TheBrokenRail to this convo if he has anything he wants to add.

**Comment by kidmakesreal** [comment]
> > Cool. @NoozAbooz would you like to take a look at this one?
> 
> It's been quite awhile since I've looked here... I think gman is better suited than me to look at these. Just looking at the script however, it doesn't look like it conforms to Pi-Apps app standards.
> 
> @kidmakesreal I would suggest using the Pi-Apps app creator tool to remake the app (https://pi-apps.io/wiki/development/Creating-an-app/) and install the appimage in a way similiar to https://github.com/Botspot/pi-apps/blob/master/apps/Minecraft%20Pi%20(Modded)/install
> 
> Also adding @TheBrokenRail to this convo if he has anything he wants to add.

sorry it needed work i fixed it and put it here https://github.com/Botspot/pi-apps/issues/2434
