### ISSUE TITLE
Suggestions for improving the GUI

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#2450]
### Cool ideas?

Is it possible to add select all/unselect buttons to program update windows? 
For example, many updates have been released, but I do not update everything (for example, broken WhatsApp, WPS (armhf kernel activated), Box86, etc.).  It would be convenient for me to have a button that removes all checkmarks from the selection menu. 
![image](https://github.com/Botspot/pi-apps/assets/88277343/b051c29b-087e-4ce3-bff6-efc6dab62708)

Can pi-apps take into account the position of an open window so as not to display the second one off the screen? (I doubt that this is necessary, I encountered this using a pi with a CRT TV, and there is a very low screen resolution)
![image](https://github.com/Botspot/pi-apps/assets/88277343/6cb8dd86-6205-4330-8515-c6d4c7b0f37c)

**Comment by Botspot** [comment]
Adding a select all button would require changes to YAD's source code on a fork. It could be done, but then we would have to package our fork of yad and ensure it installs correctly for everyone. Right now we just use the default available version of yad from debian.

Also, why do you want this? To select all, simply do not de-select anything. To avoid updating anything, simply close the updater window.

About support for small resolutions: probably the best solution now is to use the pi-apps terminal interface. You could also reduce your system GTK scale factor and font size with the "for small screens: set defaults" option in PiOS.

**Comment by Botspot** [comment]
I suppose that if we wanted to improve the small-screen experience, changes could be made like removing the image on top, maximizing the window, and removing other header information to give more space for the list and the description.

**Comment by theofficialgman** [comment]
> Can pi-apps take into account the position of an open window so as not to display the second one off the screen? (I doubt that this is necessary, I encountered this using a pi with a CRT TV, and there is a very low screen resolution) 

it is up to the compositor to place the window as it sees fit. We give it a position on screen based on the currently opened main windows so that the new window gets placed next to it.

some compositors will place the window as you see it (with part of it offscreen) and others will place it so that it never goes offscreen but ignores the window location that we specify (so it would appear overtop of the main window).

IMHO, the latter is a worse solution so most compositors don't do that.

There really isn't anything to be done here. Thats just how window management works.
