### ISSUE TITLE
It works but not great

### ISSUE THREAD

**Issue by dddnick** [Botspot/pi-apps#2453]

**Comment by Botspot** [comment]
Hello @dddnick, thank you for your feedback. But how can we improve Pi-Apps when you have not mentioned what exactly is "not great"?

**Comment by Botspot** [comment]
Please be specific.

**Comment by theofficialgman** [comment]
Hi @dddnick I see that you are a new user to GitHub.

Please note that developers at many projects provide issue templates to assist and guide our users to providing helpful and meaningful feedback.

At pi-apps we leave the blank template still available so that knowledgeable users who truely have something to report can still do so without feeling limited by our templates. The blank template is NOT there for you to open an issue with a non-descriptive title and no contents. This is not helpful or meaningful in any way and is actually a net negative as it wastes each of our times.

Consider the advice I have given here when opening future issues here and at other repositories.

I am going to close this issue to give you a chance at opening a new meaningful and helpful issue using one of our templates as fit for the problem you might be facing.
