### ISSUE TITLE
Zoom SSO Login does not load the app

### ISSUE THREAD

**Issue by YodaLightsabr** [Botspot/pi-apps#246]
When logging in to Zoom with SSO, after completing the sign in form, it opens a new Chromium window, rather than signing into the Zoom app. I am on Raspberry Pi 4 with 2GB of RAM, and Raspbian installed.

**Comment by Botspot** [comment]
This is a known issue with no known fixes.

Only Zoom accounts work. SSO doesn't.

**Comment by YodaLightsabr** [comment]
> This is a known issue with no known fixes.
> 
> Only Zoom accounts work. SSO doesn't.

Just because there are no known fixes is a reason to close it? This doesn't seem done and complete. Just because you don't have a solution isn't a reason to close it. Please re-open it. Of course there is a way to fix it. And if you can't, at least say why please.

**Comment by Botspot** [comment]
Plenty of others have complained about the SSO feature not working, but unfortunately, there is no way to fix it.

It is not possible to fix because Zoom is proprietary software. There is no source code to tweak because the Zoom desktop client is not open source.

If Zoom stops working tomorrow (which actually is the case), there's almost nothing anybody can do about it. Besides asking Zoom developers to do it for us. (which so far has gotten nowhere)
