### ISSUE TITLE
Minecraft Bedrock Launcher - Bookworm - 64-bit system

### ISSUE THREAD

**Issue by bagong** [Botspot/pi-apps#2463]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

App won't start after install

### Description

Well, after starting the program "the normal way" (clicking desktop-launcher in application menu) nothing happens.

I copied the exec-entry from the launcher into the terminal and got this error:

`````
env QTWEBENGINE_CHROMIUM_FLAGS='--enable-logging --log-level=0 --v=3 --single-process --no-sandbox' GALLIUM_HUD=simple,fps /home/pi/.local/bin/MCBedrock.AppImage
/tmp/.mount_MCBedrt5K5AW/usr/bin/msa-ui-qt: /tmp/.mount_MCBedrt5K5AW/usr/lib/libselinux.so.1: no version information available (required by /lib/aarch64-linux-gnu/libgio-2.0.so.0)
/tmp/.mount_MCBedrt5K5AW/usr/bin/mcpelauncher-ui-qt: /tmp/.mount_MCBedrt5K5AW/usr/lib/libselinux.so.1: no version information available (required by /lib/aarch64-linux-gnu/libgio-2.0.so.0)
/tmp/.mount_MCBedrt5K5AW/AppRun: line 14:  2290 Segmentation fault      $DIR/usr/bin/msa-ui-qt
/tmp/.mount_MCBedrt5K5AW/AppRun: line 14:  2291 Segmentation fault      $DIR/usr/bin/mcpelauncher-ui-qt "$@"
/tmp/.mount_MCBedrt5K5AW/AppRun: line 15: kill: (2290) - No such process
`````

(apart from this I was a bit surprised that the install installed all the xyzhf-libraries. I thought that wasn't necessary with AppImages...)

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 10/12/2023
Latest Pi-Apps version: 10/13/2023
Kernel: aarch64 6.1.0-rpi4-rpi-v8
Device model: Raspberry Pi 4 Model B Rev 1.2 
Cpu name: Cortex-A72
Ram size: 3.79 GB
Raspberry Pi OS image version: 2023-10-10
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
See above.
```

**Comment by theofficialgman** [comment]
CC @TheBrokenRail any ideas here? ^

**Comment by theofficialgman** [comment]
@bagong sorry out current appimage shipped in pi-apps is quite old for the bedrock launcher and there is a newer version upstream. You can try it out by downloading it anywhere and running it directly via terminal. https://github.com/minecraft-linux/appimage-builder/releases 

I will check myself if it is stable later today and add a pi-apps auto-updater

**Comment by Rak1ta** [comment]
@theofficialgman doesn't work, same error

**Comment by theofficialgman** [comment]
> I prefer upstream linux distributions, raspberry pi os used to remove debian packages (I assume you cannot install the bookworm apt package on it https://github.com/minecraft-linux/pkg).
64bit piOS uses debian default repos with only an additional repo added for piOS specific packages (such as their desktop environment, rpi-imager, and the like). So no they don't remove any packages (the only way to do that in this configuration would be to have a apt pin that disables packages from the debian repos which they do not have).

I was not aware that you built debs. They bookworm apt package should install without any problems.

**Comment by theofficialgman** [comment]
@ChristopherHX can confirm the issue on the arm64 appimage myself. passing `-v` does not produce any more output.
The issue is already present in the original log
`/tmp/.mount_MCBedrt5K5AW/usr/bin/msa-ui-qt: /tmp/.mount_MCBedrt5K5AW/usr/lib/libselinux.so.1: no version information available (required by /lib/aarch64-linux-gnu/libgio-2.0.so.0)
`
the version of libselinux.so.1 that you bundle in the appimage is incompatible with the system `libgio-2.0.so.0` that tries to load it.

btw, the arm64 bookworm debs do work but we prefer to use the same install methods on all systems when possible. When I say they work, I mean the QT gui runs. Attempting to run the latest version of minecraft crashes wayfire back to the login screen.

**Comment by bagong** [comment]
@theofficialgman , thanks for the deep analysis, way better than I could have ever done! So is "wayfire-compatibility" Rpi.com or MS' job? Is it likely to happen? Thanks for your care!!

**Comment by theofficialgman** [comment]
> btw, the arm64 bookworm debs do work but we prefer to use the same install methods on all systems when possible. When I say they work, I mean the QT gui runs. Attempting to run the latest version of minecraft crashes wayfire back to the login screen. More investigation needed.

crashing was because of 16K kernel used on the pi5. KDE Plasma wayland DE did not crash but instead showed a useless error and then a GUI popup saying the version of minecraft selected was unsupported and to select a support version (which was untrue). changing to the 4K kernel it does run with the debs

**Comment by theofficialgman** [comment]
> @theofficialgman Can you do `--appimage-extract`, delete `usr/lib/libselinux.so.1` from `squashfs-root` and run AppRun

@ChristopherHX the warnings/errors go away but it still segfaults on `mcpelauncher-ui-qt` like before

**Comment by theofficialgman** [comment]
> So `--help` doesn't work too?

correct, it does not work

**Comment by theofficialgman** [comment]
> I'm asking because, I never heard from the `16K kernel` term.
> 
> Your linux used a pagesize other than 4K?
> 
> 16K requires hacks to fake a 4K alignment, so libminecraftpe.so can be loaded.

yeah raspberry pi has decided to make 16K pagesize kernels the default on Pi5. A 4k kernel is also available (same one that pi3-4 use). The haven't publicized this at all because they think "not much software is affected".

**Comment by theofficialgman** [comment]
@ChristopherHX does this backtrace tell you anything (extracted appimage, determined what the LD_PRELOAD_PATH should be given the AppRun script, then executed in gdb)

```bash
(gdb) set environment LD_LIBRARY_PATH = /home/gman/.local/share/flatpak/exports/share/mcpelauncher/libs/native:/var/lib/flatpak/exports/share/mcpelauncher/libs/native:/usr/local/share/mcpelauncher/libs/native:/usr/share/mcpelauncher/libs/native:/tmp/mc/squashfs-root/usr/share/mcpelauncher/libs/native:/tmp/mc/squashfs-root/usr/lib:/tmp/mc/squashfs-root/usr/lib32
(gdb) show environment LD_LIBRARY_PATH
LD_LIBRARY_PATH = /home/gman/.local/share/flatpak/exports/share/mcpelauncher/libs/native:/var/lib/flatpak/exports/share/mcpelauncher/libs/native:/usr/local/share/mcpelauncher/libs/native:/usr/share/mcpelauncher/libs/native:/tmp/mc/squashfs-root/usr/share/mcpelauncher/libs/native:/tmp/mc/squashfs-root/usr/lib:/tmp/mc/squashfs-root/usr/lib32
(gdb) r
Starting program: /tmp/mc/squashfs-root/usr/bin/mcpelauncher-ui-qt 
/tmp/mc/squashfs-root/usr/bin/mcpelauncher-ui-qt: /tmp/mc/squashfs-root/usr/lib/libselinux.so.1: no version information available (required by /lib/aarch64-linux-gnu/libgio-2.0.so.0)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fe810eb00 (LWP 6436)]
WARNING: v3d support for hw version 71 is neither a complete nor a conformant OpenGL implementation. Testing use only.
[New Thread 0x7fd94eeb00 (LWP 6437)]

Thread 1 "mcpelauncher-ui" received signal SIGSEGV, Segmentation fault.
__GI___strlen_asimd () at ../sysdeps/aarch64/multiarch/strlen_asimd.S:195
195     ../sysdeps/aarch64/multiarch/strlen_asimd.S: No such file or directory.
(gdb) bt
#0  __GI___strlen_asimd () at ../sysdeps/aarch64/multiarch/strlen_asimd.S:195
#1  0x0000007ff6481e98 in QByteArray::QByteArray(char const*, int) () at /tmp/mc/squashfs-root/usr/lib/libQt5Core.so.5
#2  0x0000007fe78dc1c4 in  () at /tmp/mc/squashfs-root/usr/plugins/xcbglintegrations/libqxcb-egl-integration.so
#3  0x0000000000bc72f0 in  ()
```

**Comment by theofficialgman** [comment]
@ChristopherHX just to add some more context, the reason that we are using the appimages is because we support both armhf and arm64 across a variety of OSs. You don't produce any armhf debs

**Comment by bagong** [comment]
May I ask where to obtain arm64 debs? I'd like to try them on Rpi OS
Bookworm, and on Ubuntu 22.04 running on a (Rockchip RK3588) Orange Pi 5.
On both systems the debs aren't available through apt. Is there some public
ppa or a direct download?

**Comment by theofficialgman** [comment]
> May I ask where to obtain arm64 debs? I'd like to try them on Rpi OS Bookworm, and on Ubuntu 22.04 running on a (Rockchip RK3588) Orange Pi 5. On both systems the debs aren't available through apt. Is there some public ppa or a direct download?

@bagong 
the info page on adding the apt repo is here -> https://github.com/minecraft-linux/pkg . it is best to just add that repo and install using the documentation there

the debs are not directly downloadable through the web gui (unless you grab them from github actions artifact storage soon after they are built). if you want to manually download and install the debs you will have to use inherent knowledge of how a debian repo is structured and parse the Packages file for your intended dist
eg: bionic arm64 -> <https://minecraft-linux.github.io/pkg/deb/dists/bionic/main/binary-arm64/Packages>

**Comment by theofficialgman** [comment]
> It's probably easier for me to add armhf to the ppa instead of touching the AppImage with it's extreme complexity.

this would be my preference of the above choices ^

Of course it would be better if all users simply used an arm64 OS but this simply isn't the case. At least Raspberry Pi LTD just started recommending 64bit PiOS Bookworm as the default for Pi4 and Pi5 rather than 32bit PiOS for all hardware.

On another note, why do you even use QT webengine in the first place? I know it is for authentication purposes but wouldn't it have been easier to delegate that to the users default browser like other applications that require microsoft authentication tokens/keys/sessions ? I am not familiar with how that process works in this launcher so forgive my ignorance if that is not possible here for technical reasons.

**Comment by pigong** [comment]
@theofficialgman hi, this is bagong with another account. I have checked the debs and they work fine except for logging in. The bookworm deb works fine on Rpi4 64 bit. I could log into Google after multiple attempts (and ignoring security warnings), but I could not log into the MS account, and thus couldn't play on a remote server  (which is the major benefit of Bedrock, as you can play with console owners). Playing on local worlds works fine however, and is surprisingly snappy.

On Ubuntu Jammy (22.04, Orange Pi 5+, using the Joshua Riek image) it was less of a success. I could install the debs, but I couldn't log in anywhere. I then remembered that there is a flatpack which allows login for both Google and MS (it's UI version 0.12 rather than 0.11, maybe that is the reason). For some reason however this install was extremely slow while playing, while the olders were very snappy. The Orange Pi 5 has about twice the power of the RPI IV.

**Comment by theofficialgman** [comment]
> For some reason however this install was extremely slow while playing, while the olders were very snappy. The Orange Pi 5 has about twice the power of the RPI IV.

no, it was not "older builds" that were snappy. orange pi 5 has a non mesa supported gpu in it (valhall II mali gpu).
the "orange pi" distributions ship a fork of mesa called "panfork" that supports these valhall II mali gpus. 

For reasons I won't go into, the developer working on that is banned from mesa development. Use google to find out more info. Of course flatpak (which has its own integrated driverstack) does not use this cursed "panfork" mesa fork so you end up with software rendering

**Comment by pigong** [comment]
Thanks both of your for tips and explanations. Everything happens as you predicted:

- MS-login doesn't work on both installs, so I guess that means it's a MS problem (?)
- QT_QUICK_BACKEND=software instantly fixed Google login
- On the Ubuntu System using the deb's rather than flatpak brought the snappines/hardware support back.

```
export QT_QUICK_BACKEND=software
mcpelauncher-webview https://google.com test://exit
```

In my environment this did produce a browser Window, no weird error. There are Wayland warnings, but they're normal ;-)

Thanks for your help, both of you, much appreciated!

**Comment by theofficialgman** [comment]
> * Session crash on exit (This is not expected and doesn't happen in kde/x11)

does this happen in the x11 openbox based session? which session crashes (piOS wayfire session I assume)? what about kde wayland session?

> * armhf deb's now exists for debian (bookworm and oldstable), but not installable on Raspberry Pi OS / raspbian. Distro issue

I have gone ahead and created a bug report just now at raspbian via official methods for this issue https://bugs.launchpad.net/raspbian/+bug/2043742

> * Bookworm AppImage and deb cannot use qt6-webengine on 64k kernel

oh yeah sorry I should have warned you about that. it is due to too old chromium version used in qt5 and qt6 webengine before they were patched for larger pagesize support, see -> https://github.com/raspberrypi/bookworm-feedback/issues/107#issue-1955514281

>   * does chromium work on 16k? Because it crashed too, firefox works.

on Pi5 chromium does work on 4K and 16K kernels

**Comment by theofficialgman** [comment]
> * Bookworm AppImage and deb cannot use qt6-webengine on 64k kernel
>   
>   * does chromium work on 16k? Because it crashed too, firefox works.
>   * Fallback google login method can be used, xbox live has no fallback in the binary. Using a different page size works.

launcher login and xbox live login works fine in tested appimage on pi5 on 4K and 16K pagesize kernels
