### ISSUE TITLE
Musescore fails to run on RPi5

### ISSUE THREAD

**Issue by harmvuijk** [Botspot/pi-apps#2480]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

MuseScore installed fine but won´t run

### Description

I installed Musescore on my fresh RPi 5 via Pi-Apps, all seemed fine. However, after clicking Musescore in the menu, nothing happened. When entering "mscore" in the terminal, I get the following response:
```
/lib/aarch64-linux-gnu/libjack.so.0
/lib/aarch64-linux-gnu/libnss3.so
/tmp/.mount_mscorePCXgDk/bin/mscore4portable: error while loading shared libraries: libsndfile.so.1: ELF load command address/offset not page-aligned
```

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 11/12/2023
Latest Pi-Apps version: 11/12/2023
Kernel: aarch64 6.1.0-rpi6-rpi-2712
Device model: Raspberry Pi 5 Model B Rev 1.0
SOC identifier: bcm2712
Cpu name: Cortex-A76
Ram size: 8.04 GB
Raspberry Pi OS image version: 2023-10-10
```

**Comment by theofficialgman** [comment]
Given the wording of that error `libsndfile.so.1: ELF load command address/offset not page-aligned` I am pretty sure that is due to a 4K page aligned binary. RPi5 uses a 16K pagesize kernel by default and this requires that binaries be 16K or 64K page aligned.

Can you try enabling the 8K kernel by modifying the config.txt as written here and then rebooting -> https://github.com/raspberrypi/bookworm-feedback/issues/107#issuecomment-1773810662 ?

**Comment by harmvuijk** [comment]
Thanks a lot, that made Musescore run without problems. Now I have to find out how to get the cloud synchronisation running, but that's another issue.
