### ISSUE TITLE
Support all ARM Linux Distros

### ISSUE THREAD

**Issue by JustAnEric** [Botspot/pi-apps#2521]
### Cool ideas?

Well, I want to be a Linux tinkerer, but I certainly don't want my APT sources file to be deleted.
Why, just why. You have to scare your users like that when they're trying to be a Linux tinkerer upon install. My heart literally stopped beating when I installed Pi Apps and got that dialog, but it turns out it was all a lie.
:middle_finger: Thanks so much for my experience with Pi Apps on Kali Linux, best app I have ever used literally on the Raspberry Pi.

**Comment by Botspot** [comment]
Hey Eric, is this something you want to talk about, or vent and move on?

**Comment by JustAnEric** [comment]
Oh yeah, I forgot about the suggestion part, remove the part where it scares you to uninstall Pi Apps completely because it "ruins" your Linux installation upon installation of Pi Apps.

**Comment by JustAnEric** [comment]
Kali Linux is built on top of Debian too, I don't get why you can't support it.

**Comment by Botspot** [comment]
I cannot tell if you just want to argue, or help us work through a perceived problem. I will give you a chance.

> Well, I want to be a Linux tinkerer, but I certainly don't want my APT sources file to be deleted.

Pi-Apps does not delete default apt sources files. Not sure what you are talking about here.

> Why, just why. You have to scare your users like that when they're trying to be a Linux tinkerer upon install. My heart literally stopped beating when I installed Pi Apps and got that dialog, but it turns out it was all a lie.

Not exactly sure what you are referring to here either, but it sounds like pi-apps tried to add some useful commentary and repair instructions for a **pre-existing error** that occurs every time you run `sudo apt update`.
Could you run `sudo apt update` and paste its output here?

> Kali Linux is built on top of Debian too, I don't get why you can't support it.

For whatever reason, Kali is not maintained nearly as well as Debian. It is a rolling release, and we kept receiving so many error reports from package conflicts and other instabilities that we could not add support. None of the pi-apps devs use Kali, and we're all volunteers please remember. Pi-Apps used to be ONLY for Raspberry Pi OS 32-bit. Since then we've added full 64-bit support and added reasonably good general ARM support. The project is far more broad than my original dream, and maybe one day if we find an enthusiastic Kali user we could try supporting Kali again. But for now, there are basically two people keeping Pi-Apps running. Two. And neither of us make any money from it.

**Comment by theofficialgman** [comment]
> Kali Linux is built on top of Debian too, I don't get why you can't support it.

Yes it is but its built on top of debian testing (https://www.kali.org/docs/policy/kali-linux-relationship-with-debian/).
Debian testing is not intended for regular users. It is for developers to test integrating new packages, deprecating old ones, changing things around, and breaking things without risk of general users being affected. This, as Botspot said, happens very frequently.  Pi-Apps requires STABLE bases to target where over the life of the distro things don't randomly disappear, change, or break without warning. Debian testing is designed to randomly change, disappear, and break without warning, that is its purpose.

Meanwhile on a STABLE base (debian bookworm/bullseye, and ubuntu jammy/focal) we are assured that things will not change over the live of the distro, only bugfixes and security patches are applied that do NOT affect the compatibility with other software.

**Comment by theofficialgman** [comment]
> Oh yeah, I forgot about the suggestion part, remove the part where it scares you to uninstall Pi Apps completely because it "ruins" your Linux installation upon installation of Pi Apps.

This isn't a fear tactic. It also does not tell you that it "ruins" your Linux installation. It is simply a prompt to inform users that their system is unsupported by the pi-apps developers/maintainers before they even attempt to install any software. This was added at the suggestion of another user https://github.com/Botspot/pi-apps/issues/2512#issuecomment-1878778625 since it provides a better user experience to tell the user immediately that their system is unsupported (for whatever reason listed) and to expect some applications to fail (in a GUI prompt that happens once on first launch) rather than only tell them that their system is unsupported when attempting to install an application (only in the terminal) and after installation failures (in the terminal and a GUI prompt).

Additionally, you have yet to inform us as to which unsupported error message you received. You can run the following in terminal and paste it here:
```bash
~/api is_supported_system
```

**Comment by JustAnEric** [comment]
@Botspot It had some error message like "Congratulations linux tinkerer! You officially and successfully broke your system. /etc/apt/sources.list has been successfully been overwritten to not work."

**Comment by theofficialgman** [comment]
@JustAnEric read my post and run the command and send the output here

**Comment by JustAnEric** [comment]
@theofficialgman Output:
```
Congratulations, Linux tinkerer, you broke your system. You have removed ALL debian sources from your system.
All apt based application installs will fail. Unless you have a backup of your /etc/apt/sources.list /etc/apt/sources.list.d you will need to reinstall your OS.
```
It is pretty clear that part is the part that scared me now.

**Comment by theofficialgman** [comment]
Hmm yeah the error message we throw isn't actually correct in your case. It is just that your repos do not contain any of the hardcoded debian/Ubuntu (and select based distro).

I'll update that condition to produce the desired affect.

**Comment by theofficialgman** [comment]
@JustAnEric If you update pi-apps and run that command again you will see the error reported will be more relevant.

**Comment by JustAnEric** [comment]
Alright thank you.
