### ISSUE TITLE
Add WideVine support in Ubuntu through Pi-Apps

### ISSUE THREAD

**Issue by OlivierDoriath** [Botspot/pi-apps#2528]
Hello!
As things stand, installing Chromium through Pi-Apps on Ubuntu seems to install the Snap package. Adding the Raspberry Pi OS package for their branch of Chromium along with the libwidevinecdm0 package (and possibly other required packages) would allow for Ubuntu users to access DRM restricted content on their Raspberry Pi without using Raspberry Pi OS where Chromium has native WideVine support out of the box. It might also fix Better Chromium not working on Ubuntu.

**Comment by theofficialgman** [comment]
> Hello! As things stand, installing Chromium through Pi-Apps on Ubuntu seems to install the Snap package.

chromium from pi-apps installs the `chromium-browser` package through apt. On ubuntu they have made this a dummy package that implements a install script for their chromium snap package.

> Adding the Raspberry Pi OS package for their branch of Chromium along with the libwidevinecdm0 package (and possibly other required packages) would allow for Ubuntu users to access DRM restricted content on their Raspberry Pi without using Raspberry Pi OS where Chromium has native WideVine support out of the box.

its not so simple. there are a few ways that widevine can be patched. See the commit message here for more info -> https://github.com/theofficialgman/l4t-debs/commit/09c7234202a29b5803f68f456ab9503600aa4722 . I am not sure which way piOS decided to patch their widevine.

Snap chromium actually already checks for Widevine on all architectures thanks to my request -> https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/2008433 . If you place a compatible Widevine (such as my patched version for all distros that use GLIBC 2.36+ out of the box https://github.com/theofficialgman/testing/releases/download/gmans-releases/WidevineCdm-2.36.tar.gz, just extract to the proper directory) then it will load and be used.

**Comment by OlivierDoriath** [comment]
Hey!

Thank you for the swift reply!

I tried doing just that (extracted the archive to $HOME/.local/lib/ and reopened Chromium (Version 120.0.6099.199 (Official Build) snap (64-bit)) but the issue persists.

Am I missing something?

**Comment by theofficialgman** [comment]
> I tried doing just that (extracted the archive to $HOME/.local/lib/ and reopened Chromium (Version 120.0.6099.199 (Official Build) snap (64-bit))) but the issue persists.

chromium snap uses core22 https://git.launchpad.net/~chromium-team/chromium-browser/+git/snap-from-source/tree/snapcraft.yaml (a snap dependency core based on Ubuntu Jammy 22.04) and thus does not have a new enough GLIBC version to run this Widevine. Ubuntu might bump their chromium snap to core24 when that releases alongside Ubuntu 24.04 in March. For now there is no way to use chromium snap with any version of available ARM64 Widevine.

**Comment by OlivierDoriath** [comment]
That's unfortunate, but thanks again for your answers!

**Comment by theofficialgman** [comment]
And before you ask, chromium flatpak is in a similar boat. It uses freedesktop-sdk 22.08 which only has GLIBC 2.35 https://github.com/flathub/org.chromium.Chromium/blob/75de766ecf8bea72d0570ad3261e5bc0b93da958/org.chromium.Chromium.yaml#L6C16-L6C21 . It needs to use 23.08 or newer in order to have a high enough GLIBC version to be compatible with Widevine ARM64. chromium flatpak is prepared for loading ARM64 widevine as well once that happens thanks again to my suggestion https://github.com/flathub/org.chromium.Chromium/pull/321

**Comment by theofficialgman** [comment]
Incase you are interested in following the flatpak progress, someone else already asked for the move to 23.08 freedesktop SDK and I have shown my interest there as well https://github.com/flathub/org.chromium.Chromium/issues/344#issuecomment-1892806285

**Comment by OlivierDoriath** [comment]
Thanks! It almost feels silly that this isn't working yet (although I understand the reason behind it). I commented in favor of moving as well.

**Comment by theofficialgman** [comment]
Sure yeah. Things just take time. We are lucky that google eventually rolled out chromeOS ARM64 userspace otherwise we would be suck still with ARMhf only Widevine support.

Just to show that my patched Widevine works (incase there was doubt), here is it running on my Pi5 on Ubuntu 23.10 with my chromium built from source. It isn't something I want to distribute as this is chromium built from source for Nvidia Jetson R32 (Nintendo Switch) with customizations in chromium source for HW accelerated video decoding.

![Screenshot from 2024-01-15 17-36-47](https://github.com/Botspot/pi-apps/assets/28281419/da2ef37f-bf45-4054-8eb8-c685805c875e)

**Comment by theofficialgman** [comment]
and here is raspberry pi chromium sourced from https://archive.raspberrypi.org/debian/pool/main/c/chromium-browser/
![image](https://github.com/Botspot/pi-apps/assets/28281419/904a6447-8a4a-4b6f-8776-4b491122d2f6) with my patched Widevine added (didn't try the raspberrypi packaged widevine because I already had mine downloaded and known working.

**Comment by theofficialgman** [comment]
@OlivierDoriath see PR https://github.com/Botspot/pi-apps/pull/2529 which does the following:

> Adding the Raspberry Pi OS package for their branch of Chromium along with the libwidevinecdm0 package (and possibly other required packages) would allow for Ubuntu users to access DRM restricted content on their Raspberry Pi without using Raspberry Pi OS where Chromium has native WideVine support out of the box. It might also fix Better Chromium not working on Ubuntu.

You can import and test the PR by going to pi-apps settings, clicking import app, and then importing the new Better Chromium by putting in the PR number `2529`. Then simply install Better Chromium and click "I know what I am doing" when installing the app (since the app will no longer match the version in the main pi-apps repo). If you test it out, you should avoid updating Better Chromium in pi-apps until this PR has merged.

**Comment by OlivierDoriath** [comment]
You went from "It's complicated" to "It's done" in less than a day. Just like that huh?  It seems to be working on my end, thank you so much! (Although I now have two Chromiums installed, and installing Better Chromium checks for Chromium being installed. I don't know if that's intended?)

I'll run some tests and get back to you.

Thanks again, I bet your coworkers must really appreciate you!

**Comment by OlivierDoriath** [comment]
Tested with NetFlix (that's all I have on hand) and it seems to work flawlessly!

**Comment by theofficialgman** [comment]
> You went from "It's complicated" to "It's done" in less than a day. Just like that huh? It seems to be working on my end, thank you so much! (Although I now have two Chromiums installed, and installing Better Chromium checks for Chromium being installed. I don't know if that's intended?)

the actual snap chromium does not get removed as part of this change. thats why you see "two" chromiums. You can remove the snap one manually (at least for now) with `sudo snap remove chromium`

Do take note of a known issue https://github.com/Botspot/pi-apps/pull/2529#issuecomment-1892908703 . I have not decided if we will setup a mirror of the raspberry pi repo for chromium/widevine or simply modify our `is_supported_system` function so it doesn't show this configuration as a frankendebian

**Comment by theofficialgman** [comment]
> You went from "It's complicated" to "It's done" in less than a day. Just like that huh? It seems to be working on my end, thank you so much! (Although I now have two Chromiums installed, and installing Better Chromium checks for Chromium being installed. I don't know if that's intended?)
> 
> I'll run some tests and get back to you.
> 
> Thanks again, I bet your coworkers must really appreciate you!

@Botspot thoughts on that? It is not an ideal setup for ubuntu chromium-browser. ubuntu chromium-browser deb installs the snap on install but does not remove the snap on uninstall (thats how they have it setup). So in order for the user to install Better Chromium they first must install the chromium-browser package from ubuntu (that installs the snap) and then install Better Chromium (that switches to the piOS deb) while leaving the snap installed.

I would like to make it so that (at least on ubuntu) Better Chromium can install the `chromium-browser` package (if available) and also add a userinput prompt to ask if the user would like to uninstall the snap (after installing the piOS chromium-browser deb). Do you have any objections or thoughts on that?

**Comment by Botspot** [comment]
> I would like to make it so that (at least on ubuntu) Better Chromium can install the `chromium-browser` package (if available) and also add a userinput prompt to ask if the user would like to uninstall the snap (after installing the piOS chromium-browser deb). Do you have any objections or thoughts on that?

Installing a new chromium package is beyond my original intended scope for Better Chromium, but I do not oppose it as it makes the most sense. Upon installing Better Chromium, I as a Pi user would want to see a dialog with the following information and 2 options:
"The PiOS chromium browser is faster and supports widevine. Install it?"
1. yes, uninstall snap chromium, move my config over, and install rpi chromium
2. no, leave my snap chromium untouched and hide the widevine option

If the user chooses option 1 and later uninstalls Better Chromium, I would likely leave rpi chromium-browser package untouched, but make a note of this decision in the terminal output when uninstalling. (something like "you switched to the rpi chromium build. If you want to use the snap version, here's commands to do that and move your config back over")

**Comment by theofficialgman** [comment]
@OlivierDoriath we decided to use a different apt repo in the final version. Please run the following commands and then update to the latest pi-apps version of better chromium
```bash
~/pi-apps/api rm_external_repo "raspberrypi" force
sudo rm -f /etc/apt/preferences.d/chromium
```

**Comment by OlivierDoriath** [comment]
> @OlivierDoriath we decided to use a different apt repo in the final version. Please run the following commands and then update to the latest pi-apps version of better chromium
> 
> ```shell
> ~/pi-apps/api rm_external_repo "raspberrypi" force
> sudo rm -f /etc/apt/preferences.d/chromium
> ```

Thanks for the update! Sorry I was busy for the past few days!

**Comment by RozbehSharahi** [comment]
@theofficialgman Wow, bravo !

Thanks a lot, due to better-chromium i could now configure my fathers rasp pi 5 to have amazon prime working. Thank you so much ! Donation will be done tomorrow. 

Its really great what you are doing here !
