### ISSUE TITLE
Pi-Apps Franken Debian

### ISSUE THREAD

**Issue by BreiteGu** [Botspot/pi-apps#2535]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Broken OS after Pi-Apps update

### Description

I am total new to github ...
I was using Pi-Apps for a while with little to no issues.
I am talking about a HL, Pi 3B+, Bullseye (32)
Recently the Sys demanded an Pi-Apps update ...
which never goes through but ends with: "You have successfully created an Franken-Debian" System
After this most of my Installations wont work again
and I am left with restoring the system from an img file.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Raspbian GNU/Linux 11 (bullseye)
OS architecture: 32-bit
Last updated Pi-Apps on: 08/10/2022
Latest Pi-Apps version: 01/21/2024
Kernel: armv7l 6.1.21-v7+
Device model: Raspberry Pi 3 Model B Rev 1.2
Cpu name: Cortex-A53
Ram size: .92 GB
Raspberry Pi OS image version: 2022-04-04
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
at present I refrain from reproducing this again, once more
```

**Comment by theofficialgman** [comment]
Sorry this isn't a pi-apps bug. The error that pi-apps gives you is true and only triggers if you have added debian/ubuntu sources from multiple different dists (eg: some sources from buster with others from bullseye). Pi-Apps does this to let you know that you have broken your system and should undo the changes that you did. Otherwise the best solution is to install from a fresh image if you do not remember what you did.

fyi, you can run `~/pi-apps/api is_supported_system` again to show what specific repo you need to fix.
