### ISSUE TITLE
Steam dependency install issue

### ISSUE THREAD

**Issue by Im-CatDev** [Botspot/pi-apps#2556]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Steam can't install dependecies

### Description

When i try to launch steam from my desktop, a terminal window asking to download additional packages, when i press enter, a bunch of errors are being thrown. Logs below

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 02/29/2024
Latest Pi-Apps version: 02/29/2024
Kernel: aarch64 6.1.0-rpi8-rpi-v8
Device model: Raspberry Pi 5 Model B Rev 1.0
SOC identifier: bcm2712
Cpu name: Cortex-A76
Ram size: 7.94 GB
Raspberry Pi OS image version: 2023-12-05
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
Steam needs to install these additional packages:
libc6:arm64 libc6:i386 libegl1:arm64 libgbm1:arm64 libgl1-mesa-dri:arm64 libgl1-mesa-dri:i386 libgl1:arm64 libgl1:i386 steam-libs-amd64:amd64 steam-libs-i386:i386 xterm

Press return to proceed with the installation: 
.............
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libc6:i386 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libc6-dev libnss-nis libnss-nisplus libcrypt1 libc6-dev:armhf libnss-nis:armhf libnss-nisplus:armhf libcrypt1:armhf

Package libgl1:i386 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libgl1-mesa-dri:i386 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libc6:i386' has no installation candidate
E: Package 'libgl1-mesa-dri:i386' has no installation candidate
E: Package 'libgl1:i386' has no installation candidate

Press return to continue:
```

**Comment by theofficialgman** [comment]
> When i try to launch steam from my desktop

delete the steam file from your desktop and then reboot. afterwards it should launch without errors

you neglected to follow the warning displayed "YOU NEED TO REBOOT before starting steam. This is because Steam is the first application on your system to be installed into the /usr/local folder." since you did not have a /usr/local folder prior to installing steam

**Comment by Im-CatDev** [comment]
> > When i try to launch steam from my desktop
> 
> delete the steam file from your desktop and then reboot. afterwards it should launch without errors
> 
> you neglected to follow the warning displayed "YOU NEED TO REBOOT before starting steam. This is because Steam is the first application on your system to be installed into the /usr/local folder." since you did not have a /usr/local folder prior to installing steam

I rebooted as the console told me to, but no one said to delete the desktop file

**Comment by Botspot** [comment]
This situation confuses me.
Installing steam should not leave behind a launcher on the Desktop. Such a file is explicitly removed by pi-apps at the end of installation:
```bash
rm -f $HOME/Desktop/steam.desktop
```
what I don't understand is: How was the steam.desktop file still there after a reboot?

**Comment by Im-CatDev** [comment]
> This situation confuses me. Installing steam should not leave behind a launcher on the Desktop. Such a file is explicitly removed by pi-apps at the end of installation:
> 
> ```shell
> rm -f $HOME/Desktop/steam.desktop
> ```
> 
> what I don't understand is: How was the steam.desktop file still there after a reboot?

Sorry, I made a mistake, I meant I tried to start it from the taskbar thing

**Comment by theofficialgman** [comment]
> This situation confuses me. Installing steam should not leave behind a launcher on the Desktop. Such a file is explicitly removed by pi-apps at the end of installation:
> 
> ```shell
> rm -f $HOME/Desktop/steam.desktop
> ```
> 
> what I don't understand is: How was the steam.desktop file still there after a reboot?

installation of the steam deb installs a .desktop file in `/usr/share/applications/steam.desktop`. Running steam copies that .desktop file to `~/Desktop/steam.desktop`. unfortunately, both of these files hardcode the location of the steam binary `Exec=/usr/bin/steam`. If the user DOES NOT HAVE .desktop files existing in `/usr/local/share/applications` at the time of DE LOGIN, then that directory NEVER gets searched for new .desktop files. That is why the reboot is critical for users where this is the first application in `/usr/local/share/applications`. 

IF they do NOT reboot, then launching steam through the applications menu, then it will run `/usr/share/applications/steam.desktop` which calls `/usr/bin/steam` which will result in the errors posted in the first message here. Additionally, it will also copy that .desktop file to `~/Desktop/steam.desktop`. Now if the user reboots it doesn't matter that `/usr/local/share/applications` is searched, because  `~/Desktop` has priority over all other locations. So they will NEVER get our custom steam.desktop file in `/usr/local/share/applications` unless they manually delete the one on their desktop. This is why its critical to read and follow directions.

**Comment by theofficialgman** [comment]
I have already explained this before multiple times. As mentioned, the best way to workaround how DEs search the XDG paths based on what is available at login is to use dpkg-divert as described here https://github.com/Botspot/pi-apps/pull/2555#issuecomment-1967945903

**Comment by Im-CatDev** [comment]
I will update you when something changes, at the moment my pi broke :( so it may take a while
