### ISSUE TITLE
raspian trixie is supported despite some packages being broken

### ISSUE THREAD

**Issue by gitmanbloggus** [Botspot/pi-apps#2562]
### Cool ideas?

remove the warning if trixie is detected since from what apps are broken, balena, obs are broken (from what I tested)
other then those 2 everything works as expected + I get gcc 13

**Comment by theofficialgman** [comment]
> raspian trixie is supported despite some packages being broken

supported is something that the developers decide. We have decided to support only the latest 2 LTS distros of debian and ubuntu. So that means Debian Bullseye, Debian Bookworm, Ubuntu Focal, and Ubuntu Jammy.

> remove the warning if trixie is detected since from what apps are broken, balena, obs are broken (from what I tested)
> other then those 2 everything works as expected + I get gcc 13

when we say supported we mean:
- this system is tested and all applications in the store function on it
- we will fix issues and provide support for such systems

we have no intention of supported debian trixie (the current debian testing) and debian unstable as these are moving targets that we cannot support based on the above definition. we need stable unchanging OSs to support for many applications, such as OBS which you listed.

OBS is built for each supported system individually and takes a lot of time investment to do so.

balena etcher continues to be unmaintained by the developers and the issue you run into has been reported for nearly a year now https://github.com/balena-io/etcher/issues/4096

**Comment by gitmanbloggus** [comment]
well its fine... they are kind of pointless anyways
