### ISSUE TITLE
Reddit Install based app

### ISSUE THREAD

**Issue by solitary8** [Botspot/pi-apps#2613]
### What is the name of the app?

Reddit Desktop

### Where is the app hosted?

https://github.com/solitary8/Reddit

### About the app

Reddit but on Desktop using electron to run it as if it were a desktop app,there are some errors while running the app in the terminal but they don't seem to affect the running of the app 

### Upload file or Add PR Link

[Reddit_Desktop.zip](https://github.com/user-attachments/files/15966084/Reddit_Desktop.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have read and followed the [creating an app for Pi-Apps documentation](https://pi-apps.io/wiki/development/Creating-an-app/).
- [X] I have confirmed that this app can run on all [Pi-Apps supported systems](https://pi-apps.io/install/).

**Comment by solitary8** [comment]
don't hesitate to ask for the errors that I get while running the app

**Comment by solitary8** [comment]
I have already done the install and uninstall script using the pi-apps wizard this is just some of the files that are on the github page,I have also added an icon in the apps list in the pi-apps create an app install script and it works

**Comment by Botspot** [comment]
Where are the install and uninstall scripts? All I see in your zip file is a `reddit_setup.sh` and a `run.sh` script, neither of which Pi-Apps has any idea what to do with.
Furthermore, we do not allow app install scripts to use `apt-get` directly - they have to use `install_packages` instead.

Please read our documentation. https://pi-apps.io/wiki/development/Creating-an-app/

**Comment by solitary8** [comment]
I'm sorry as I said these are for people that want to install it from github,
I have done the same setup script and done a uninstall script for the app I will upload it shortly

**Comment by Botspot** [comment]
We also generally don't want to add any website-as-an-app because that would flood Pi-Apps.
Anybody with a web browser can create a desktop version of their favorite websites with a few clicks. We also have the "Web Apps" tool on Pi-Apps, which helps simplify that process further.

I see no advantage to using your approach of launching reddit.com - only drawbacks. Electron needs frequent updating, and it also has numerous [bad versions](https://github.com/Botspot/pi-apps/issues/1930) that need to be avoided.

Unless you can explain how your electron-based way of launching reddit.com is truly better than chromium or the Web Apps tool, I'm ready to close this issue.

**Comment by theofficialgman** [comment]
fine to close by me
some more reading for @solitary8 if they are interested more about our decision process:
https://github.com/Botspot/pi-apps/issues/1791
https://github.com/Botspot/pi-apps/pull/2333

**Comment by solitary8** [comment]
Great thanks for the additional info
