### ISSUE TITLE
switch to depending on `chromium` instead of `chromium-browser` in Better Chromium on supported OSs

### ISSUE THREAD

**Issue by ghost** [Botspot/pi-apps#2644]
### Cool ideas?

As RPI has switched to the Debian's Chromium package (instead of its own chromium-browser package), some functions in "better chromium" are probably no longer needed. And also maybe, other functions may require some edits to be usable in the Debian's Chromium. I used to install this to get "sync" functionality but it turns out, Debian Chromium now allows sync out of the box.

You might want to look into it.

**Comment by theofficialgman** [comment]
> As RPI has switched to the Debian's Chromium package (instead of its own chromium-browser package)

Please provide evidence of this occurring @sudo-splinter-cell . RPI `chromium-browser` package was just updated 10 hours ago and is not using debian's `chromium` package.

**Comment by Botspot** [comment]
> They are not using debian's official chromium package but have instead switched to using debian's `chromium` naming scheme and buildscripts (instead of using ubuntu's buildscripts forward ported from the time before the snap transition years ago). No immediate changes are necessary since installing `chromium-browser` will now install `chromium` via the `Depends: chromium`

I do want to mention that on my PiOS install, the `chromium-browser` package is removed during upgrade. It does not stay installed as a dummy transitional package.
```
pi@raspberrypi:~ $ sudo apt upgrade --autoremove
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be REMOVED:
  chromium-browser chromium-browser-l10n
The following NEW packages will be installed:
  chromium chromium-common chromium-l10n chromium-sandbox libc++1-16
  libc++abi1-16 libunwind-16 libupower-glib3 libwidevinecdm0
  notification-daemon upower
The following packages will be upgraded:
  box64-generic-arm python3-gpiozero raspberrypi-sys-mods raspi-utils
  raspi-utils-core raspi-utils-dt raspi-utils-eeprom raspi-utils-otp raspinfo
  rc-gui rpi-chromium-mods rpi-eeprom
12 upgraded, 11 newly installed, 2 to remove and 0 not upgraded.
```

**Comment by theofficialgman** [comment]
`chromium-browser` is still provided by `chromium` (see my message) so the autoremoval of the physical `chromium-browser` package should be of no consequence.

**Comment by sudo-splinter-cell** [comment]
As I have been told in the RPI forum, The Chromium package is the same with the Debian one, so instead of a different RPI maintained chromium package, RPI modifications are added to the default package with another package which is probly called "rpi-chromium-mods".

I have been using this new Chromium without the "better chromium" package and it really is good enough imo. Sync works out of the box. DRM content plays fine (widevine was installed). Twitter videos start laggy but it can be resolved by disabling "hw acceleration" in settings. On a RPI5, i found through experience that disabling hw acceleration for pretty much anything in any app makes the experience so much better (Kodi for example). I am on X11 (refusing wayland still).

**Comment by theofficialgman** [comment]
> As I have been told in the RPI forum, The Chromium package is the same with the Debian one, so instead of a different RPI maintained chromium package, RPI modifications are added to the default package with another package which is probly called "rpi-chromium-mods".

Whoever is talking to you in the forum has no idea what they are talking about. raspberry pi `chromium` (same as with the previous `chromium-browser`) includes 1000s of lines of patchfiles modifying the source code of chromium itself. the changes are NOT limited to the small things in `rpi-chromium-mods`. As I said (I know what I'm talking about) the only difference is that they are now starting with the debian `chromium` dsc as a base instead of the old ubuntu `chromium-browser` dsc as a base. Very very little has changed.
![image](https://github.com/user-attachments/assets/c6a5ce3d-c837-4b99-bf03-d84913b09daf)
https://archive.raspberrypi.com/debian/pool/main/c/chromium/chromium_128.0.6613.119-1~deb12u1+rpt5.debian.tar.xz

**Comment by sudo-splinter-cell** [comment]
Well it is quite possible that i have been misled as i am not a programmer. But it is obvious to me that there is a major change here and i just wanted to give you a heads up to prevent anything to be broken for the people who actually use better-chromium (like me, it was one of the first things i installed). And i am surprised that Chromium now offers sync without it. So maybe it is more than just a name change. I don't know.

**Comment by theofficialgman** [comment]
> But it is obvious to me that there is a major change here and i just wanted to give you a heads up to prevent anything to be broken for the people who actually use better-chromium (like me, it was one of the first things i installed). And i am surprised that Chromium now offers sync without it. So maybe it is more than just a name change. I don't know.

There is no major change. I already explained the changes. Debian's dsc (`debian/etc/apikeys` in the debian tarfile) has had keys for google sync for many years now (but not ubuntu's dsc since it is so old). So changing over to their dsc as a base simply brought that change with it.

**Comment by theofficialgman** [comment]
We can simplify it but nothing urgent.

**Comment by sudo-splinter-cell** [comment]
Yeah i have been experimenting with installing it on and off and i guess it is still required and working at least for "sync" functionality. When i installed and then removed better chromium, sync was gone. Then i have to install it again. So i guess it is better to have it installed than not.

**Comment by sudo-splinter-cell** [comment]
I think i spoke a little bit too early about this. The new Chromium has no hw acceleration under X11 (they told me). And i tought hw acceleration was only for video playback but it turns out, it wasn't. Google Earth/Maps do not work in 3d without it. And the performance really slumps. Now basically we are forced to use wayland to have it, but i personally don't want to. Could there be any way to reimplement hw acceleration to the new Chromium (under x11) with a new "better chromium" script?

**Comment by Botspot** [comment]
@sudo-splinter-cell this is not something I have the interest/time to investigate. My suggestions for you:

1. Try Downgrade Chromium
2. With rpi-chromium-mods uninstalled, try command-line arguments when running chromium to see if an older version works with the KMS driver that helped with acceleration on the pure X11 distro back in the day.
3. Once you figure that out, it may work in the latest Chromium.

**Comment by theofficialgman** [comment]
> The new Chromium has no hw acceleration under X11 (they told me this will be the case now.).

@sudo-splinter-cell please provide a link to a public statement from someone representing RPI LTD chromium developement stating that (if they aren't employed by RPI LTD, I don't want to hear it)

**Comment by Botspot** [comment]
> rpi-chromium-mods is a dependency. Removing it solely will probably require some skills and it will come back with every update

No and false.
```
pi@raspberrypi:~ $ sudo apt purge rpi-chromium-mods
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  rpi-chromium-mods*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 18.4 kB disk space will be freed.
Do you want to continue? [Y/n]
```
The `rpi-chromium-mods` package has always been removable leaving Chromium intact.
Also as you seem interested in the subject, try seeing what files rpi-chromium-mods actually installs. It's not as significant as most people think.
```
$ dpkg -L rpi-chromium-mods
/.
/etc
/etc/chromium
/etc/chromium/master_preferences
/etc/chromium.d
/etc/chromium.d/00-rpi-vars
/usr
/usr/share
/usr/share/doc
/usr/share/doc/rpi-chromium-mods
/usr/share/doc/rpi-chromium-mods/changelog.gz
/usr/share/doc/rpi-chromium-mods/copyrigh
```

**Comment by sudo-splinter-cell** [comment]
Yeah i thought if a package is being installed with another app it is a dependency, anyway it turns out, my problems are deeper with the new chromium, even if i switch to wayland, hardware acceleration causes more issues probably due to the fact that i am using KDE Plasma (kwin). So yeah, i guess my issues stem from the fact that i am using a different desktop environment.

**Comment by glanduin** [comment]
(HW acceleration in x11)

Fixed:

[https://forums.raspberrypi.com/viewtopic.php?t=376584#p2253409](url)

**Comment by theofficialgman** [comment]
Yes this was already posted by upstream piOS devs https://github.com/RPi-Distro/chromium/issues/47#issuecomment-2352705411

they will investigate and fix their patch that isn't working anymore. no changes in pi-apps needed.
