### ISSUE TITLE
Update Monero GUI wallet to the latest version, Monero GUI 0.18.3.4?

### ISSUE THREAD

**Issue by SoulReaver-SS** [Botspot/pi-apps#2651]
Update would be much appreciated.
Thnx.

**Comment by SoulReaver-SS** [comment]
> Monero GUI actually already builds from the latest git master branch in pi-apps. So if you were to install today you would have the latest version already.
> 
> This is actually against pi-apps current design philosophy where we only build against tags and have our auto-updater only update that tag when there is a new version and when that new version can build successfully on all supported systems.
> 
> Once our CI has finished validating that Monero GUI can built successfully on all supported systems on the latest tagged release I will transition the application to using our current design philosophy.

Sounds like I just need to wait. Thnx.

**Comment by theofficialgman** [comment]
@Botspot requesting your assistance on this one due to 32bit build failures. The specific error should have been fixed with https://github.com/Botspot/pi-apps/commit/aeb34676edb3c953e6db59a3bd5009143624bf61 but that hasn't worked probably due to https://github.com/Botspot/pi-apps/actions/runs/11131702617/job/30933876253#step:3:1852

It also seems that the P2Pool feature won't work (on arm32 or arm64) due to the hardcoded download of x64 libraries as part of the the source code
https://github.com/monero-project/monero-gui/blob/master/src/p2pool/P2PoolManager.cpp there are aarch64 linux libraries but these aren't setup for use in the source of monero gui.

I don't really have any experience or interest in this application (or mining/crypto) so won't be working on it further myself.

**Comment by theofficialgman** [comment]
Closing this as it is resolved for ARM64 and ARM32 support has been disabled. For anyone that wants to have ARM32 added back please resolve the above build failures ^.
