### ISSUE TITLE
OrcaSlicer Build

### ISSUE THREAD

**Issue by AnotherSamWithADream** [Botspot/pi-apps#2660]
### What is the name of the app?

OrcaSlicer

### Where is the app hosted?

Must be built for the Raspberry Pi. Source code is available on GitHub. 

### About the app

The app is a 3D printer G-Code slicer program. I know @Botspot was asking about a build for it, and I finally found a viable build method that works _and_ it doesn't have the problem with the webview. You can build OrcaSlicer through the docker build method. Look at this pull request: [OrcaSlicer Pull Request 6552](https://github.com/SoftFever/OrcaSlicer/pull/6552). If you look at the README from my fork and the pull request there are build instructions. If there are any more questions, you can just reply to the issue (of course).

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
I don't see how the linked PR changes anything. It is simply a docker container of Ubuntu 22.04. A container like that is way way too much overhead (in terms of storage) for any single application except if you want a reproducible build for use in development on any machine.

Please contribute to one of the accepted desktop software distribution models (eg: appimage, flatpak, deb). Note that whichever one is chosen will need to be able to run on all our supported systems https://pi-apps.io/install/#supported-systems: (which is why for complex software that might need newer dependencies than available in all our supported distros flatpak is usually the easiest choice).
