### ISSUE TITLE
Thonny installer

### ISSUE THREAD

**Issue by justaPancakeGuy** [Botspot/pi-apps#2661]
### What is the name of the app?

Thonny

### Where is the app hosted?

https://github.com/thonny/thonny

### About the app

Just an apt package app that installs thonny ide

### Upload file or Add PR Link

[Thonny.zip](https://github.com/user-attachments/files/17352594/Thonny.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have read and followed the [creating an app for Pi-Apps documentation](https://pi-apps.io/wiki/development/Creating-an-app/).
- [X] I have confirmed that this app can run on all [Pi-Apps supported systems](https://pi-apps.io/install/).

**Comment by Botspot** [comment]
Pi-Apps is best suited for helping people install hard-to-install apps. For Thonny, it may be preinstalled, but even if it is not, it comes ready-to-install in the Raspberry Pi "Recommended Software" program.
Why should Thonny be added to Pi-Apps?

![20241012_16h33m25s_grim](https://github.com/user-attachments/assets/4c69ff91-e36a-4977-a457-e609f5c6630f)

**Comment by theofficialgman** [comment]
@justaPancakeGuy zip is empty

@Botspot are you aware of how these users continue to create empty zips? is it a bug with the createapp script or some pre-installed software these users are using?

**Comment by Botspot** [comment]
This keeps happening because users right-click on the app folder, click Compress, and expect all subfiles to be in the zip. For whatever reason Xarchiver only compresses the folder name and ignores the contents.. Createapp does not create a zip. Maybe if it did, the situation could be better.

**Comment by theofficialgman** [comment]
> This keeps happening because users right-click on the app folder, click Compress, and expect all subfiles to be in the zip. For whatever reason Xarchiver only compresses the folder name and ignores the contents.

Is that already reported as a usability bug with Xarchiver? Obviously even if it was it wouldn't get fixed before an major version release of the OS. Maybe someone should open an issue at Rpi Bookworm asking that they ship a new default program since its not working the way users expect.

> Createapp does not create a zip. Maybe if it did, the situation could be better.

Yes I realized that after posting. I think that functionality should be added or add a warning about using Xarchiver (ie: how to use it properly if they do use that software).

**Comment by justaPancakeGuy** [comment]
Sorry about the zip thing it's fixed now I should've checked it

**Comment by justaPancakeGuy** [comment]
> Pi-Apps is best suited for helping people install hard-to-install apps. For Thonny, it may be preinstalled, but even if it is not, it comes ready-to-install in the Raspberry Pi "Recommended Software" program.
> 
> Why should Thonny be added to Pi-Apps?
> 
> 
> 
> ![20241012_16h33m25s_grim](https://github.com/user-attachments/assets/4c69ff91-e36a-4977-a457-e609f5c6630f)
> 
> 

Pi apps supports Ubuntu right?

**Comment by theofficialgman** [comment]
> Pi apps supports Ubuntu right?

Yes https://pi-apps.io/install/#supported-systems:

@Botspot I personally have no issue with adding Thonny since it seems to fit well within our existing guideline (eg: there are other python IDEs existing in pi-apps such as mu, pycharm ce, sublime text, vscode, etc). Thonny existing in "Recommended Software" really isn't relevant here and that has never prevented other similar applications from being added (eg: Scratch 3, VSCode, libreoffice, etc).

**Comment by theofficialgman** [comment]
> ```
> Thonny is a free, open-source Python IDE made with beginners in mind.
> ```
Using the official and full debian description would be better than whatever you found/came up with.

```
Thonny is a simple Python IDE with features useful for learning programming.

It comes with a debugger which is able to visualize all the conceptual steps
taken to run a Python program (executing statements, evaluating expressions,
maintaining the call stack). There is a GUI for installing 3rd party packages
and special mode for learning about references.
```

**Comment by justaPancakeGuy** [comment]
@theofficialgman yeah your probably right it was a little short i updated the zip file

**Comment by Botspot** [comment]
Added!
