### ISSUE TITLE
Audacious with Winamp Skins - Window Dragging Issue on Wayfire

### ISSUE THREAD

**Issue by adrianl85** [Botspot/pi-apps#2691]
### Suggestion

Description of the Issue:
I am encountering an issue with Audacious when using Winamp skins. The problem is specific to the Debian package version of Audacious on Raspberry Pi OS Bookworm running the Wayfire desktop environment. With Winamp skins enabled, the windows of Audacious become fixed in position on the desktop. They cannot be dragged or moved in the usual way using the mouse. The only way to reposition the windows is by holding down the Alt or Super key (depending on desktop configuration) while dragging.

Steps to Reproduce:

Install Audacious using the Debian package on Raspberry Pi OS Bookworm.
Switch to Wayfire as the desktop environment.
Enable the Winamp skin in Audacious.
Attempt to drag the Audacious window without using the Alt or Super key.
Expected Behavior:
The Audacious windows should be draggable and movable freely without needing to hold down any modifier keys.

Actual Behavior:
The windows are locked in place and can only be moved by holding the Alt or Super key.

Additional Information:

Using the Snap version of Audacious on Ubuntu for Raspberry Pi 5 does not exhibit this issue. The windows with Winamp skins are draggable as expected in that setup.
This behavior seems tied to the Debian package of Audacious in combination with Wayfire on Raspberry Pi OS Bookworm.
Environment Details:

Operating System: Raspberry Pi OS Bookworm
Desktop Environment: Wayfire
Audacious Version: Debian package version
Hardware: Raspberry Pi 5
Suggested Action:
Investigate whether this issue is specific to the combination of the Debian package of Audacious and the Wayfire window manager. If possible, check the window handling compatibility of the Winamp skins in this environment or provide a workaround.

Thank you for your attention to this issue.

Best regards,
Eddie

**Comment by Botspot** [comment]
>  Suggested Action: Investigate whether this issue is specific to the combination of the Debian package of Audacious and the Wayfire window manager. If possible, check the window handling compatibility of the Winamp skins in this environment or provide a workaround.

This is not our job. Go ask on the Raspberry Pi forums, or get support from winamp if you think the issue lies there. It may be an issue with Wayfire so you might want to try opening an issue there. Are you sure you are using Wayfire? In my experience the alt-dragging feature was not present on wayfire, but is present on LabWC. Go check which compositor you are running.
Closing this issue because I have no levers I can pull that you do not have access to. I cannot help you any better than you can help yourself. Now if a workaround was found that requires an update to the *Pi-Apps* script, then that would be something to open an issue here for, but otherwise this is the wrong place to get such support.
