### ISSUE TITLE
Unreal on RPi4

### ISSUE THREAD

**Issue by fabianmendes** [Botspot/pi-apps#284]
>Can this app run on RPi? If so, please provide a link to a tutorial if applicable.  
>
>If you've created a zip file for this app, upload it here.

Please, @rdeioiris 
https://github.com/rdeioris/UnrealOnRPI4

**Comment by CoderLogy** [comment]
Sorry man pls close this request yourself or else botspot will closed as I opened request like this and he told me same that he would tell u that we cannot install any game engine and piapps made for easy of people not for difficulty. And also unreal cannot be installed on raspberry Pi as it demands a graphic card or directx12 and minimum 8 gb ram and around 30 gb storage and also a high-end processor like Intel 5 th or 3 ed generation rather than staying on arm as arm even with recent developments cannot reach at speed like Intel or ryzen does so pls understand it

**Comment by Botspot** [comment]
This looks really fascinating, especially considering it runs on a Pi4.

What games could be made possible with this engine? (I'd rather add games to the app store, than game components like this engine)

**Comment by CoderLogy** [comment]
Botspot understand this is heavy game engine it could not work good on raspberry Pi I said u to install Godot and you it's difficult to install but I understand how Godot works and what do if you learn I am starting to learning Godot as I know some that how to use unity engine

**Comment by CoderLogy** [comment]
Unreal could work at some extended only as his link suggest but understand it would be broke raspberry Pi into pieces it such heavy engine that my 5 year old pc with some upgrades could not run it because it needs graphic card even with Intel 4000 hd on raspberry Pi 4 8gb ram could work it atleast but what will call a proper devlopment for even previous version users of Pi could not use it so make a game engine that would be good for all not only for 8gb ram one

**Comment by CoderLogy** [comment]
I have list of games that you could add on raspberry Pi it here
https://www.raspberrypi.org/forums/viewtopic.php?t=51794

**Comment by fabianmendes** [comment]
I read on the git shared something about the vulkan, does that help? I
mean, I hope the gut shared helps on any way

**Comment by CoderLogy** [comment]
Yes vulkan is good but understand unless until with raspberry Pi 8gb ram and bulman you can't do it so go ahead making games in that it would be great for your pi

**Comment by fabianmendes** [comment]
> > Can this app run on RPi? If so, please provide a link to a tutorial if applicable.
> > If you've created a zip file for this app, upload it here.
> 
> Please, @rdeioiris
> https://github.com/rdeioris/UnrealOnRPI4

I can't tag the user @rdeioris here but I think he could share something. Any ideas? I don't care if it's "outdated" (hey, like _apt_ Blender!!), and I think no one will care either if they can develop or start something on it. Also, and first of all: #185 I don't want to make all the code on the terminal every time I wanted to install _Unreal for RPi4_. Also context: I often re-flash my OS (despite this, I think that Unreal on RPi is necessary. The use of Unreal is getting bigger and bigger) 

P.S: I also would like to see the Pi-Apps badge in https://github.com/rdeioris/UnrealOnRPI4 hoho!

**Comment by Botspot** [comment]
Tell you what: if someone makes the install script, I'll add it.

Bonus points if it's 32-bits compatible.

**Comment by fabianmendes** [comment]
Here we go https://github.com/rdeioris/UnrealOnRPI4/issues/2

**Comment by Itai-Nelken** [comment]
any updates?

**Comment by fabianmendes** [comment]
> any updates?

Not yet, I couldn't  go further because of internet connection issues last several weeks. Sorry about it

**Comment by theofficialgman** [comment]
Closing as the linked repo is archived. The whole unreal sdk likely will not be ported and distributed for arm64 linux for many years and may never come.
