### ISSUE TITLE
Blender on raspberry Pi

### ISSUE THREAD

**Issue by CoderLogy** [Botspot/pi-apps#288]
Pls add blender to raspberry Pi it will help many users to do modelling on raspberry Pi and making game and editing videos and making python script to run on it it's  a game engine, video editor and modelling

**Comment by Itai-Nelken** [comment]
> Pls add blender to raspberry Pi it will help many users to do modelling on raspberry Pi and making game and editing videos and making python script to run on it it's a game engine, video editor and modelling

@CoderLogy Blender is already available on the pi from apt: `sudo apt install blender` yes, it is a older version but newer versions won't run because they require a newer version of openGL that the pi does not support.

before opening issues please research a bit, read existing issues (closed and open) and see that your request wasn't requested/tried already.
Blender was already tried in #108.
and if your request is new, do some research about it: find out if the pi can actually run it and by run it I don't mean to check if the pi is powerful enough, but if the app has a port for Linux arm or you tested it with box86/box86+wine.

As Botspot says: Pi-Apps isn't magic.

**Comment by Botspot** [comment]
Well said, @Itai-Nelken.
