### ISSUE TITLE
How to use minecraft-pi modes it doesn't install and when installed how to use it pls tell

### ISSUE THREAD

**Issue by CoderLogy** [Botspot/pi-apps#309]

**Comment by Botspot** [comment]
@CoderLogy You need to give more information in order for me to help you.  
For starters, you say "it doesn't install". How can I help you fix it, unless you send me the error message?

Concerning how to use it, the description for Minecraft Pi (Modded) should have covered that.

To recap, I can't help you solve a problem until you tell me what the problem is.

**Comment by mobilegmYT** [comment]
@CoderLogy The install should be fixed now, try again. You can join the discord server on the details page for the app for help.

**Comment by CoderLogy** [comment]
Sorry I didn't add error message but I will try again intstall it but can
you tell how it works and what do with some screenshots that would be cool

**Comment by mobilegmYT** [comment]
@CoderLogy Can you close this issue?

**Comment by CoderLogy** [comment]
Ok
