### ISSUE TITLE
Raspberry Pi OS with Pi Apps

### ISSUE THREAD

**Issue by GabeCoder** [Botspot/pi-apps#336]
Raspberry Pi OS with Pi Apps takes a step further into improving the simplicity of installing and running your favorite applications on your computer. With only a click of a button, you’ll have the application downloading and ready to run. Plus, the pre-installed apps included will help you configure and boost your Pi so you will experience Raspberry Pi OS smoothly. Installing apps has never been easier than ever.
Credit to @Botspot for creating Pi Apps.
Download the OS! ⬇️
https://gofile.io/d/2JoJ13

**Comment by ReallyFunnyGuyGabe** [comment]
The OS has officially been corrupted and is considered useless. Don’t download it.

**Comment by ReallyFunnyGuyGabe** [comment]
UPDATE: The OS has finally been fixed and is now eligible for installation. Enjoy your easier life with RPI and Pi Apps!

**Comment by Botspot** [comment]
I appreciate what you've done here and there's nothing wrong with it.

But I have a few concerns that will result in this issue being closed:

- I think few people will find this issue and download the image from you instead of from Raspbian's download site.
- Pi-Apps has recently gotten a one-liner installation command. So, it's already super easy to install onto pre-existing installs.
- Hosting your own image raises concerns by those who distrust humanity. Things like, "How can we know you haven't installed malware/spyware on it?"
- Github "issues" are not really meant for this. In my continued quest to close as many issues as possible, this one has to go, since it's not really an issue.

If you think your image is still useful, you're more than welcome to make your own github repository to spread the word. Or maybe make a post about it on the Raspberry Pi Forums.

**Comment by GabeCoder** [comment]
> I appreciate what you've done here and there's nothing wrong with it.
> 
> But I have a few concerns that will result in this issue being closed:
> 
> * I think few people will find this issue and download the image from you instead of from Raspbian's download site.
> * Pi-Apps has recently gotten a one-liner installation command. So, it's already super easy to install onto pre-existing installs.
> * Hosting your own image raises concerns by those who distrust humanity. Things like, "How can we know you haven't installed malware/spyware on it?"
> * Github "issues" are not really meant for this. In my continued quest to close as many issues as possible, this one has to go, since it's not really an issue.
> 
> If you think your image is still useful, you're more than welcome to make your own github repository to spread the word. Or maybe make a post about it on the Raspberry Pi Forums.

Understood, have a great day.

**Comment by Botspot** [comment]
> Understood, have a great day.

You too! :)
