### ISSUE TITLE
retropie_packages.sh: command not found

### ISSUE THREAD

**Issue by timonrus** [Botspot/pi-apps#340]
When I try to open the settings in RetroPi, I get an error /home/pi/RetroPie-Setup/retropie_packages.sh: command not found.
How can I fix it?

**Comment by Botspot** [comment]
Retropie has been removed from the store due to its complexity, state of disrepair, and lack of support.

I suggest you use a Retropie image, or use their own installation instructions at your own risk.

**Comment by thepinacoladasong** [comment]
> Retropie has been removed from the store due to its complexity, state of disrepair, and lack of support.

Fair enough, but how can we uninstall it if we installed it with Pi-Apps?

**Comment by Botspot** [comment]
> > Retropie has been removed from the store due to its complexity, state of disrepair, and lack of support.
> 
> Fair enough, but how can we uninstall it if we installed it with Pi-Apps?

The app has been removed from everyone's Pi-Apps installations because I added a `rm` command to delete the folder. The app is not just hidden, it's gone from your system.

Fortunately, I've located the original commit in which the RetroPie app was added in the first place. Here it is: https://github.com/Botspot/pi-apps/commit/500d2fb4804b54fc9bbc9158b465d9a1cbdc777c
Scroll down until you see the code in the `uninstall` script. Copy and paste that code into a terminal and it should uninstall RetroPie.
The "`purge-installed`" line in that uninstall script removes RetroPie-related packages. If you want `purge-installed` to work, run this first in the terminal so the script can be found: `DIRECTORY=~/pi-apps`

**Comment by thepinacoladasong** [comment]
Thanks for the quick response. I've found both the `uninstall `script and the `purge-installed `scripts, but it seems I'm not the most tech-savvy person as I'm a little unclear on the specific steps. Would you mind outlining it for me step-by-step? Thanks for your time.

**Comment by Itai-Nelken** [comment]
Run the following:
```bash
cd $HOME
git clone --depth=1 https://github.com/RetroPie/RetroPie-Setup.git
cd RetroPie-Setup
chmod +x retropie_setup.sh
sudo ./retropie_setup.sh
```
select 'Uninstall RetroPie'
run
```bash
DIRECTORY="$HOME/pi-apps"
"${DIRECTORY}/purge-installed" "$(dirname "$0")"
```

**Comment by thepinacoladasong** [comment]
Thanks very much! Love the project and happy to be a contributor to it.
