### ISSUE TITLE
Option in settings to stop certain apps from updating

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#377]
for example I had to redownload the discord scripts for the deb version 3 times because I accidentally updated the discord app.
having a option to stop apps you are modifying from updating is something I'm sure a lot of people will find very useful.

**Comment by Botspot** [comment]
I may choose to add this feature in the future, but until then, here's what I do:

- Rename the app. For example, from `Discord` to `Discordnew`. Now Pi-Apps considers this app as a local app, because `Discordnew` doesn't exist on the repo.
- Don't update. This is what I most often do, and when I do want to update some things but not others, I just manually copy stuff from `~/pi-apps/update/pi-apps` to `~/pi-apps`.
- Recover your old app folders from the Trash. To solve this exact problem, pi-apps doesn't delete "old" app folders. Instead, it moves them to trash. This has saved me more than once, when I update, then realize that something was customized. It's easy to recover prior app folders, thanks to this safety net.

**Comment by Itai-Nelken** [comment]
ok, thanks
