### ISSUE TITLE
Discord Not working with Ubuntu Mate

### ISSUE THREAD

**Issue by 2Kernel** [Botspot/pi-apps#379]
I am using a Pi4 4gb model and installed Ubuntu mate.
Tested both the 64bit and the 32bit of Mate. All the other apps were working(I tried about 7 random apps) but discord isn't working. It installs well but when I try to open the app the window shows up as a white square and then closes by itself. Please help!
+) I heard that the mate terminal has some issues with pi-apps so I used xfce4 terminal to run pi apps but it doesn't work

**Comment by techcoder20** [comment]
@real-gamb1t try downloading the Deb manually to check if it's a pi apps problem or the webapp problem. 
https://github.com/SpacingBat3/electron-discord-webapp/releases/download/1.0.2/electron-discord-webapp_1.0.2_arm64.deb

**Comment by real-gamb1t** [comment]
I'm running a 32bit one so I downloaded and ran https://github.com/SpacingBat3/electron-discord-webapp/releases/download/1.0.2/electron-discord-webapp_1.0.2_armhf.deb
It still has the same issue. The app installs successfully but when I run it, it only shows a white block.

**Comment by Botspot** [comment]
If @spacingbat3 (Discord's deb creator) chooses to investigate this and fix it, then good for him.

But I (Pi-Apps creator) have no control over how/if Discord works.

@2Kernel, thank you so much for opening this issue! It was the right thing to do. But in this case, it would be preferable if this issue was moved to @spacingbat3's repository. Link: https://github.com/SpacingBat3/electron-discord-webapp/issues/new
