### ISSUE TITLE
Godot Engine For the Rasberry Pi

### ISSUE THREAD

**Issue by gl91306** [Botspot/pi-apps#462]
Here's the Pi-apps zip file
[Godot Engine 3.2.4.zip](https://github.com/Botspot/pi-apps/files/6137396/Godot.Engine.3.2.4.zip)

**Comment by mobilegmYT** [comment]
@Botspot

**Comment by Botspot** [comment]
A couple things I noticed before installing:

- Nowhere does the description actually explain what Godot is. I had to do some digging to discover it's a game engine!
- The last link is broken, due to you ending the sentence with a period. (YAD assumed the period was part of the URL.) In this case I'd recommend you put the raspberry pi specific URL in the `website` file, instead of using https://godotengine.org/

How would I test this app?

**Comment by gl91306** [comment]
> A couple things I noticed before installing:
> 
> * Nowhere does the description actually explain what Godot is. I had to do some digging to discover it's a game engine!
> * The last link is broken, due to you ending the sentence with a period. (YAD assumed the period was part of the URL.) In this case I'd recommend you put the raspberry pi specific URL in the `website` file, instead of using https://godotengine.org/
> 
> How would I test this app?

I fixed, the first two suggestions, and as for testing, you simply have to do ./(godotlauncherthing).bin and it just automatically runs.
[Godot Engine 3.2.4.zip](https://github.com/Botspot/pi-apps/files/6153662/Godot.Engine.3.2.4.zip)
