### ISSUE TITLE
Nothing installs on Kali Linux

### ISSUE THREAD

**Issue by mad-ton** [Botspot/pi-apps#466]
was able to install and lauch pi-apps. However it does not install any apps. Terminal reads:
```
Output: Tor BrowserEOO
Details
cat: '/home/kali/pi-apps/data/installed-packages/Tor Browser': No such file or directory
cat: '/home/kali/pi-apps/data/status/Tor Browser': No such file or directory
Button: 4
QDir::exists: Empty or null file name
Using a variable-width font in the terminal.  This may cause performance degradation and display/alignment errors.
Using a variable-width font in the terminal.  This may cause performance degradation and display/alignment errors.
Timestamps match.
Reading list file...
Details
cat: '/home/kali/pi-apps/data/installed-packages/Tor Browser': No such file or directory
cat: '/home/kali/pi-apps/data/status/Tor Browser': No such file or directory
Button: 0
Back
Timestamps match.
Reading list file...
Another instance of preload-daemon is already running. Exiting now.
Another instance of preload-daemon is already running. Exiting now.
```

**Comment by Botspot** [comment]
First, be aware that Kali is not supported the same way RPiOS is. If you have app-specific issues, they may be out of the scope of Pi-Apps to fix.

Second, the error output is of little help in this case. (But thanks for posting it!) Usually when nothing installs, it's due to a malfunctioning terminal.  
To test this theory, we can try two different things:

1. Try installing an app, and look carefully for any black boxes (terminals) briefly flashing on the screen and then vanishing. If you see anything like that, then there's the problem for sure.
2. Run this code to determine what terminal program Pi-Apps is trying to use:
```
if [ -f /usr/bin/lxterminal ];then
  echo lxterminal
elif [ -f /usr/bin/xfce4-terminal ];then
  echo xfce4-terminal
elif [ -f /usr/bin/mate-terminal ];then
  echo mate-terminal
elif [ -f /usr/bin/xterm ];then
  echo xterm
elif [ -f /usr/bin/konsole ];then
  echo konsole
elif [ -f /usr/bin/x-terminal-emulator ];then
  echo $(readlink -f /usr/bin/x-terminal-emulator)
else
  echo "Failed to locate any terminal emulators!!!"
  exit 1
fi
```

**Comment by Treks2448** [comment]
Hello, I have the same issue, but on Ubuntu Mate. 
I ran "sudo pi-apps" from terminal and had a similar output to mad-ton.
I do get a flashing terminal opening if I simply launch the app from the menu.
I ran the code posted by Botspot. It responded with "mate-terminal".

**Comment by Itai-Nelken** [comment]
> Hello, I have the same issue, but on Ubuntu Mate. 
> I ran "sudo pi-apps" from terminal and had a similar output to mad-ton.
> I do get a flashing terminal opening if I simply launch the app from the menu.
> I ran the code posted by Botspot. It responded with "mate-terminal". 

Dint run pi-apps as root

**Comment by Botspot** [comment]
> Hello, I have the same issue, but on Ubuntu Mate.
> I ran "sudo pi-apps" from terminal and had a similar output to mad-ton.
> I do get a flashing terminal opening if I simply launch the app from the menu.
> I ran the code posted by Botspot. It responded with "mate-terminal".

@Treks2448 I've been able to repeat the issue you're having. It's very weird, because I already fixed mate-terminal TWICE. Anyway, as it wasn't working for me today, I found a solution. Please update Pi-Apps, and you should be good to go!

As far as the original issue with Kali, IDK what terminal it's trying to use, and so don't know if this fix I just made will solve @mad-ton's issue as well.

**Comment by Botspot** [comment]
Closing this issue, as I'm fairly sure @mad-ton's issue was solved when I fixed `mate-terminal`.
