### ISSUE TITLE
Sound fix for minecraft 1.8.9

### ISSUE THREAD

**Issue by gl91306** [Botspot/pi-apps#517]
so ive aldready provided a temporary fix for this, but to fix this for the whole app, all you have to do is to replace the code in the install script for minecraft java, and replace the part where it downloads rpimikes lwjgl2arm32 and replace it with wget https://github.com/gl91306/filestorage/raw/main/lwjgl2arm32.tar.gz and its fixed

**Comment by Botspot** [comment]
Instead of using an entirely different lwjgl2arm32 folder, I think it may be better to only use the new file.

The script could simply download your single file and put it in the right spot. BTW we don't need two issues open for this, there's already one [issue](https://github.com/Botspot/pi-apps/issues/513) open for it.
