### ISSUE TITLE
My opinion on the new icons

### ISSUE THREAD

**Issue by locness3** [Botspot/pi-apps#519]
The new icons are a bit confusing, at least for me.

For instance, the "install" and "uninstall".
![image](https://user-images.githubusercontent.com/37651007/113179512-fa0a9000-924f-11eb-80b3-0176a901183c.png)
You install apps from Pi-Apps to your device, which is not well represented by these two icons. Without their text and context, the install one seems to be about adding something "into" Pi-Apps, while the second one seems to be removing it from Pi-Apps.

The same goes for the installed status icons. A checkbox on the shopping bag seems more like "the app is available from the store" or something like that.

Bascially, may want to remove the shopping bag from icons, it has nothing to do there.

**Comment by Botspot** [comment]
Your concerns are valid. I do agree the icons have room for improvement, but am not sure _how_ to improve them.

Redoing the original icons was necessary:  

- After watching other people use Pi-Apps, I noticed that most people instinctively tried to click the "checkboxes". (the app's status icons)  
- In addition, the original install/uninstall icons would rarely draw your attention.
- On some themes the grey buttons would blend in and become invisible.

For those three main reasons, I realized that a material redesign was necessary.

Devising a set of app status icons was tricky - "how to indicate that an app is installed, using 16x16 pixels, without looking like a check box?"  
In the end, I made the status icons look like shopping bags. Now nobody was clicking the status icons to try to install stuff. Success!

There were still problems though. The biggest, was that when viewing a category, all action buttons weren't labelled, in order to fit the fourth button. As a result, many users didn't know what to do with these buttons.
In addition, the `+` and the `-` didn't really look like action buttons as much as I had hoped.

Eventually I decided to again use the bag idea and extended the analogy to "put apps in the bag, or dump apps out of the bag."  
Yes I agree with you it's far from perfect, but currently I don't see a better way to convey the meaning any clearer.

If you have an idea for how to improve it, you are more than welcome to edit the icons yourself. :)  
They are located in `/home/pi/pi-apps/icons`.  
My image editor of choice is KolourPaint. It can be installed with `sudo apt install kolourpaint`.

**Comment by locness3** [comment]
> After watching other people use Pi-Apps, I noticed that most people instinctively tried to click the "checkboxes". (the app's status icons)
I think this could be solved :
- by adding a colored background or
- by coloring the foreground or
- by putting the icon on the right (if possible)

> Eventually I decided to again use the bag idea and extended the analogy to "put apps in the bag, or dump apps out of the bag."
May want to use computer- or Pi-related icons for this ;)

> If you have an idea for how to improve it, you are more than welcome to edit the icons yourself. :)
I'll have a go.

**Comment by srini-pro** [comment]
then it wont be pure dark mode right?
if that happens

**Comment by locness3** [comment]
The thing is we need to ensure the icons work as well on light and dark modes (unless we can detect if a dark theme is used somehow?)

**Comment by Botspot** [comment]
> then it wont be pure dark mode right?
> if that happens

Currently the icons work fairly well on dark mode. Better than the old icons, at least.

**Comment by Botspot** [comment]
> I'll have a go.

How's it coming? (Can you tell I'm looking for issues to close? :P )

**Comment by locness3** [comment]
I didn't start anything yet. But wouldn't it be better to work with svg icons (rendered to png via a script)?

**Comment by locness3** [comment]
Also why is the install and uninstall text in the PNGs, and not as the actual label of the button in yad?

**Comment by locness3** [comment]
Oh. Maybe use "Remove" then?

**Comment by Botspot** [comment]
> Oh. Maybe use "Remove" then?

I could, but chose to instead use png text for two reasons:
- Changing "uninstall" to "remove" would invalidate many tutorials. Also, changing the text label after everyone's used to it being "uninstall", opens the door for issues like this one. "I prefer the old version of X...", or "My opinion on X..."
- It would end up being too wide. Using a png icon, without any label text, makes a significant width reduction.

**Comment by TurquoiseTNT** [comment]
I dont know if anyone likes these but i made custom icons.
Badge: ![Badge](https://user-images.githubusercontent.com/69688534/114267078-c10db080-99f1-11eb-8501-5549e9f6863e.png)
Info: ![Info](https://user-images.githubusercontent.com/69688534/114267079-c10db080-99f1-11eb-979a-263c5d77d7c1.png)
Install: ![Install](https://user-images.githubusercontent.com/69688534/114267080-c1a64700-99f1-11eb-8f12-b4f288a43b9f.png)
Logo: ![Logo](https://user-images.githubusercontent.com/69688534/114267081-c1a64700-99f1-11eb-99c8-447a4dc35040.png)
Uninstall: ![Uninstall](https://user-images.githubusercontent.com/69688534/114267082-c1a64700-99f1-11eb-963c-7ce534b91744.png)

**Comment by TurquoiseTNT** [comment]
ZIP Containing
[Pi-Apps-Custom-Icons.zip](https://github.com/Botspot/pi-apps/files/6289749/Pi-Apps-Custom-Icons.zip)
 All PNG Files

**Comment by locness3** [comment]
Good idea to use an arrow and a bin, plus an arrow and a Pi!

**Comment by TurquoiseTNT** [comment]
Thank You.

**Comment by Botspot** [comment]
> I dont know if anyone likes these but i made custom icons.

I liked them.
Recently a couple of the buttons were improved. Your icons partially inspired the changes. (the arrow, the pi logo, and the trash can)
![2021-05-06-193556_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/117381711-5772ac00-aea2-11eb-81b4-92f7ff09a610.png)

**Comment by mobilegmYT** [comment]
> > I dont know if anyone likes these but i made custom icons.
> 
> I liked them.
> Recently a couple of the buttons were improved. Your icons partially inspired the changes. (the arrow, the pi logo, and the trash can)
> ![2021-05-06-193556_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/117381711-5772ac00-aea2-11eb-81b4-92f7ff09a610.png)

You should also change the "Install" and "Uninstall" buttons to have a capital at the beginning...

**Comment by Botspot** [comment]
> You should also change the "Install" and "Uninstall" buttons to have a capital at the beginning...

Better now?

**Comment by TurquoiseTNT** [comment]
WOW!
Normally I do this stuff for fun but I did not release that mine would become an inspiration!

**Comment by locness3** [comment]
@TurquoiseTNT Keep contributing to open-source! Any contribution, small or big can have an impact. And sorry for the necro.

**Comment by TurquoiseTNT** [comment]
> > I dont know if anyone likes these but i made custom icons.
> 
> I liked them. Recently a couple of the buttons were improved. Your icons partially inspired the changes. (the arrow, the pi logo, and the trash can) ![2021-05-06-193556_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/117381711-5772ac00-aea2-11eb-81b4-92f7ff09a610.png)

Looking Back on This, What OS are you using?

**Comment by Botspot** [comment]
> Looking Back on This, What OS are you using?

At the time I was using Raspberry Pi OS Buster, themed using [my Windows 10 Theme](https://github.com/Botspot/Windows-10). Unfortunately the changes made to Bullseye make it a lot uglier, but it is what it is.

**Comment by mobilegmYT** [comment]
Reject windows 10 theme, steal theme from twister os
