### ISSUE TITLE
Use ~/.cache to store downloaded files?

### ISSUE THREAD

**Issue by locness3** [Botspot/pi-apps#520]
Currently, scripts download their required files directly to the home directory, which doesn't feel very "clean" to me.
Maybe use ~/.cache or ~/Downloads for that?

**Comment by Botspot** [comment]
I prefer having all scripts doing everything in the open: if there's problems or `wget` has download the same file 5 times and made 5 copies, we want to know that.

Having a script conceal what it's doing, for no apparent reason/benefit, seems like bad form.  
But in the end it's a matter of preference. Just now I changed the Arduino app to store it's program files in `~/.local/share` instead of /home/pi, in order to cut down on unnecessary folders cluttering the home folder.

**Comment by locness3** [comment]
? How does storing in a different folder conceals what scripts do?

**Comment by Botspot** [comment]
> ? How does storing in a different folder conceals what scripts do?

If a script malfunctions, the users should know.  
This is partly accomplished by using the `error` function, but some issues aren't caught that way.  
In any case, when a script uses /home/pi, its actions are out in the open for anyone to easily view. Many issues have been found by accident, that otherwise would have not been noticed if scripts were using `/opt`, `/tmp`, etc.

But again, it comes down to a matter of preference. If I want an app's program files to be stored at /home/pi for easy user access, then I would consider it just fine to download an archive to /home/pi, extract the archive, then delete the archive.  
Downloading the archive to a less-visible location and then having to explicitly tell the extractor to extract to a non-default directory, seems like more effort for no visible gains.

@locness3, is there any app in particular that you're referring to when you opened this issue?

**Comment by locness3** [comment]
I'm nit referring to any app in particular
