### ISSUE TITLE
OpenCV

### ISSUE THREAD

**Issue by hmsjy2017** [Botspot/pi-apps#557]
Compiling OpenCV is very time-consuming and easy to fail. It is very convenient to install directly from the deb package.
### 4.2.0
https://github.com/dltpdn/opencv-for-rpi/releases
### 4.5.0
https://github.com/cyysky/OpenCV-Raspberry-Pi-4-Package-for-Python/releases
Some useful scripts: https://github.com/cyysky/OpenCV-Raspberry-Pi-4-Package-for-Python/tree/master/StepForBuilding/4.5.0

**Comment by CleanMachine1** [comment]
How is this hard to compile, its like 5 command to copy and paste..
It may take a while to compile though, I haven't tested

**Comment by Botspot** [comment]
Looks like this would do:
```bash
rm -f ~/opencv.deb
wget -O ~/opencv.deb https://github.com/cyysky/OpenCV-Raspberry-Pi-4-Package-for-Python/releases/download/4.5.0/opencv_4.5.0-1_armhf.deb
sudo apt install -yf ~/opencv.deb
rm -f ~/opencv.deb
```

I don't feel qualified to create the app for this. To be honest, I've never heard of OpenCV before, and doubt I'd describe it properly. Someone else can make the app.

**Comment by CleanMachine1** [comment]
Is it not in pip?

**Comment by CleanMachine1** [comment]
https://pypi.org/project/opencv-python/

**Comment by CleanMachine1** [comment]
pip3 install opencv-python

unsure if it works on ARM, but works on x86

**Comment by Botspot** [comment]
> pip3 install opencv-python
> 
> unsure if it works on ARM, but works on x86

`sudo pip3 install opencv-pytho` works for me on a Pi4 running RPiOS.

**Comment by hmsjy2017** [comment]
@Botspot OpenCV is an open source cross-platform computer vision and machine learning software library.OpenCV built from source code can use full functions (but opencv-python can't), but the compilation is complicated and easy to fail.

**Comment by CleanMachine1** [comment]
Whats hard about compilation

**Comment by CleanMachine1** [comment]
Since OpenCV is a product which does rely on performance, it would probably be better for it to be compiled at installing.

Also I don't think this app should be added since its not something most would even know about or use.

How many Pi-Apps users are going to know how to write machine learning code through cameras and not know how to run some basic compiling commands.

If a Pi-Apps user knows how to write machine learning python code I trust them to Ctrl+C and V some commands

**Comment by theofficialgman** [comment]
I think the users who want to use opencv on the pi already have multiple avenues for installs (or building) updated versions of opencv and don't need another version on pi-apps. especially since we don't have any maintainers which use it.

opencv also have many different internal parts that some users might want to enable/disable, and this can only be done by building it yourself

(full process for these types of things is always at <https://qengineering.eu>)
