### ISSUE TITLE
New App: Lightshot

### ISSUE THREAD

**Issue by KolpixTV** [Botspot/pi-apps#581]
Hey,

i wrote this Script to install Lightshot and i want to ask if you can add it to the offical "App Store".
This App is for the Categorie: "Eyecandy" the Zip file is the attached FIle:
[Lightshot.zip](https://github.com/Botspot/pi-apps/files/6321528/Lightshot.zip)

With friendly Regards
KolpixTV

**Comment by Botspot** [comment]
Nice job writing the scripts! :)  
Wow, this app is incredibly similar to Flameshot, which is already on Pi-Apps.

@KolpixTV, could you please install both Lightshot and Flameshot on your Pi and compare the two? If Flameshot turns out to be equivalent, then it may be better to only distribute Flameshot. (Flameshot is a native armhf application, while lightshot has to go through two emulation layers)

**Comment by KolpixTV** [comment]
Hey,

thank you for the fast answer Flameshot is really nice and i compared Flameshot and Lightshot and Flameshot is better ,because it has more tools and its user more user-friendly. The only better thing in Lightshot is that you can also upload your Pictures to prntscr, printerest, twitter etc. ,you can search after the picture on google and you can direcct print the Picture with a printer. So i think Flameshot is better :D 

~KolpixTV
