### ISSUE TITLE
YouTube Music

### ISSUE THREAD

**Issue by SuperPi911** [Botspot/pi-apps#589]
[YouTube Music.zip](https://github.com/Botspot/pi-apps/files/6337017/YouTube.Music.zip)

**Comment by Itai-Nelken** [comment]
this is a nativefier webapp, right?
because you should use the official icon in my opinion:
<img width="200" alt="YouTube-Music" src="https://user-images.githubusercontent.com/70802936/115275417-70612a80-a14a-11eb-8065-d26da81887cd.png">
 `nativefier music.youtube.com --arch armv7l --icon path/to/YouTube-Music.png`
and add a tray icon if you didn't (I didn't test the app, so I don't know if you added the tray icon): `nativefier music.youtube.com -arch armv7l --icon path/to/YouTube-Music.png --tray`
and there is [this youtube music web app](https://github.com/th-ch/youtube-music) that is way better and has some sort of ARM support (see https://github.com/th-ch/youtube-music/issues/85#issuecomment-779651296).

**Comment by SuperPi911** [comment]
I know but the nativefier icon looks better

**Comment by Itai-Nelken** [comment]
But a lot of users install apps by there icon, not name. so using the official icon is better.
also I have concerns with nativefier webapps when running heavy websites like youtube music, see https://github.com/Botspot/pi-apps/issues/587#issuecomment-822636515 and https://github.com/Botspot/pi-apps/issues/588#issuecomment-822638783

**Comment by SuperPi911** [comment]
[YouTube Music.zip](https://github.com/Botspot/pi-apps/files/6342055/YouTube.Music.zip)
V2

**Comment by mobilegmYT** [comment]
@Itai-Nelken Perhaps?

**Comment by Itai-Nelken** [comment]
the scripts wgere improved, I think thats all.

I still think that running a heavy website like youtube music in a nativefier (electron) webapp is a bad idea. we should use this instead: https://invent.kde.org/jbbgameich/audiotube but I never got it to compile correctly.

**Comment by Botspot** [comment]
Closing, as this would probably run better in-browser, than in electron.
