### ISSUE TITLE
Gmail

### ISSUE THREAD

**Issue by SuperPi911** [Botspot/pi-apps#593]
[Gmail.zip](https://github.com/Botspot/pi-apps/files/6349063/Gmail.zip)

**Comment by Itai-Nelken** [comment]
Is this a nativefier web app?

**Comment by mobilegmYT** [comment]
> Is this a nativefier web app?

Looks like it, maybe it could be a regular chromium webapp too.

**Comment by Itai-Nelken** [comment]
Can you check please? If it's a regular chromium webapp it will be a shell script, if it's a nativefier webapp it will be a executable and tons of files.

**Comment by CleanMachine1** [comment]
Why?

Why not use an email client such as claws or thunderbird?

**Comment by Itai-Nelken** [comment]
>Why?
>
>Why not use an email client such as claws or thunderbird?

A lot of people prefer the webpage, not everyone will like to use a app that looks different than anything they know.

@CleanMachine1 don't think about why would you want it in cases like this app, think why would other people want it. not everyone cares about privacy (unfortunately), not everyone wants to use an email client, and not everyone wants an email client that looks a bit outdated compared to the gmail webpage. 
***
anyway if its a nativefier webapp, I'm against adding it. heavy websites like gmail + electron = using all your CPU and RAM.
for less heavy sites like stackedit and whatsapp, I'm ok with using nativefier webapps. thats my opinion.

**Comment by CleanMachine1** [comment]
Loading websites filled with JS are terrible on pis and especially on ARM computers (personal experience)

There are plenty of good mail clients, thunderbird is my choice and its filled with privacy options and uses near 0% CPU on my personal laptop, its so light that I have it docked away, compare that to something like Gmail in a webbrowser and I assume it would be near 10% just in the background (probably all the spyware and data collection)

**Comment by CleanMachine1** [comment]
> A lot of people prefer the webpage, not everyone will like to use a app that looks different than anything they know.

Linux, most newbs of pi have come from Windows, completely different.


Also consider its a $35 PC then you have a reason to say, give in and use a lighter, less bloated application

**Comment by SuperPi911** [comment]
It is working verry well with nativefier rather than chromium, but it is verry handy.

**Comment by CleanMachine1** [comment]
Can you open it and then open a htop in terminal and monitor CPU and RAM usage as it loads and does things?
That would be very helpful and I am sure everyone would be more inclined to add it if it works well

**Comment by Itai-Nelken** [comment]
I'm sure its using a lot of resources, but I don't think it matters to people that are new to linux and all they want is the familiar webpage. this brings up something else: all the people that use gmail that I know use it from a web browser, so adding this webapp makes even less sense to me.

@CleanMachine1 I'm not saying that claw or thunderbird are bad (I like them, but don't have any use for them), I just think that most people will prefer the website (and will go straight to it in a web browser).
***
here is my opinion on why this shouldn't be added:
1) most if not all people that use the gmail website will go to it in a web browser and not even think about using a webapp.
2) electron apps are heavy. and while lighter websites are ok on the pi, a heavy website like gmail aren't ok.

**Comment by SuperPi911** [comment]
But WHY you added WhatsApp, Discord, THESE ARE NATIVEFIER WEBAPPS?

**Comment by mobilegmYT** [comment]
(Discord also doesn't use as much ram as opening it in chrome AFAIK.)

**Comment by Botspot** [comment]
> I'm sure its using a lot of resources, but I don't think it matters to people that are new to linux and all they want is the familiar webpage. this brings up something else: all the people that use gmail that I know use it from a web browser, so adding this webapp makes even less sense to me.
> 
> @CleanMachine1 I'm not saying that claw or thunderbird are bad (I like them, but don't have any use for them), I just think that most people will prefer the website (and will go straight to it in a web browser).

I agree with you on both points, @Itai-Nelken. In my opinion, **web apps are not on the same level** as other apps. You can't compare a container running an ordinary website, to an emulated IDE. (Notepad ++)

Part of me wants to draw the line and remove all web apps from Pi-Apps, in the name of consistency and standards. But another side of me realizes that _some websites really do benefit_ from being separated from the browser, either due to privacy concerns, performance, or based on how people use them. ;)  
Discord is a great example. I find it a lot more convenient to use Discord separately from the rest of my browser. It's draggable, autostartable, minimizeable, resizeable, and can hide out in the system tray when I'm not using it. It's a tribute to the usefulness of a web app. But not all websites are equally useful, like Google.com. Seriously, come on - how many people would care for a separate search engine app? It's not the same as Discord, but this opinion may be the exact opposite for the next guy. When we come to web apps, some seem to work well, while others don't. Though nobody can agree on what exactly makes a web app successful.

I have to decide what other people's opinion will be about an app. I have to pick sides for the grey areas. I have to dismiss some apps to hold some sort of a standard. But in cases like this, there really isn't a standard - I just have to go by gut feelings and fallible perception. Doing this is probably my least-favorite parts of managing Pi-Apps, saying "no" to an app and having nothing more than a hypocritical opinion to back it up.

For gmail.com, I have chosen to say no. While some people may benefit, it just doesn't seem to have the same convenience as Discord, though I can't tell you why. (boy do I hate being the decision-maker, but someone's got to do it.)
