### ISSUE TITLE
AdventButWrong

### ISSUE THREAD

**Issue by leha-code** [Botspot/pi-apps#626]
[AdventButWrong.zip](https://github.com/Botspot/pi-apps/files/6412486/AdventButWrong.zip)

**Comment by donnerkebab1730** [comment]
yep i mean i want this on pi apps

**Comment by Botspot** [comment]
This issue is being closed because:

- Adventbutwrong doesn't seem playable. According to LEHAtupointow on Discord, you are supposed to _guess_ what word to type, to proceed to the next page.
- LEHAtupointow on Discord says that only 50 or so people would be interested in installing it. (And would know how to use it)
