### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by RaspberryRBX** [Botspot/pi-apps#63]
[Spotify.zip](https://github.com/Botspot/pi-apps/files/5489802/Spotify.zip)

**Comment by Botspot** [comment]
Chromium Media Edition already runs Spotify perfectly fine.  

If someone were to install this app, and not already have Chromium Media Edition installed, it wouldn't work because Spotify certainly requires the widevine libs, which your app doesn't take care of.

The only thing your app does is open the Spotify website in its own window. The user-agent is the same as Chromium Media Edition, it depends on the Widevine lib from Chromium Media Edition.

I don't see the point of adding this.

**Comment by RaspberryRBX** [comment]
@Botspot I Did Try To Add Chromium Media But The Code i found didnt work

**Comment by mobilegmYT** [comment]
Chromium media edition is already in pi-apps--
Cheers,
Mike
CEO of The Useless Companies Corp.

**Comment by Botspot** [comment]
I'm going to close this now, as Chromium Media Edition is already on Pi-Apps and plays Spotify correctly already.

**Comment by Botspot** [comment]
Wait, I re-opened it?!  
Oops.
