### ISSUE TITLE
GNOME For Pi

### ISSUE THREAD

**Issue by TerraGitHuB** [Botspot/pi-apps#685]
Hi @Botspot !

Looks like a new app just came in...

This is GNOME For Pi (For Pi Apps) based upon this project (mine): https://github.com/TerraGitHuB/gnomeforpi

It removes normal Raspberry Pi OS desktop, and replaces it with GNOME.

GNOME is then configured to work in Raspberry Pi OS.
[GNOMEFORPI-PiAPPS.zip](https://github.com/Botspot/pi-apps/files/6537542/GNOMEFORPI-PiAPPS.zip)

**Comment by chunky-milk** [comment]
> Hi Botspot!
> 
> 
> 
> Looks like a new app just came in...
> 
> 
> 
> This is GNOME For Pi (For Pi Apps) based upon this project (mine): https://github.com/TerraGitHuB/gnomeforpi
> 
> 
> 
> It removes normal Raspberry Pi OS desktop, and replaces it with GNOME.
> 
> 
> 
> GNOME is then configured to work in Raspberry Pi OS.
> 
> [GNOMEFORPI-PiAPPS.zip](https://github.com/Botspot/pi-apps/files/6537542/GNOMEFORPI-PiAPPS.zip)
> 
> 

This looks awesome!

**Comment by TerraGitHuB** [comment]
@chunky-milk Thanks!

Be warned that Pi-Apps implementation will remove Raspberry Pi OS desktop, so be prepared for that...

**Comment by TerraGitHuB** [comment]
It was, but I find it pretty usable, even with animations turned on. Give it a go! I thin I have a pre-built image somewhere

**Comment by Itai-Nelken** [comment]
This looks really nice @TerraGitHuB! unfortunately this cant be added to pi-apps unless there is a functional uninstall script...
it should be easy enough to use something like @techcoder20's [ThemeSaver](https://github.com/techcoder20/ThemeSaver) to save the configuration of the rpi desktop and install the gnome packages using pi-apps's `pkg-install` script.
then to uninstall it, install the rpi desktop and use `purge-installed` to remove all the packages installed for gnome, and use ThemeSaver to reload the users theme.
also make backups of the files the script changes so the uninstall script can revert back.

**Comment by Botspot** [comment]
> This looks really nice @TerraGitHuB! unfortunately this cant be added to pi-apps unless there is a functional uninstall script...
> it should be easy enough to use something like @techcoder20's [ThemeSaver](https://github.com/techcoder20/ThemeSaver) to save the configuration of the rpi desktop

Or to see how [my Windows 10 theme](https://github.com/Botspot/Windows-10) restores configs.

**Comment by TerraGitHuB** [comment]
I don't think (I'm ENTIRELY fluent in bash script) that those do quite what I would need, considering they restore desktop configuration files, whilst my project is installing a whole desktop enviroment, so I don't think that would work.

I could use backups, but they're a bit limited.

However, I think the best option from here is for the installer to install a lighter amount of packages (If people are coming from a standard version of Raspberry Pi OS, they'll probably have apps already), which makes things a lot easier for the uninstall script (I can keep track of the packages much more easily).

**Comment by TerraGitHuB** [comment]
Oh, I see what you're saying now.

That makes a lot of sense.

Anyway, I'll work on an uninstall script.

**Comment by TerraGitHuB** [comment]
Ok, You can now uninstall and have Raspberry Pi OS desktop back:
[GNOMEFORPI-PiAPPS.zip](https://github.com/Botspot/pi-apps/files/6545010/GNOMEFORPI-PiAPPS.zip)

**Comment by TerraGitHuB** [comment]
Oh, a little off topic, an image: https://drive.google.com/drive/folders/13LO7sXRnuwO-NLlNKFU59-WpG9K0Upi6?usp=sharing

**Comment by TerraGitHuB** [comment]
Ok, I missed the credits, oops:

[GNOMEFORPI-PiAPPS.zip](https://github.com/Botspot/pi-apps/files/6546647/GNOMEFORPI-PiAPPS.zip)

**Comment by Itai-Nelken** [comment]
A few problems with the scripts:
1) `apt` is not being run as root, pi-apps runs the scripts as regular user, so you have to run `apt` with `sudo`.
2) you shouldn't use `apt`, use pi-apps's `pkg-install` script instead. it still uses `apt`, but it installs only the packages that aren't installed and remembers them so when you run `purge-installed` in the uninstall script, only the packages that where installed by the install script will be uninstalled.
**`pkg-install` usage:**
```bash
# Get dependencies
"${DIRECTORY}/pkg-install" "package1 package2 package3" "$(dirname "$0")" || exit 1
```
**`purge-installed` usage:**
```bash
#if your app installs any packages, keep this command here so those packages will be removed.
"${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1
```
3) Use the `error` function more, and you have to add the following to the top of the script:
```bash
DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" &gt;/dev/null 2&gt;&amp;1 ; pwd -P )")")"

function error {
      echo -e "\\e[91m$1\\e[39m"
      exit 1
 }
```
(also change the error in the part that clones the repository, kits on the default example).

also instead of cloning a repo that clones a repo, just put the `gnomeforpi-full` script in the install script, you can create a function for the `purge-pi-desktop` script if you need/want.
**function syntax in bash:**
```bash
function funcName() {
    #code goes here
}

#call (run) the function
funName
```
Is this tested? I'm pretty sure the uninstall won't work properly.
use the 'create-app' in pi-apps settings to create the app (if you didn't use it), it will use the template app scripts as a base.
feel free to ask any questions you have on how to do stuff.

**Comment by TerraGitHuB** [comment]
Ok, thanks for the pointers. I'll try and re-write (ok, use pi-apps to do the work)

When looking at the template script, it kind of was confusing about what each part did (could just be me)

Yes the uninstall script was tested and worked.

**Comment by TerraGitHuB** [comment]
What should I do if a command requires root permissions?

**Comment by TerraGitHuB** [comment]
Another thing, my app requires Raspberry Pi OS desktop to be removed, can this be done with the in-built functions?

**Comment by Itai-Nelken** [comment]
> What should I do if a command requires root permissions?

run the command with `sudo`, so if for example you have a command that is called `test`, and you want to run it as root, run `sudo test`.

> Another thing, my app requires Raspberry Pi OS desktop to be removed, can this be done with the in-built functions?

not in this case.

use `pkg-install` and `purge-installed` for GNOME and everything it needs, and to remove and restore the rpi desktop you can use `apt`.

**Comment by TerraGitHuB** [comment]
Ok, thanks!

**Comment by TerraGitHuB** [comment]
I'm afraid, I don't think GNOME For Pi will be be put up on Pi-apps (yet).

No matter what I do (following the wiki), I just keep getting permission errors (unless I do it with apt).

I'll probably work on it if and when I want to, but after an afternoon and a bit of a morning trying and failing to get this working, I think I'm calling it there.

Thanks to everyone who tried to help!

**Comment by TerraGitHuB** [comment]
Ok, reopening, I think something is wrong...

Anyway, could somone who knows how to test this stuff test this new app for me?

Thanks,
[Archive.zip](https://github.com/Botspot/pi-apps/files/6710421/Archive.zip)

**Comment by Itai-Nelken** [comment]
looks mostly good to me. did you test it? I'll see if I can test it tomorrow.

**Comment by TerraGitHuB** [comment]
Like before, got permission errors. Not sure what the issue is, especially since I commented out all the lines and got an error (what's the right way to test it?)

Should be fine though. Let me know how it works.

**Comment by Itai-Nelken** [comment]
You have to make the install script itself executable with `chmod +x install`.

**Comment by TerraGitHuB** [comment]
Ah, that makes sense. I'll try it myself at somepoint then. Thanks, never thought about that!

**Comment by TerraGitHuB** [comment]
Ok, tested this morning. There is currently an issue with `pkg-install`, where it seems to not install all of the packages that apt usually bundles with the packages I install (namely the settings app, GDM and the network manager) I'm not even sure what the setting app is called in the repositories. To make things even weirder, `purge-installed` doesn't seem to remove all the packages installed either (like gnome-shell)

Not sure what the problem is perhaps @Itai-Nelken @Botspot  you could shed some light on this?

**Comment by Botspot** [comment]
> There is currently an issue with `pkg-install`, where it seems to not install all of the packages that apt usually bundles with the packages I install

That is probably because `pkg-install` runs apt with the `--no-install-recommends` flag. This flag is necessary for several apps, to avoid installing unnecessary, problematic packages.

To make things even weirder, `purge-installed` doesn't seem to remove all the packages installed either (like gnome-shell)
> 
> Not sure what the problem is perhaps @Itai-Nelken @Botspot you could shed some light on this?

Contrary to popular belief, `purge-installed` doesn't actually purge anything! Instead, it marks packages as autoremovable and lets `apt` autoremove what it wants to. This approach **prevents purging anything that other packages depend on**.
So in your case, something must be "depending" on gnome-shell, or otherwise preventing an `apt autoremove` from removing it.

**Comment by theofficialgman** [comment]
closing as botspots suggestions have not been implemented in over a year.

this should have been made a native pi-apps script (its as simple as `install_packages gnome gnome-core gnome-software gnome-shell`)

there isn't any good reason for force removing LXDE. they can co-exist just fine and should co-exist since if for some reason gnome does not work, the user should still have a working DE
