### ISSUE TITLE
Box86 on raspbian arm64 doesnt install

### ISSUE THREAD

**Issue by Jai-JAP** [Botspot/pi-apps#740]
Box86 on raspbian is not installing as libraspberrypi0:armhf conflicts with arm64 version 

I tried removing libraspberrypi0:armhf from the install script but the library libsdl1.2debian:armhf depends on libraspberrypi0:armhf and is not installed resulting the failure of the install script

![Screenshot](https://user-images.githubusercontent.com/78354625/122343687-985ee580-cf63-11eb-8d73-da350a6ae946.png)

The main issue is that libraspberrypi0:armhf cannot be installed on arm64 as it conflicts native version

**Comment by finitelife** [comment]
Confirmed on fresh install (setup and update complete) of 2021-05-07-raspios-buster-arm64 (latest)

**Comment by Itai-Nelken** [comment]
This is a problem.
@Jai-JAP or @finitelife could you remove `libraspberrypi0:armhf` and all the packages that depend on it and see if box86 is still usable?

**Comment by finitelife** [comment]
The point is the computer is unusable. I went and forced the install manually, broke my system. Maybe ask the weekly ppa maintainer to simply have a proper depends in the package?

**Comment by Jai-JAP** [comment]
> @Jai-JAP or @finitelife could you remove `libraspberrypi0:armhf` and all the packages that depend on it and see if box86 is still usable?


I will try this later this week

**Comment by finitelife** [comment]
libavcodec58:armhf libavformat:armhf libsdl1. 2debian:armhf

All of these depend on libraspberrypi0:armhf

Box86 still installs because of a very very basic Deb file without any depends section, but sound won't work (afaik).

In fact, box86 "runs" with half of the listed installs, but this is the biggest issue.

Since my end goal is zoom, I went ahead and installed it manually- adding dependencies one by one. Everything except for audio and screen sharing works... Which makes it rather useless unless I'm spying on a meeting.

**Comment by Itai-Nelken** [comment]
I guess we will have to or remove box86 arm64 or make it limited by removing libraspberrypi0:armhf and all the packages that depend on it.

**Comment by Itai-Nelken** [comment]
>Maybe ask the weekly ppa maintainer to simply have a proper depends in the package?
(...)
>Box86 still installs because of a very very basic Deb file without any depends section(...)

I'm the maintainer of the box86 apt repo. the reason that I didn't put proper dependencies is because on rpiOS 32bit, no extra dependencies are needed, but on 64bit they are. so unfortunately I can't make a one-size-fits-all deb and I don't want to have multiple packages (a rpi one, a rpi 64bit one, a general one for everything else).

**Comment by Jai-JAP** [comment]
Box86 installs perfectly fine in arm64 ubuntu 20.04 20.10 & 21.04.  The problem is only with RPiOS buster arm64 due to improper dependencies and other conflicts.  So I guess it should be removed only for RPiOS buster.

**Comment by Jai-JAP** [comment]
Maybe changing 
```

**Comment by Jai-JAP** [comment]
Solved in #836
