### ISSUE TITLE
Lunar Client

### ISSUE THREAD

**Issue by Pythonic456** [Botspot/pi-apps#786]
[lunarclient.gz](https://github.com/Botspot/pi-apps/files/6763501/lunarclient.gz)

**Comment by Pythonic456** [comment]
Whoops, didn't spot that error.

This one works:
[lunarclient.gz](https://github.com/Botspot/pi-apps/files/6763592/lunarclient.gz)

**Comment by Pythonic456** [comment]
Updated install and uninstall scripts 
[lunarclient.gz](https://github.com/Botspot/pi-apps/files/6768615/lunarclient.gz)

**Comment by gl91306** [comment]
well the main reason i havent asked to add lunar to pi-apps, is because I wanted it to be pi-ware native...

**Comment by Pythonic456** [comment]
I guess that makes sense.
To be honest I hadn't heard of pi-ware until you mentioned it, because not many people have heard of it, whereas pi-apps is huge, almost everyone with a Raspberry Pi has heard of it. And it's amazing that someone has got Lunar Client working on Raspberry Pis, and the more people that know about it the better. Pi-ware isn't as advanced as Pi-Apps just yet, and its userbase isn't anywhere near Pi-Apps. Maybe this would be a good idea?
**Lunar Client [from pi-ware]**

**Comment by gl91306** [comment]
I had previously added issues to add both Godot Engine and Deltarune to pi-apps, but they weren't added within a week. That's when I discovered pi-ware. There were only like 7 people in the discord at the time, and I liked the small community. Right after I asked, both of my apps were instantly added to pi-ware. From there on, I started contributing to the main code, and became part of the pi-ware team. And when I got lunar to first run its startup screen, I had thought to add this to pi-ware. I also thought (like you) that I should add this to pi-aps, so I went in the discord and showed the screenshots, they thought it was cool. But when I told them that lunar was closed source, and I had decompiled it, the deleted my messages. I then added the app to pi-ware, and they had no problems. So from there on, the only reason I continued developing lunar for the raspberry pi, was to add it to pi-ware. I dont care about advancement or userspace. Its kind of personal thing at this point, but I don't think lunar should be added to pi-apps. My final reason is that pi-ware is a small community, and the only way to let it grow, is to add popular apps to it. But if lunar is available in pi-apps and pi-ware, the pi-ware community wont grow. Also, if you really want lunar in pi-apps, the chicly, then this issue might work. [here](https://github.com/piware14/pi-ware/issues/10#issuecomment-840591817). So yeah :P

**Comment by Pythonic456** [comment]
Ok.

**Comment by Botspot** [comment]
> I had previously added issues to add both Godot Engine and Deltarune to pi-apps, but they weren't added within a week. That's when I discovered pi-ware. There were only like 7 people in the discord at the time, and I liked the small community. Right after I asked, both of my apps were instantly added to pi-ware.

@gl91306, I sincerely wish I could keep up with all the app requests and issues. But I cannot and there's nothing I can do about it. I'm sorry. :(
This summer, I'm working at a **summer camp**. In order to keep Pi-Apps going, I built a Raspberry Pi laptop. But keeping up with the issues seems to be an impossible task.

- I have very little free time.
- The WiFi out here is horrible. It would take a week to download a RPiOS image file, assuming the download doesn't fail.
- Just two days ago the Pi Laptop's screen cracked, and I have no way to repair or replace it. I working around the cracked portion of screen with some crazy overscan settings, but at any moment the crack could spread and my ability to work on Pi-Apps would fall to zero.

Therefore, I am forced to prioritize issues:

1. Fixing Pi-Apps core bugs.
2. Fixing installation errors with existing apps.
3. Improving existing apps.
4. Adding new apps, if I think they are a good fit for the app store, are legal, and would be likely to attract many users. Not all apps pass that test.

As can be seen from the number of open issues, I can't keep up alone. Many issues go stale, waiting for a day when someone finds the time to accomplish whatever is being requested.
If your issues take a long time to move along, or never move along, ***please don't take it personally or think that I don't care***. I do care.
Concerning Pi-Ware: if another app store can rise up and stay on top of hundreds of issues better than Pi-Apps has done, then kudos to them. I'll be very impressed. No matter what happens, I believe that a bit of friendly competition will benefit everybody.
