### ISSUE TITLE
Make pi-apps cross platform

### ISSUE THREAD

**Issue by CoderLogy** [Botspot/pi-apps#819]
Hello, fellow pi-apps developer. I think it's time to make pi-apps on other platforms such as Ubuntu, Kali-Linux, Manjaro, or other RPI working distros.
As I am saying this because its only app store for RPI and we all want it to be working with other Debian, arch, and sub-Debian famous distros if RPI

**Comment by CoderLogy** [comment]
As I know it works on some Debian programs but not all apps work on it. Like Minecraft modded of RPI does not work on kali pls make every app working on Debian if u want to stick with Debian or make it arch-based and make fewer apps compatible. But do something on this topic.

**Comment by Tejas-Singh-py** [comment]
This thing is clearly mentioned in the README.md. Majority people use Raspberry Pi OS and Twister OS and it is made for that only. Although we can fork this and make an Arch version, But he only Arch distro available to the Pi is Manjaro. But, if you want you can donate @Botspot some money, so that he can continue the devlopment.

**Comment by CoderLogy** [comment]
Ok thanks and even I want to say like can u do that modded minecraft
doesn't run on kali or arch pls make apps compatible or cross platform
thnks for replying

**Comment by Botspot** [comment]
All the developers here are unpaid volunteers who develop Pi-Apps as a past-time. Including me.
Asking us to make Pi-Apps do <some-difficult-thing> will probably not change much because we are bound to have something more interesting to do instead.

@CoderLogy, if you _really_ want to see Minecraft Pi (Modded) running on Kali Linux, then please consider doing one of the following:
1. Identify and fix the problem yourself. Contributions like this will be greatly appreciated!
2. Open a troubleshooting issue that deals specifically with modded Minecraft Pi running on Kali.
