### ISSUE TITLE
PiGro

### ISSUE THREAD

**Issue by actionschnitzel** [Botspot/pi-apps#82]
[PiGro.zip](https://github.com/Botspot/pi-apps/files/5513487/PiGro.zip)

**Comment by mobilegmYT** [comment]
@actionschnitzel May I ask what this application is?

**Comment by Botspot** [comment]
Looks like some sort of convenient system manager. https://github.com/actionschnitzel/PiGro-Aid-

**Comment by actionschnitzel** [comment]
PiGro is a program designed to make all Debian-based distributions easier to use on the Pi. The most common terminal commands can be executed with one click.

**Comment by Botspot** [comment]
Sorry for the delay.

PiGro looks like it has good potential.

List of things I'd like to see changed:
 - Could the icon be improved? I'm afraid most first-time-viewers will find this icon disturbing and move on. ![2020-11-12-091312_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/98957940-5e0e0100-24c7-11eb-9ae6-a1cbd3e6d6f5.png)
 - There's a typo in the Info window. "Autor:" needs to be changed to "Aut**h**or:"
 - Once you improve the icon, could you also add it to the taskbar icon, instead of the generic blue-n-grey square?
 - Also, if you can think of any other command buttons to add, I think it would be a good idea. Ideas of mine: gparted, have apt remove residual config from uninstalled packages, automatically sign unsigned repositories, maybe some browser links too. (like raspberrypi.org, google, stackexchange, etc.)

**Comment by actionschnitzel** [comment]
Wow, thanks for the constructive criticism. With this I can give the tool the finishing touch.

I'll get in touch as soon as it's done

**Comment by actionschnitzel** [comment]
Done! 
Hope you like it.

https://github.com/actionschnitzel/PiGro-Aid-

**Comment by Botspot** [comment]
@actionschnitzel 
Thanks. Icon is much improved, and I like your website links.

But for the two commands I suggested adding, they weren't what I intended. Here what I meant:
```
# remove residual configuration files
sudo apt autoremove -y && sudo apt clean && sudo apt-get purge -y $(dpkg -l | grep '^rc' | awk '{print $2}')
# Add keys to all unsigned repositories
sudo apt update 2>&1 1>/dev/null | sed -ne 's/.*NO_PUBKEY //p' | while read key; do if ! [[ ${keys[*]} =~ "$key" ]]; then sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys "$key"; keys+=("$key"); fi; done
```

**Comment by Botspot** [comment]
Oh, and right here is a text file I created that helped me memorize common terminal commands. I think you'd find it a jackpot of new ideas.  
[Study Reference.txt](https://github.com/Botspot/pi-apps/files/5534448/Study.Reference.txt)

**Comment by actionschnitzel** [comment]
@Botspot 
Fixed it! ;-)
THX for the Study Reference.txt. Love it! 
In fact, PiGro was born from the idea of ​​a cheat sheet. At one point I got sick of copy and paste.

**Comment by Botspot** [comment]
@actionschnitzel At what point do you think PiGro will have enough functions to make it a useful, rounded-out tool?

**Comment by actionschnitzel** [comment]
@Botspot 

A lot has happened since we last spoke. Pigro is now on v2.1. The appearance of the GUI is now final. I am also satisfied with the functions. For the future, I would switch to a "By Request Model" in terms of functionality.



For my part, it is ready for publication.

**Comment by Botspot** [comment]
> For the future, I would switch to a "By Request Model" in terms of functionality.

I'm not sure what you mean by that. Could you clarify?

**Comment by actionschnitzel** [comment]
Users can suggest new features and I will check if they are useful. Just like you do with Pi-apps or PiKiss on Discord.

**Comment by Botspot** [comment]
Gotcha.

Well if you're ready for it to be added, then I am ready too. However, there are some issues with the install scripts and icons.
I've fixed most of the problems, but haven't finished yet.

**Comment by actionschnitzel** [comment]
Yes Sir, I'm ready! ;-)

**Comment by Botspot** [comment]
Added. Commit a003e24d2dd697f027fa58f5f42cd3d85868cdc3
