### ISSUE TITLE
mcpirevival clamantivirus

### ISSUE THREAD

**Issue by mlohdael** [Botspot/pi-apps#833]
```
Installing Clam Antivirus with install script
Running pkg-install...
Waiting until APT locks are released... Done
Running sudo apt update...
pkg-install failed to run sudo apt update!
APT reported these errors:
E: The repository 'https://mcpirevival.tk/mcpi-packages buster Release' no longer has a Release file.

Failed to install Clam Antivirus with install script!
▲ Need help? Copy the above error output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

Close this window to exit.
```

**Comment by Itai-Nelken** [comment]
update pi-apps and try again. (update by running `echo 'u' | ~/pi-apps/updater`

**Comment by Botspot** [comment]
Looks like @mlohdael installed Minecraft Pi a while back. That's okay, but since then the repository has been moved to https://mcpi-revival.github.io/mcpi-packages.

@mlohdael, could you run this command and send the output?
```
cat /etc/apt/sources.list.d/mcpi-revival.list
```

**Comment by Botspot** [comment]
Update: I got the same error.

Looks like the MCPI developers decided to [change](https://github.com/MCPI-Revival/mcpi-packages/commit/c9011ae046363c28baef69ddbd1654e9237baf5f) their repository URL and took down the old repository. This decision on their end has effectively broken thousands of people's systems around the world, due to the `apt update` error.

To remedy the situation, I've [added a few new lines](https://github.com/Botspot/pi-apps/commit/e2f018bc21e7cce245661d14a743b5f4f60cb3de) to the Pi-Apps main script to detect the problematic file and to automatically fix it.

**Comment by Botspot** [comment]
This issue should be solved now.
