### ISSUE TITLE
Game activity for discord 

### ISSUE THREAD

**Issue by marv-nerd** [Botspot/pi-apps#841]
please add this, it will be pretty cool

for example maybe it could show me playing lunar client

**Comment by Botspot** [comment]
> please add this, it will be pretty cool

If it's not possible to do, it doesn't matter how "cool" it is.
Have you researched to see if this is possible on a Raspberry Pi?

**Comment by Itai-Nelken** [comment]
also we aren't the developers of webcord (the discord client that pi-apps installs).
@spacingbat3 is and I think he is going to implement it in some form in the future.

**Comment by chunky-milk** [comment]
I found this: https://github.com/Pizzabelly/EasyRP, but I'm not sure if it works with WebCord.

**Comment by marv-nerd** [comment]
Ok

**Comment by chunky-milk** [comment]
@marv-nerd maybe open an issue on the WebCord GitHub repo?

**Comment by SpacingBat3** [comment]
> @marv-nerd maybe open an issue on the WebCord GitHub repo?

There's already a discussion about it, and I'm still not decided if I will implement it or not... I put whole list of the reasons why it is not there and why I won't make implement it as a feature, at least when using

I could implement simple activity (not whole Rich Presence mechanism that Discord has) with [Discord.js](https://www.npmjs.com/package/discord.js), but the problem is **this API is for bot account use only** (there's no API for client-use or regular account use) and I'll never implement it as an official Discord feature, but only as the simple extension – I don't want my client go the same way as `cordless` and implement features that would be risky to use for the average users, unless they don't care about being banned (and I'm pretty sure they can detect the account type by `token`, where features like *JavaScript injection* and *CSS injection* are made by regular browsers as well, sometimes without modifications done to the browser behavior or installing extensions – for instance, Chromium injects the CSS style to almost any website, calling that part of the CSS *UserAgent Stylesheet*).

So, again reconsider, what you would prefer? The use of untrusted API that may cause banning the users and identifying WebCord users from the regular Discord users or starting to HTML implementation and trying to improve it or even implement some features using own servers / protocol.

If you're still interested about seeing how it would be implemented, I could give it a try and play with that API (to eventually create it as a WebCord unofficial extension that I may or may not support), but I won't risk to use my own user account token. As of regular user token, the one can get it from the Electron's *Local Storage* database, which I believe (but I haven't tested that yet) allows to login with the `discord.js` API.
