### ISSUE TITLE
Let user choose install path for programms

### ISSUE THREAD

**Issue by Joshy-2010** [Botspot/pi-apps#848]
Amazing App so far!
I have just one small suggestion: I would like to be able to choose an install path once or before installing new apps, similar to most windows programs. That's because after installing a few apps my home directory is absolutely crowded with the programs base folders or .AppImage s. With such a feature I could create an additional "Programs" folder where all this "junk" lies, cleaning up my home directory.
And if I just move this stuff manually all the updates and taskbar launch scripts will get confused, of course.
Not an import issue, maybe a little treat down the line. 
BTW: Sorry for asking, but how do I assign a label?

**Comment by Itai-Nelken** [comment]
>BTW: Sorry for asking, but how do I assign a label?

you cant. only if you are using one of the templates.

this is a good idea, unfortunately it means updating the install scripts of over 100 apps :(
What do you think @Botspot? should we do this?

**Comment by techcoder20** [comment]
Why do you need to update the install scripts. Dont all scripts use the `DIRECTORY` variable ?

**Comment by Itai-Nelken** [comment]
yes, but a lot of them download files to your home folder.

**Comment by techcoder20** [comment]
Well if they do don't they remove the downloaded files or maybe they are required to be there and if they do you probably should move them to `/opt`

**Comment by Botspot** [comment]
> BTW: Sorry for asking, but how do I assign a label?

Use the category editor. It's in Pi-Apps settings.

To answer your main question, Pi-Apps runs a **script** to download and install each app. Some scripts install apps system-wide, while others install apps locally. There is no rhyme, no reason, and no consistency.
Unfortunately, solving this problem would introduce a staggering number of new bugs, especially for migrating users.
This would also take a staggering amount of **time**. Right now we have 105 apps. Each app has two or three scripts. Most of the apps would have to be modified if we wanted them installing system-wide. So we're looking at 220+ scripts to re-learn, re-write, and re-test.
If we wanted all apps to install anywhere, we'd have to modify all 246 app scripts. We would have to create a dialog box to select the installation directory, detect conflicting installations, and create a database of installation directories so that the `uninstall` scripts know where to find the program files to delete. And did I mention that many of these apps would not be capable of installing anywhere? How would those be handled?

**Comment by techcoder20** [comment]
> (maybe you @techcoder20!)

Maybe... I have wanted to make a python fork of pi apps making use of pyqt but that seems a little ambitious. But for the future if this had to be done for some reason what about doing some stuff to make it easier such as
1) Installing pi apps into `/usr/share` like every other app that is installed using apt...
2) Going forward adding a extra instruction for making apps to download anything required into pi-apps `.temp` directory which could be made in the pi apps folder and if those files do need to remain move them to `/opt` under the app's name. Lot of these jobs require the root privileges and also nullifies this point in the readme `Besides those, nothing is modified outside of the Pi-Apps folder.` so....

**Comment by Botspot** [comment]
> Lot of these jobs require the root privileges and also nullifies this point in the readme `Besides those, nothing is modified outside of the Pi-Apps folder.` so....

The quotation refers to _Pi-Apps_ not modifying anything outside of your home directory when you install pi-apps itself. Pi-Apps is portable and will run fine from anywhere, but many of the _apps_ **do** require themselves to be installed somewhere specific.
Pi-Apps is basically a recipe-book that happens to do the cooking for you. It's a collection of tutorials from around the web with an added "Run" button.

Asking the user where to install every app would not benefit many people.

- First, most people wouldn't know where a good location was.
- Then we have to account for all of the apps that, by nature, don't support portability. (Like Chromium)
- No app can be completely self-contained to one directory. How would we handle the app's autostart entries, menu buttons, systemd services, kernel modules, binfmt entries, terminal commands, icon entries, sockets, and other modifications to the root directory?
- Currently, app-creators can copy and paste the commands from a tutorial, and they will have a functional app. If we required people to make new apps install anywhere on the filesystem, the app-creation task would be far more daunting, challenging, confusing, and time-consuming.
- In order to uninstall an app, Pi-Apps would have to remember where the user chose to install the app earlier. Then it would have to send that data to the app's `uninstall` script.
- App updates would be further complicated. Pi-Apps would have to remember where each app was installed, uninstall it, update the scripts, and install it back to the same path. And if an installation failed, how would pi-apps notify the user where an app used to be installed?
- Support would be more complicated. Suppose an app is not launching correctly after being installed. Now we'd have to ask the user where they installed the app before we could check if the app's files were installed correctly.

Then of course, very few people would **care** if pi-apps let you install an app to anywhere. What difference would it make usability-wise? None. Actually, I think the user-experience would be worsened if this was implemented - it increases the likelihood of an installation failure, while reducing our ability to help.

Replying to the OP:

> after installing a few apps my home directory is absolutely crowded with the programs base folders or .AppImage s.

This annoys me too. Right now I have 139 folders in my home directory. Not that many are related to apps on pi-apps, but every folder counts. We've transitioned a few apps to use ~/.local/share instead of /home/pi, and I would like to see this process continue. However, making pi-apps install everything to any folder of your choice is a recipe for disaster.
