### ISSUE TITLE
Pi-Apps Settings Text broken in German language

### ISSUE THREAD

**Issue by Joshy-2010** [Botspot/pi-apps#849]
If I open by Pi - Apps Settings on Raspberry Pi OS with German as the main language, the text gets corrupted. 
![PiAppsSettingsScreenshot](https://user-images.githubusercontent.com/76668448/127165112-ea6d0469-5f25-4efe-9bd0-2d60a9d3b623.png)
I think this could be due to our so called "umlauts" meaning Ä, Ö, Ü, etc., but I am not sure.
Not a super important bug, just wanted to mention it.

**Comment by Itai-Nelken** [comment]
do you have the same problem in other apps? because pi-apps doesn't handle translation at all. pi-apps uses [yad](https://github.com/v1cont/yad) for the gui that uses [gtk](https://gtk.org/), so the problem looks like a missing font for me. can you try installing a font that contains all those characters and see if it fixes the problem?
here is a tutorial on how to add fonts (untested): https://medium.com/source-words/how-to-manually-install-update-and-uninstall-fonts-on-linux-a8d09a3853b0

**Comment by Joshy-2010** [comment]
Sadly, this didn't fix it. Maybe this only an issue with something broken in my installation, then it shouldn't be a big problem. But maybe other people have the same experience?

**Comment by Botspot** [comment]
This may be due to how GTK is responding to our punctuation space substitution.

In the settings script, many of our command-line arguments for yad will contain space characters. "Check for updates", "App List Style", "Enable analytics", etc.

These space characters would cause problems on the command like if they were allowed to remain. To solve this, our `settings` script substitutes all space characters for a unicode whitespace character called a "punctuation space".
Perhaps GTK was never designed to handle this character when performing automatic language translation?

**Comment by Joshy-2010** [comment]
You are right Botspot. As a test, I went into the settings file and replaced the following  lines
![2021-07-29-162753_970x864_scrot](https://user-images.githubusercontent.com/76668448/127511227-9e42e00c-2a79-43e9-82cf-42d2f1a1ff55.png)
Now, of course, I have the letter 'a' stuffed between words, but at least the error characters are gone.
![2021-07-29-162803_342x453_scrot](https://user-images.githubusercontent.com/76668448/127511320-e0d00216-02a0-4a88-ab40-af72bce397da.png)

**Comment by Botspot** [comment]
With recently gained knowledge about bash **arrays**, I've been able to fix the Settings app to no longer need this punctuation space fix.
