### ISSUE TITLE
Can't install Ulancher

### ISSUE THREAD

**Issue by Audvikhp737** [Botspot/pi-apps#855]
![problem](https://user-images.githubusercontent.com/88205594/127687596-b5a15b5f-00b7-4c50-a7dc-d95b8ed70676.png)

**Comment by Botspot** [comment]
The mcpirevival.tk repository error is a [known issue](https://github.com/Botspot/pi-apps/issues/833). This issue was caused when the Minecraft Pi developers decided to take down their repository and put up a new one without telling me and without pushing an update to Minecraft Pi. This effectively broke all MCPI user's systems, which were expecting the old repository to still be there when it wasn't.
Out of desperation, I [added an emergency fix](https://github.com/Botspot/pi-apps/commit/e2f018bc21e7cce245661d14a743b5f4f60cb3de) to the latest main Pi-Apps script. If the faulty Minecraft Pi repository is detected, Pi-Apps will automatically repair it for you upon launch. In order for this fix to come through, you need to update Pi-Apps.

The raspotify error is not caused by Pi-Apps It appears that you had previously installed Raspotify, and now the repository is offline.
To fix it, you will have to remove the repository.
Either it will be in the **`/etc/apt/sources.list`** **file** (so **delete the line** in the file), or it will be in the **`/etc/apt/sources.list.d`** **folder**. (so **delete the file** that mentions raspotify). You will need root permissions to do this.

**Comment by mobilegmYT** [comment]
@Audvikhp737

**Comment by Audvikhp737** [comment]
thanks for news

**Comment by Audvikhp737** [comment]
and hey can you please tell mehow to update pi apps

**Comment by Audvikhp737** [comment]
and i also had issue installing other such as bongo cam

**Comment by Audvikhp737** [comment]
and i also tried re-installing pi apps

**Comment by Audvikhp737** [comment]
same issue
![smae](https://user-images.githubusercontent.com/88205594/127850304-4f33fb10-c865-432f-ae6e-d00389933a50.png)

**Comment by Audvikhp737** [comment]
![agin](https://user-images.githubusercontent.com/88205594/127851261-4c6d0258-57ae-4128-8129-038c6e081537.png)
hey i tierd detling raspspotify but this happend

**Comment by Audvikhp737** [comment]
sorry if i am doing somthing dumb!
i new to raspberry pi

**Comment by Audvikhp737** [comment]
I made this auccont beacause of this eorr

**Comment by Audvikhp737** [comment]
> The mcpirevival.tk repository error is a [known issue](https://github.com/Botspot/pi-apps/issues/833). This issue was caused when the Minecraft Pi developers decided to take down their repository and put up a new one without telling me and without pushing an update to Minecraft Pi. This effectively broke all MCPI user's systems, which were expecting the old repository to still be there when it wasn't.
> Out of desperation, I [added an emergency fix](https://github.com/Botspot/pi-apps/commit/e2f018bc21e7cce245661d14a743b5f4f60cb3de) to the latest main Pi-Apps script. If the faulty Minecraft Pi repository is detected, Pi-Apps will automatically repair it for you upon launch. In order for this fix to come through, you need to update Pi-Apps.
> 
> The raspotify error is not caused by Pi-Apps. It appears that you had previously installed Raspotify from a tutorial or something, and now the repository is offline.
> To fix it, you will have to remove the repository.
> Either it will be in the **`/etc/apt/sources.list`** **file** (so **delete the line** in the file), or it will be in the **`/etc/apt/sources.list.d`** **folder**. (so **delete the file** that mentions raspotify). You will need root permissions to do this.

how to get root permision

**Comment by techcoder20** [comment]
> ![agin](https://user-images.githubusercontent.com/88205594/127851261-4c6d0258-57ae-4128-8129-038c6e081537.png)
> hey i tierd detling raspspotify but this happend
> permision dedeind

Open a terminal and run `sudo pcmanfm` This will open the file manager again but this time with root privileges. If you want to do it from the terminal you can run `sudo rm /etc/apt/sources......`  another option is to login as the root user. Run `sudo passwd` to set a root password. After that just run `su` in the terminal and click enter and that will log you in as a root shell and then you can remove the file. Choose which ever method feels easy for you :)

**Comment by Audvikhp737** [comment]
> > ![agin](https://user-images.githubusercontent.com/88205594/127851261-4c6d0258-57ae-4128-8129-038c6e081537.png)
> > hey i tierd detling raspspotify but this happend
> > permision dedeind
> 
> Open a terminal and run `sudo pcmanfm` This will open the file manager again but this time with root privileges. If you want to do it from the terminal you can run `sudo rm /etc/apt/sources......` another option is to login as the root user. Run `sudo passwd` to set a root password. After that just run `su` in the terminal and click enter and that will log you in as a root shell and then you can remove the file. Choose which ever method feels easy for you :)

thanks A lot!!! techcoder20

**Comment by Audvikhp737** [comment]
:)

**Comment by techcoder20** [comment]
Is it working now ?

**Comment by Audvikhp737** [comment]
Yes, it is working.
