### ISSUE TITLE
rework the update process of apps

### ISSUE THREAD

**Issue by conrackx** [Botspot/pi-apps#862]
I think it would be useful to change the order in which the reinstall process occurs.

As far as i can tell, when an install script is updated, the package is uninstalled, downloaded, renamed and then installed again.

I think a more optimal reinstall would be to download and process the package first, and then if successful, uninstall the old version and install the newer one. 

The reason behind my suggestions is that i have a slow and faulty internet connection and when an update arrives, the download process fails many times before reaching a full download, also leaving me without said application for quite some time. 

I know for most of you that's not even a problem, but i figured i could make the suggestion because even though i'm not very bash savvy to make the pull request myself, reading at the code gives me the impression that it wouldn't require excessive effort, as the update process of everything seems to be handled by a single script instead of a different code block in the script of every app.

Thanks for reading and if there's a technical reason for which this cannot be done ("maybe to avoid the program being used while reinstall ??? or something like that") or maybe "too hard", id like to hear from you guys.

**Comment by Botspot** [comment]
> As far as i can tell, when an install script is updated, the package is uninstalled, downloaded, renamed and then installed again.

Not exactly, though you were close. Updating goes like this:

1. Check for updates. If successful, this downloads (using `git clone`) an entire fresh Pi-Apps folder to `~/pi-apps/update/pi-apps`.
2. Individual apps are cross-compared between the main Pi-Apps folder and the new Pi-Apps folder.
3. In addition, the main pi-apps scripts are compared to the update-folder versions.
4. If anything (app or pi-apps file) doesn't match the freshly-downloaded version, it is placed on a list of updatable items.
5. If the list of updatable items is not empty, Pi-Apps will display a notification, asking permission to update. Here you can choose to opt out of individual files or apps by unchecking an item in the list.
6. First, the new files are copied from the downloaded pi-apps folder to the main pi-apps folder.
7. Then **for apps**: If an app is **_currently installed, and its install script was modified_**, the app will be **reinstalled**. Otherwise, the app folder will merely be copied from the downloaded pi-apps folder to the main pi-apps folder.

App update/reinstall procedure:

1. Before the app is updated with new scripts from the downloaded pi-apps folder, **first the app is uninstalled**.
2. Once the app is uninstalled, _then_ the app's new installation scripts are copied in from the new pi-apps folder to the main pi-apps folder.
3. Now that the new scripts are in place, the app's new install script is executed. Most of our install scripts will download something from the Internet, then perform other operation(s) on the file(s) it downloaded.

Now, to address your suggestion @conrackx: If I understand correctly, you are proposing that during an update, Pi-Apps will install the new app, _before_ uninstalling the old one. So at one point during the update process, the same app would somehow be installed twice and not interfere with itself.
Or are you asking that the old app not be uninstalled before the new app's files are fully downloaded? And once the new app's files are fully and successfully downloaded, the old app would be uninstalled and the new app would be installed.

In any case, I don't see how this proposal would be possible without having to edit every single app's scripts to accommodate this separate download procedure. Right now all of our installation scripts will download files, then finish the installation immediately. If we want to change this behavior, so that apps can install themselves offline with pre-downloaded archives, that would require modifying every single install script at a minimum.

Additionally we'd have to sort out interesting edge cases:

- What if the installation script is directly running a script from github.com?
- What if the installation script has to download something, configure it, then download something else afterwards to repair the first thing it downloaded?

**Comment by conrackx** [comment]
> Or are you asking that the old app not be uninstalled before the new app's files are fully downloaded? And once the new app's files are fully and successfully downloaded, the old app would be uninstalled and the new app would be installed.

This exaclty is what i was suggesting,

> Right now all of our installation scripts will download files, then finish the installation immediately. If we want to change this behavior, so that apps can install themselves offline with pre-downloaded archives, that would require modifying every single install script at a minimum.

but this right here i didn't account for. My suggestions was simply a rearrangement of the process i thought was:

1. Update modified download scripts
2. Uninstall presently-installed app whose script has been updated
3. Download the latest version of the uninstalled app
4. install the latest version.

to this by just swapping steps 2 and 3:

1. Update modified download scripts.
**2. Download the newer version of the scheduled for update apps**
**3. If fully downloaded uninstall presently-installed app**
4. Install the latest version.

I thought the download and installation process was a self contained script, but if i understand you correctly, they're also responsible for signaling the end of said process and would effectively render the rearrangement more trouble than it's worth, without mentioning those not-so edge cases, which i think you refer to apps like box86/64 that are recompiled at every update and need to be erased before they can be downloaded and compiled; also i didn't thought of multiple-update cases.

Thanks for the explanation and i actually didn't thought of something as far as offline installation, which really seems like it would complicate the flow of updates; if i can come up with a solution that i can offer later on, i will shirley bring it to you.

**Comment by Botspot** [comment]
> I thought the download and installation process was a self contained script, but if i understand you correctly, they're also responsible for signaling the end of said process and would effectively render the rearrangement more trouble than it's worth, without mentioning those not-so edge cases, which i think you refer to apps like box86/64 that are recompiled at every update and need to be erased before they can be downloaded and compiled; also i didn't thought of multiple-update cases.
> 
> Thanks for the explanation and i actually didn't thought of something as far as offline installation, which really seems like it would complicate the flow of updates; if i can come up with a solution that i can offer later on, i will shirley bring it to you.

Thank you for understanding: We simply do not have the time, patience, or manpower to rewrite all the apps in pi-apps.
