### ISSUE TITLE
Failled to install Wine on Raspberry pi 4 

### ISSUE THREAD

**Issue by PhilZPhaZ** [Botspot/pi-apps#908]
Hi, when i try to install wine with pi-apps, i have an error
Installing Wine (x86)...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/5.10.17-v7l+/modules.dep.bin'
modprobe: FATAL: Module configs not found in directory /lib/modules/5.10.17-v7l+
Failed to run sudo modprobe configs!

Failed to install Wine (x86) with install-32 script!
\u25b2 Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

**Comment by Botspot** [comment]
We've seen this error reported a lot, but it's not our fault. This problem is caused by your operating system, must likely by user-interference.

Could you tell us what operating system you are using and all modifications you've made to it since installing it?
And does the same error occur for other `modprobe` commands like this one?
```
sudo modprobe fuse
```

**Comment by demib72** [comment]
I am currently having the same issue. When I do sudo modprobe fuse I get the following:

modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/5.10.63-v7l+/modules.dep.bin'
modprobe: FATAL: Module fuse not found in directory /lib/modules/5.10.63-v7l+
