### ISSUE TITLE
Error installing Pycharm CE

### ISSUE THREAD

**Issue by Kassyuskaly** [Botspot/pi-apps#924]
Error installing apps in PI-Apps

error presented in the terminal below.

Hit:1 http://ports.ubuntu.com/ubuntu-ports groovy InRelease
Hit:2 http://ppa.launchpad.net/lah7/ubuntu-mate-colours/ubuntu groovy InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports groovy-updates InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports groovy-backports InRelease
Hit:5 http://ports.ubuntu.com/ubuntu-ports groovy-security InRelease
All packages are up to date.

Creating dummy deb...
Waiting until APT locks are released... Done

Installing dummy deb...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pi-apps-e1162640 : Depends: python-pip but it is not installable
E: Unable to correct problems, you have held broken packages.

Apt finished.
Failed to install the packages!
APT reported these errors:
E: Unable to correct problems, you have held broken packages.

Failed to install Pycharm CE with install script!
▲ Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

Close this window to exit.

**Comment by Botspot** [comment]
This is because your operating system has decided to remove python-2.

All apps that use `pip` will no longer work.

**Comment by Itai-Nelken** [comment]
maybe a newer version of pycharm will work with pip3?

**Comment by fabianmendes** [comment]
> maybe a newer version of pycharm will work with pip3?

I once had told that only good working Pycharm version for 32-bit always will be the 2018 specified 32-bit version and I don't know why it was changed on the pi-apps scripts. The 64-bit installation is the only updatable alongside the JetBrains upgrades so far.

otherwise, @Botspot  I think pycharm has issues on running python 2 from its terminal and even having it on the configuration as default. The user could try to path the python 2 on Pycharm after installing it. or just running their python-2 code from the terminal. About the installation issue, _I have spoken_  for 32-bit, install the 2018 version only.

**Comment by Botspot** [comment]
Pycharm has been updated. https://github.com/Botspot/pi-apps/commit/1bc0d07b3cca604ffccbcc29d217c75655bf2cbe
