### ISSUE TITLE
APT reported an unresolvable repository

### ISSUE THREAD

**Issue by PiBunny** [Botspot/pi-apps#949]
I was prompted to update the FreeTube App via my Pi-Apps, and after several attempts, I am unable to do so. My Raspberry Pi3B+ is giving me an error regarding "APT reported an unresolvable repository", and "failed to install with install -32 script". After some discussion, I also tried to find and execute the install 64 script in the Pi-Apps folders (since that would be the script actually needed in my case) ... that also resulted in the same issue, and inability to install. I have sent in the error reports to the devs, via the Pi-Apps prompt. Thank you in advance for looking into this issue, or any tips you might have.

**Comment by Botspot** [comment]
First of all, thank you for reaching out. Error reports are good in some ways and bad in other ways.

- They are more convenient than a github issue, for us and for you.
- But, if the error is being caused by **_something wrong_** with **_your_** operating system, we have no way to "reply" to the error report to let you know.

> `APT reported an unresolvable repository`

That right there is your problem. I've made changes to the `pkg-install` script to automatically diagnose apt-related errors on your behalf.
Above that error, you will find more output saying that apt could not connect to a website. Could you send that output to me?

The easiest way to get that output now is by running this command:
```
sudo apt update
```

**Comment by PiBunny** [comment]
The latest FreeTube update has resolved the install issues.
