### ISSUE TITLE
Apps Refuse To Install.

### ISSUE THREAD

**Issue by Vicky-Boi** [Botspot/pi-apps#959]
I'm using Pi-Apps to install Box86 and a few other apps here. Whenever I try to install any app, it always throws a few errors at me. I attached the terminal output below.
[terminal output.log](https://github.com/Botspot/pi-apps/files/7193236/terminal.output.log)

**Comment by Botspot** [comment]
First of all, thank you for reaching out. In case you were wondering why you were not offered a button to send us an error log, it's because this is an error not caused by Pi-Apps.

It looks like you were playing around in `/etc/apt/sources.list` and added your own repository.
If you didn't do it, then some other software did. Looks like the problematic repository is `https://repo.**protonvpn**.com/debian`.

## To fix:
APT repositories are located in two places:

- A single **line** in the text **file** located at `/etc/apt/sources.list`
- A single **file** in the **folder** located at `/etc/apt/sources.list.d`

Be careful. Try to look through sources.list first and look for any lines that mention protonvpn. If you don't see any, look inside all the files in sources.list.d and see if any of them mention protonvpn.
When you find the right line, delete it and then save the file.
Alternatively, if the entire file _only_ contains stuff for protonvpn, you could delete the whole file if you wanted to.

*Note: Modifing files in the /etc directory require root privileges. This can be accomplished by running `sudo`. If you're using Raspberry Pi OS, you can launch the File Manager as root with this command: `sudo pcmanfm`

**Comment by Vicky-Boi** [comment]
Followed all the steps and it works perfectly now. Thank you!
